README.rst

Signed-off-by: Przemek Tredak <ptredak@nvidia.com>

Added the link to the User Guide

---

transformer_engine/pytorch/module.py

fp8_autocast bug fix when switching from non-fp8 execution

---

transformer_engine/pytorch/module.py
transformer_engine/pytorch/transformer.py

Add checks for tensor parallel use case to ensure all-reduce is called only when necessary

---

transformer_engine/pytorch/distributed.py

`None` is a valid group to pass into the TE API for the distributed use case and thus shouldn't be treated as a no-argument.

Bug fix for distributed TE case

---

tests/cpp/operator/test_layernorm.cu
tests/cpp/test_common.cu
tests/cpp/test_common.h
transformer_engine/common/include/transformer_engine/layer_norm.h
transformer_engine/common/layer_norm/ln_api.cpp
transformer_engine/common/layer_norm/ln_fwd_kernels.cuh
transformer_engine/pytorch/csrc/common.cu
transformer_engine/pytorch/csrc/common.h
transformer_engine/pytorch/csrc/extensions.cu

fp8_out argument is not needed since the output Tensor already has the proper type set.

Remove fp8_out from the LN API

---

transformer_engine/common/layer_norm/ln_bwd_kernels.cuh

I forgot to check some bounds.
Running on an A2, I see no unit test failures with the general layer norm kernels using `compute-sanitizer`. I do see one failure with the optimized kernel since `dgamma` is ever so slightly outside the numerical tolerances, but that shouldn't have been affected by this change.

Fix illegal memory access in general layer norm backward kernel

---

docs/examples/advanced_optimizations.ipynb
docs/index.rst

Tutorial was not linked to the main page and so was not rendered.

Link performance optimization tutorial to docs

---

docs/api/c/index.rst
docs/api/c/softmax.rst
transformer_engine/common/fused_softmax/scaled_masked_softmax.cu
transformer_engine/common/fused_softmax/scaled_upper_triang_masked_softmax.cu
transformer_engine/common/include/transformer_engine/softmax.h
transformer_engine/pytorch/csrc/extensions.cu

Add docstrings to `softmax.h` for C API and remove const modifiers from output Tensors.

Softmax docstrings and type fixes

---

transformer_engine/pytorch/module.py
transformer_engine/pytorch/transformer.py

Ensure that inputs to APIs are of contiguous memory ([torch.contiguous_format](https://pytorch.org/docs/stable/tensor_attributes.html#torch.memory_format)). Without this, memory related bugs are encountered in kernels.

Ensure contiguous inputs

---

qa/L0_cppunittest/test.sh
tests/cpp/operator/CMakeLists.txt

The unit test time will be increased as more kernels are added. This PR is to reduce the unit test time for a shorter development cycle.
1. Calculating the reference answer is the hotspot of unit test time on the CPU. Enabling `-O2` can bring 6~7x speedup. (`TestLN/float32Xfloat32X2048X12288` from 12645ms to 1874ms)
2. Set ctest parallel level to 4, which can run multiple tests on different processes. Current unit tests are small, I think OOM or extreme resource contention should not happen.

Reduce unit tests time

---

tests/cpp/operator/CMakeLists.txt
tests/cpp/operator/test_cast_transpose_dgeglu.cu
tests/cpp/operator/test_dgeglu.cu
tests/cpp/operator/test_geglu.cu
transformer_engine/common/activation/gelu.cu
transformer_engine/common/include/transformer_engine/activation.h
transformer_engine/common/include/transformer_engine/transpose.h
transformer_engine/common/transpose/cast_transpose_fusion.cu
transformer_engine/common/util/math.h
transformer_engine/common/util/vectorized_pointwise.h

1. [GeGLU](https://arxiv.org/pdf/2002.05202.pdf) is used in T5. Fusing `gelu`, `gate`, `elementwise_mul` can highly reduce the global memory read/write and increase the performance. Two backward kernels are also added, `dgeglu` is for `fp16`, `bf16`, `fp32`, and `dgeglu_cast_transpose` is for `fp8` output.
2. Because `geglu` and `dgeglu` has multiple input/outputs. This PR extends `CheckAlignment` to support multiple input/outputs.
3. Move `gelu` and `dgelu` to `util/math.h`

Add GeGLU and the corresponding gradient kernels

---

transformer_engine/pytorch/utils.py

In PyTorch, custom autograd functions run with gradients disabled. This means each time a new tensor is cast or created, the `requires_grad` field is set to False.  When we cast the `weight` because of AMP, this is what happens and the wgrad is not computed and null grad is returned (silent fail). **Note:** If a gradient is returned from backward, PyTorch will cast it to input type before populating the `.grad` field.

Fix gradients when using AMP

---

qa/L0_lint/pylintrc
tests/cpp/operator/test_layernorm.cu
tests/test_onnx_export.py
tests/test_transformerengine.py
transformer_engine/common/include/transformer_engine/layer_norm.h
transformer_engine/common/layer_norm/ln.h
transformer_engine/common/layer_norm/ln_api.cpp
transformer_engine/common/layer_norm/ln_bwd_kernels.cuh
transformer_engine/common/layer_norm/ln_fwd_kernels.cuh
transformer_engine/pytorch/cpp_extensions.py
transformer_engine/pytorch/csrc/extensions.cu
transformer_engine/pytorch/csrc/extensions.h
transformer_engine/pytorch/csrc/ts_fp8_op.cpp
transformer_engine/pytorch/module.py
transformer_engine/pytorch/te_onnx_extensions.py
transformer_engine/pytorch/transformer.py

This PR adds a new option to LayerNorm (and other APIs that use LN) to initialize gamma parameter to 0 and use (1+gamma) instead of gamma.
This improves the precision characteristics of LN parameters and makes some techniques, like the weight decay, easier to implement for LN parameters.

Zero-centered gamma support in LayerNorm (LayerNorm1p)

---

transformer_engine/pytorch/module.py

This was mistakenly added during #41

fix bug in non-FP8 nvfuser path

---

examples/jax/encoder/test_single_gpu_bf16_training.py
examples/jax/encoder/test_single_gpu_fp8_training.py
qa/L0_jax_unittest/test.sh
tests/jax/test_custom_call_compute.py
tests/jax/test_helper.py
tests/jax/test_layer.py
tests/jax/test_mnist.py
tests/jax/test_sharding.py
tests/jax/utils.py
transformer_engine/jax/__init__.py
transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/dot.py
transformer_engine/jax/fp8.py
transformer_engine/jax/layernorm.py
transformer_engine/jax/mlp.py
transformer_engine/jax/module.py
transformer_engine/jax/sharding.py
transformer_engine/jax/softmax.py
transformer_engine/jax/transformer.py

Add TE/JAX high-level modules and API
*  transformer_engine/jax/__init__.py
*  transformer_engine/jax/module.py
*  transformer_engine/jax/softmax.py
*  transformer_engine/jax/transformer.py 
Add TE/JAX unittests to cover high-level API
*  qa/L0_jax_unittest/test.sh
*  tests/jax/test_layer.py
*  tests/jax/test_mnist.py
*  tests/jax/test_sharding.py
*  tests/jax/utils.py
Add TE/JAX exampels
* examples/jax/encoder/test_single_gpu_bf16_training.py
* examples/jax/encoder/test_single_gpu_fp8_training.py
TE/JAX bugfix
* tests/jax/test_helper.py
* transformer_engine/jax/fp8.py
* transformer_engine/jax/sharding.py

Add TE/JAX high-level modules,  unittests and examples

---

transformer_engine/jax/dot.py
transformer_engine/jax/layernorm.py
transformer_engine/jax/mlp.py

- Fixing the failure when running FP8 with multi-devices by properly slice amax buffers.

Adding slice to fix failure with multi-devices.

---

.github/workflows/build_docs.yml
docs/api/common.rst
docs/api/pytorch.rst
docs/conf.py
transformer_engine/pytorch/transformer.py

As we move forward with the support for multiple frameworks, the behavior of autodoc to import everything becomes an issue - we would need to have a container with all frameworks installed, which is going to be an issue with handling all of the dependencies. AutoAPI does not need to import the module to generate documentation, which is much better in this case.
Also add GitHub action to build the documentation.

Move from Sphinx Autodoc to sphinx-autoapi

---

transformer_engine/pytorch/fp8.py

Without this change, the following use case errors out with a not very helpful message,
```
import torch
import transformer_engine.pytorch as te
model = te.Linear(512, 512)
inp = torch.rand((128, 512), device="cuda")
epochs = 5
def train():
with te.fp8_autocast(enabled=True):
for _ in range(epochs):
activation = model(inp)
train()
train() # Error!
```
This PR fixes this case and catches the error the first time `train()` is called in the above script. The "correct" usage is below:
```
import torch
import transformer_engine.pytorch as te
model = te.Linear(512, 512)
inp = torch.rand((128, 512), device="cuda")
epochs = 5
def train():
for _ in range(epochs):
with te.fp8_autocast(enabled=True):
activation = model(inp)
train()
train()
```

Raise autocast usage error

---

transformer_engine/pytorch/distributed.py

`torch.distributed._all_gather_base` and `torch.distributed._reduce_scatter_base` are deprecated.

Update PyTorch comm API

---

transformer_engine/pytorch/module.py
transformer_engine/pytorch/utils.py

The current restriction of having modulo16 for all dimensions is too harsh and breaks `examples/pytorch/mnist/main.py` when executing with FP8.

Relax dimension checks for fp8 exec

---

transformer_engine/common/transpose/cast_transpose.cu

@vasunvidia has observed poor performance when running the cast-transpose kernel with small matrices. The issue is that we use a per-CTA tiling scheme with hard-coded 8B vector loads and stores, and if the number of CTAs drops below the number of SMs (132 for H100) we can expect reduced throughput. This PR adds a very rough heuristic: if the data is small enough that we would run with fewer than 128 CTAs, reduce the vector size to 4B to increase the number of CTAs by a factor of 4.
Running on a H100 SXM with FP16 input and FP8 output:
| Dims | Run time (8B vector size) | Run time (heuristic vector size) |
|----|----|----|
| 512 x 512 | 6.17 us | 3.80 us |
| 768 x 768 | 6.43 us | 3.79 us |
| 1024 x 1024 | 6.75 us | 3.94 us |
| 1536 x 1536 | 6.90 us | 5.13 us |
| 2048 x 2048 | 6.98 us | …

Use 4B vector loads/stores in cast-transpose kernel for small matrices

---

transformer_engine/common/__init__.py
transformer_engine/pytorch/transformer.py

This is a modification of the bugfix in https://github.com/NVIDIA/TransformerEngine/pull/120, with some small changes for safety and style.
Pinging @ngoyal2707. Closes https://github.com/NVIDIA/TransformerEngine/pull/120.

Fix zombie process when querying TE install path

---

tests/jax/test_sharding.py
tests/jax/utils.py
transformer_engine/jax/fp8.py
transformer_engine/jax/module.py
transformer_engine/jax/transformer.py

1. Added support to `transpose_batch_seqlen` when `decoded=True`.
2. Fixed wrong masking issues in MultiHeadAttention when `decoded=True`.
3. Fixed missing dropout broadcast dims in LayerNormMLP.

Fix Bugs of TE/JAX

---

transformer_engine/pytorch/te_onnx_extensions.py

The function `_type_utils.JitScalarType.from_value` causes segfaults during the ONNX exports for torch version <1.14.

Fix segfault during onnx export

---

tests/pytorch/test_torch_save_load.py
transformer_engine/pytorch/module.py

On torch model loading, update fp8 scale_inv from the extra state tensor. 
+ test to validate all extra state attributes are consistent after torch load.

Bugfix - compute scale_inv when loading checkpoint

---

.github/workflows/build.yml
README.rst
setup.py

Fixes #142 
~Pybind11 must be installed with `[global]`, otherwise cmake won't find it during the TF build.~
~See pybind11 docs here about this option: https://pybind11.readthedocs.io/en/stable/installing.html#include-with-pypi~
Jax build sets `DCMAKE_PREFIX_PATH` to allow cmake to find the pybind11 cmake config even in the python user package directory. We will do the same for TF.

Set DCMAKE_PREFIX_PATH for TensorFlow build to build with pip pybind11

---

tests/jax/test_custom_call_compute.py
tests/jax/test_layer.py
tests/jax/utils.py
transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/csrc/modules.cpp
transformer_engine/jax/csrc/modules.h
transformer_engine/jax/layernorm.py
transformer_engine/jax/mlp.py
transformer_engine/jax/module.py
transformer_engine/jax/transformer.py

This PR adds `zero_centered_gamma` support for JAX layernorm in different modules.
For `TransformerLayer`, `MultiHeadAttention` module, the gamma initializer becomes 0s initializer and use (1+gamma) instead of gamma when `zero_centered_gamma` is used.
It is similar for `LayerNorm`, `LayerNormDenseGeneral`, and `LayerNormMLP`. The default initializer for them is `nn.initializers.ones` when `zero_centered_gamma` is `False`, and it becomes `nn.initializers.zeros` when `zero_centered_gamma` is `True` through `__post_init__`. Besides, users can still provides their own initializer through `scale_init` for these three modules.

Zero-centered gamma (Layernorm1p) support for JAX

---

tests/pytorch/test_onnx_export.py
transformer_engine/pytorch/module.py

In this commit:
- Whenever converting a torch.tensor to numpy, we need to first migrate the tensor storage to the host CPU.
- Add a warning not to do contant-folding when exporting to ONNX. This is due to a torch.onnx export bug.
- Refactor compare_outputs

Fix model load exception when state resides on GPU

---

.github/workflows/lint.yml
setup.py
transformer_engine/pytorch/transformer.py

H100 support has been added to upstream flash attention including other features such as [deterministic execution](https://github.com/HazyResearch/flash-attention/pull/147) and [cuda graph capture](https://github.com/HazyResearch/flash-attention/pull/166). These are available in v1.0.2.

Switch to upstream flash-attn

---

transformer_engine/common/fused_attn/fused_attn_fp8.cu

This is to help remove some of the warnings when compiling transformer_engine/common/fused_attn/fused_attn_fp8.cu

Remove used function ternary_pw_op_create

---

README.rst
docs/api/jax.rst
examples/jax/encoder/test_model_parallel_encoder.py
examples/jax/encoder/test_multigpu_encoder.py
examples/jax/encoder/test_single_gpu_encoder.py
examples/jax/mnist/test_single_gpu_mnist.py
tests/jax/test_layer.py
tests/jax/test_sharding.py
transformer_engine/common/utils.py
transformer_engine/jax/__init__.py
transformer_engine/jax/flax/__init__.py
transformer_engine/jax/flax/module.py
transformer_engine/jax/flax/transformer.py

1. Collect Flax related modules to a sub-folder, flax.
2. Add a function to unify scale_init for zero-centered-gamma LN.
Note: This PR is for the further Praxis (another NN library on top of JAX) support.

[JAX] Adjust Module Structure.

---

transformer_engine/pytorch/module.py

This error shows up in certain configurations of BERT/T5 when the `Linear` API is used to run in column parallel mode.

Bugfix in Sequence Parallelism

---

tests/pytorch/test_onnx_export.py
transformer_engine/common/fused_attn/fused_attn_fp8.cu
transformer_engine/pytorch/te_onnx_extensions.py

When exporting LayerNorm make sure that the weights and bias inputs have the same type as the LN input.
Also:
* Add a regression test.
* Add environment variable to override directory of generated test artifacts

Fix LayerNorm ONNX export

---

docs/installation.rst

I confirmed with cuDNN team that the exact version that allows compilation of TE with cuDNN frontend is 8.1 instead of 8.0, so making this correction here.

Correct cuDNN version requirement

---

tests/pytorch/test_onnx_export.py

- Allow saving i/o tensors when onnxruntime inference is skipped
- Support saving multiple outputs

Fixes to test_onnx_export when saving input and output tensors

---

setup.py
transformer_engine/pytorch/transformer.py

The `distutils` package is now deprecated and support will be fully removed in Python 3.12 (see [pep 0632](https://peps.python.org/pep-0632/)). The deprecation notice also fails linter tests from `distutils` v3.10.6 onwards and in the newer containers.

Remove use of distutils

---

setup.py
transformer_engine/pytorch/transformer.py

Fixes #189. 
`packaging` is apparently not a built-in and results in build failures if it's not installed in the user's environment. `pkg_resources` is also not built-in but it's [vendored into setuptools](https://github.com/pypa/setuptools/tree/a94ccbf404a79d56f9b171024dee361de9a948da/pkg_resources) so it's safe to use during build as well as RT.

Get packaging module from setuptools

---

transformer_engine/pytorch/module.py

#130 adds the option of running TE with no bias.
DDP requires all parameters (and buffers) to be on the device when the model is wrapped by distributed data parallel. Moving the dummy bias buffers to cuda does the trick.

DDP support for no-bias option [PyTorch]

---

transformer_engine/jax/flax/module.py
transformer_engine/jax/flax/transformer.py

- Fixed typo, `bais` to `bias`.
- Fixed the wrong shape of bias in `LayerNormMLP` when enable `gated` activations, such as `('gelu', 'linear')`.
> For example, if we apply `('gelu', 'linear')`, then the shape of bias should be `('num_act', 'hidden')`, that is `(2, hidden)` in this case, but we always generate `(1, hidden)`, then led to incorrect results when `enable_bias=True`.
- Fixed the issue of misshing `bias_axes` parameter passed to sub-layers in `TransformerLayer`, which cause incorrect `PSpec` in sharding when running with mutli-devices.

[JAX] Fix missing axes parameters in TransformerLayer and the wrong shape of bias in LayerNormMLP

---

transformer_engine/pytorch/jit.py
transformer_engine/pytorch/transformer.py

This makes the bias-dropout-add fusion and bias-gelu fusions deterministic across checkpointing.

Deterministic JIT warmup

---

examples/jax/encoder/test_multigpu_encoder.py
transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/csrc/extensions.cpp

1. According to https://github.com/NVIDIA/TransformerEngine/pull/217#issuecomment-1545313438, fix the lowering bug of softmax custom-call.
It has been verified by JAX 0.4.8 and JAX 0.4.11 (i.e. `jax:nightly-py3-base-2023-05-12`).
```sh
NVIDIA Release main (build 59902119)
JAX Version 0.4.8
NVIDIA Release nightly (build 60183022)
JAX Version 0.4.11
```
All unit tests passed with 2xH100.
2. Relax the threshold of multigpu example as a workaround of deterministic issue for now

[JAX] bugfix for softmax lowering

---

tests/pytorch/test_onnx_export.py
transformer_engine/pytorch/softmax.py
transformer_engine/pytorch/te_onnx_extensions.py

In ONNX inference with KV-Cache optimizations for GPT text generation, the causal attention mask can be square (context-phase) or rectangular (generation-phase).
This commit forces softmax to use forward_torch_softmax and to dynamically slice a pre-allocated attention mask - when exporting to ONNX.
* Introduce an environment variable (NVTE_ONNX_KVCACHE_MAX_SEQ_LEN) to set the maximum sequence length.
When exporting to ONNX and this variable is set, TE preallocates an upper triangular (k=1) matrix with a size as prescribed by the variable, and dynamically slices the mask for the required shape.
TE models can be exported to ONNX when NVTE_ONNX_KVCACHE_MAX_SEQ_LEN is not configured, but the attention masking is always square and not fit for efficient text generation.
* Work-around …

Add env. var. for efficient text-generation in inference

---

transformer_engine/jax/fp8.py

When using multi-process with 1 GPU per process, single-node and using CUDA_VISIBLE_DEVICES to force each process to see only 1 GPU, the gpu id returned by JAX isn't the right one.
This happens with jax.distributed.initialize

WAR a JAX issue

---

transformer_engine/pytorch/attention.py

HazyResearch FlashAttention supports 'causal' mask type but also support 'no mask' type. This PR relaxes the restriction on `attn_mask_type` being 'causal' in the PyTorch FlashAttention module.

Relax checks for attn_mask_type in FlashAttention

---

tests/jax/test_fused_attn.py
tests/jax/test_layer.py
transformer_engine/common/fused_attn/fused_attn_fp16_bf16_max_seqlen_512.cu
transformer_engine/common/fused_attn/fused_attn_fp8.cu
transformer_engine/jax/flax/transformer.py
transformer_engine/jax/sharding.py

This PR includes several bug fixes related to the fused and the unfused attention, and also not enabling the fused attention by default.
1. Fixed an issue where fusing the scale and softmax operations with a bias resulted in incorrect computation flow. The fix ensures that the computation flow becomes Softmax(scale * attn_weights + bias). e594bb625b40deb9a5206e3ac4431832fe187967
2. There is a bug that not clearing `S` tensor leads to incorrect answer on cuDNN kernel. WAR by clearing `S` tensor when `causal_masking` + `no_bias` and add the  relevant unit tests. ac67e914b6e3bbd6a6cdbbbdf073026a1e86e9f2
3. Enhance the handling of `None` sharding tensor. 49e73d51f2dae2aeee056c709f8efbdc39f51d73
4. Based on internal discussions, it has been decided to disable fused attention by default for JAX …

Jax bug fixes for the dot product attention

---

transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py
transformer_engine/pytorch/utils.py

Addressing issues found when debugging https://github.com/Lightning-AI/lit-llama/issues/249

Clearer error messages for dtype and shape assertions

---

setup.py

This allows TE to be tested against specific FA releases and upgrade when necessary, to avoid situations such as https://github.com/HazyResearch/flash-attention/pull/241, when changes to FA introduces bugs in TE

Pin FA version

---

transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

If `is_first_microbatch=None`, it's unnecessary to save the fp8 weight tensor for the fwd pass. 
[Although in the bwd pass, we do need the transposed weights.]

Don't save fp8 weight tensors if `is_first_microbatch` is None

---

transformer_engine/jax/flax/transformer.py

1. Adding `self.head_dim == 64` into condition set of `use_fused_attn`, since cuDNN fMHA only support `head_dim==64` at this moment.

[JAX] Enhance fall-back conditions for fMHA.

---

tests/pytorch/test_onnx_export.py
transformer_engine/pytorch/te_onnx_extensions.py

Adding support for BF16 in ONNX export
* "fake bf16" are bf16 subgraphs with fp32 I/O for testing TE vs ORT
* standard bf16 - for exporting the inputs and outputs and comparing against TRT
* added cast to bf16 before GEMM in BF16, in case input is output of DQ

ONNX export test - BF16 support

---

tests/jax/test_helper.py
transformer_engine/jax/fp8.py

- Use the same default in the function to what the class default.
- Assert instead of silently ignoring not supported variation (and small doc correction)
- No need to change those value after the context.

JAX small changes

---

transformer_engine/pytorch/attention.py
transformer_engine/pytorch/te_onnx_extensions.py

Models with BF16 precision export to ONNX successfully but fail to run through ONNX Runtime. Issues observed:
1. Output of GEMM is FP32 - The output of gemm is not type-compliant as an input to a subsequent node that expects a BF16 input. 
2. The `torch.empty` call in the forward definition of  `UnfusedDotProductAttention` sets the type of the `value` attribute of the `ConstantOfShape` node to BF16. This is not supported by ONNX Runtime.
The changes in the MR address the issues above

Fix BF16 ONNX export for successful ONNX Runtime Verification

---

transformer_engine/pytorch/attention.py
transformer_engine/pytorch/te_onnx_extensions.py

This reverts commit 914f3841cc78571ab514fab00150ea0a4f40a0ba. #271 was merged before we had fully worked out test failures.
Closes https://github.com/NVIDIA/TransformerEngine/pull/274.

Revert "Fix BF16 ONNX export for successful ONNX Runtime Verification (#271)"

---

tests/pytorch/test_onnx_export.py
transformer_engine/pytorch/softmax.py
transformer_engine/pytorch/te_onnx_extensions.py

* BF16 is validated using "fake i/o": i.e. instead of using BF16 as input/output, use FP32 input/output and convert to/from BF16 in the forward method.
* Wrap softmax symbolic functions with conversion to/from FP32 to produce the same semantics as TE's softmax (compute is performed at FP32 precision regardless of input/output data type).

Fix softmax ONNX export

---

tests/pytorch/test_onnx_export.py

Same filename is used for all activations, file is getting overridden to last activation type executed

ONNX export test - fix file name in transformer layer tests

---

transformer_engine/pytorch/te_onnx_extensions.py

ONNX has a spec bug: ConstantOfShape supports all dtypes except for BF16. To WAR we use dtype FP32 and then cast to BF16.
Will also issue a PR to the ONNX sig committee to change the spec in opset 20.

Fix layer_norm ONNX export

---

transformer_engine/common/gemm/cublaslt_gemm.cu

Fixing compute type aligning with [this table](https://docs.nvidia.com/cuda/cublas/index.html#id8).

Fix compute type for GEMM

---

transformer_engine/common/__init__.py

Allows TE discovery mechanisms to pick up the `python` interpreter (and associated `pip`, as opposed to the global `python`) running in the virtual-environment that code is being run in.

Fix TE discovery in python virtual environments

---

transformer_engine/common/CMakeLists.txt

Many users have run into build errors by forgetting `git submodule update --init`. The current error message is not so helpful:
```
/tmp/pip-req-build-12341234/transformer_engine/common/fused_attn/../util/cudnn.h:17:10: fatal error: cudnn_frontend.h: No such file or directory
17 | #include <cudnn_frontend.h>
|          ^~~~~~~~~~~~~~~~~~
```
This PR gives a better message:
```
CMake Error at common/CMakeLists.txt:46 (message):
Could not find cuDNN frontend API.  Try running 'git submodule update
--init --recursive' within the Transformer Engine source.
```

Check for cuDNN frontend API when building

---

tests/paddle/test_operators.py
transformer_engine/paddle/cpp_extensions.py
transformer_engine/paddle/csrc/common.cpp
transformer_engine/paddle/csrc/common.h
transformer_engine/paddle/csrc/custom_ops.cu

The following ops are added:
- rmsnorm_fwd, rmsnorm_bwd, rmsnorm_fwd_fp8
- scaled (upper triang) (masked) softmax  fwd+bwd
- fused_attn_fwd_qkvpacked, fused_attn_fwd_kvpacked, fused_attn_bwd_qkvpacked, fused_attn_bwd_kvpacked
(To avoid merge conflict, I create my git branch based on @Tom-Zheng 's [PR262](https://github.com/NVIDIA/TransformerEngine/pull/262).  Please merge his PR first and then this one)

Add operators for Paddle

---

tests/jax/test_helper.py
transformer_engine/jax/fp8.py

To support Paxml, we might receive fp8 meta in 3 dimension, instead of 2 (we expected before), then we create this PR to make `update_fp8_meta`  work as expected for arbitrary dimensinos of fp8 meta.

[JAX] Support arbitrary dimensinos of fp8 meta.

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

When using FSDP or any mode in which parameters are divided externally, the buffers registered are retained as duplicate memory unsharded tensors leading to significantly higher memory consumption.
+ @erhoo82

Remove buffer registration for FSDP like cases

---

transformer_engine/pytorch/attention.py

This ensures that the dtype for the inference cache is that same as that of the activations. `params_dtype` is not necessarily passed and so it defaulted to fp32.

Fix dtype for KV inference cache

---

transformer_engine/pytorch/module/base.py

For saving the FP8 checkpoint in PyTorch, TE relies on internal attributes such as `self.fp8` and `self.fp8_calibration` to figure out whether or not to keep the state as `None` or save all the relevant tensors from `fp8_meta`. This breaks for cases when the checkpointing is done without actually running forward execution because the defaults for `self.fp8` and `self.fp8_calibration` are `False`. As a result, the FP8 checkpoint is saved with incomplete states. An example and common use case for this is when writing checkpoint converters or mappers. [For more background](https://github.com/NVIDIA/NeMo/pull/6929).
The solution is to save some variable inside `fp8_meta` which can also be used as a check when saving the checkpoint.

[PyTorch] Fix FP8 checkpointing for non forward execution cases

---

.github/workflows/build.yml

Since July 7 we've experienced test failures in our GitHub-hosted PyTorch build tests ([example](https://github.com/NVIDIA/TransformerEngine/actions/runs/5487892849/jobs/10005440313)). These are out-of-memory errors that show up while building Flash Attention. [GitHub runners have 14 GB of available disk memory](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), [NGC PyTorch containers are about ~9 GB](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags), and the pip wheels of TE dependencies take about 2.5 GB (with possibly multiple copies during the build stage), so it seems we've been sitting close to the memory limit for a while. I'm not sure what pushed us over last Friday though: …

Stop creating pip wheels in GitHub build tests

---

qa/L0_unittest/test.sh
tests/pytorch/test_jit.py
transformer_engine/pytorch/jit.py
transformer_engine/pytorch/module/layernorm.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

As discussed in https://github.com/NVIDIA/TransformerEngine/issues/308, calling `torch.compile` on a Transformer Engine module fails. A full solution would probably require significant changes in both Transformer Engine and PyTorch, so until we have a demonstrated need it will be easier to just disable TorchDynamo. `torch.compile` wouldn't do anything for the Transformer Engine modules in a model, but it could still benefit other model components.
Closes #308.

Disable TorchDynamo optimizations in PyTorch modules

---

transformer_engine/pytorch/jit.py

This PR is a numerical fix to ensure that the results are bitwise identical when running TE (w/o FP8) with and without activation recompute.
- Add missing warmup for kernel with no bias.
- Fix incorrect input shape during jit warmup.

Fix numerics for activation recompute

---

tests/jax/test_sharding.py

Our JAX sharding unit tests were failing since they use `jax.experimental.maps.Mesh` instead of `jax.sharding.Mesh` (see https://github.com/google/jax/issues/13487). I confirm the test now passes on 4 A40s.

Replace deprecated sharding API in JAX test

---

transformer_engine/pytorch/attention.py

We have observed divergence in some models when this feature is turned on by default. Since it is a very specific use case, making it opt-in is reasonable.

Make QK layer scaling opt-in

---

transformer_engine/pytorch/module/layernorm_mlp.py

Incorrect usage of `raise`:
`TypeError: exceptions must derive from BaseException`

[PyTorch] Minor bug fix

---

transformer_engine/pytorch/fp8.py
transformer_engine/pytorch/module/base.py

[See comment](https://github.com/NVIDIA/TransformerEngine/issues/342#issuecomment-1661504430) for the need for this.
**Note:** This is backwards compatible with current checkpoints including all parallelism modes (DP/SP/TP/PP).

Store FP8 checkpointing data in CPU

---

tests/jax/test_custom_call_shape.py
tests/jax/test_fused_attn.py
transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu
transformer_engine/common/fused_attn/fused_attn_f16_max512_seqlen.cu
transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/csrc/extensions.cpp
transformer_engine/jax/csrc/modules.cpp
transformer_engine/jax/csrc/modules.h
transformer_engine/jax/csrc/utils.cu
transformer_engine/jax/csrc/utils.h
transformer_engine/jax/flax/transformer.py
transformer_engine/jax/fused_attn.py

This PR exposes the cuDNN arbitrary seqlen fused attention backend to JAX.
Main changes:

[JAX] flash attention integration

---

tests/pytorch/test_numerics.py
transformer_engine/pytorch/module/rmsnorm.py
transformer_engine/pytorch/te_onnx_extensions.py

In the kernel we use epsilon inside the square root, rather than outside (as in the original paper). Our behavior is consistent with the implementation in Llama and T5 in HuggingFace.

Fix for the RMSNorm tests/doc/ONNX export to match the actual implementation

---

transformer_engine/pytorch/fp8.py
transformer_engine/pytorch/module/base.py

This is a better way to solving the problem in #351 as we have since observed that the number of `.cpu()` calls during saving and loading the checkpoint results in a non-negligible overhead. Just for the state tensors, there are 18 calls per transformer layer and this is excluding `.cpu()` calls to the global fp8 buffer.

Optimize calls to .cpu() during checkpointing

---

tests/pytorch/test_numerics.py
transformer_engine/pytorch/attention.py

This PR allows users to mix cuDNN fused attention fprop kernel with flash-attn v2 bprop kernels, which provides the fastest performance for certain model configs. It only takes place when the arbitrary_seqlen backend of fused attention is called.

Add mixed use of cuDNN fprop and flash-attn v2 bprop

---

qa/L0_lint/pylintrc
tests/pytorch/test_fused_attn.py
tests/pytorch/test_onnx_export.py
tests/pytorch/test_sanity.py
transformer_engine/pytorch/distributed.py
transformer_engine/pytorch/fp8.py
transformer_engine/pytorch/module/base.py

[PyTorch] FP8 fixes

---

transformer_engine/pytorch/module/base.py

`FP8GlobalStateManager` doesn't have the `amax_and_scale_update` method. It's probably a typo

fix for amax_and_scale_update when reduce_amax=False

---

tests/pytorch/test_fused_attn.py
transformer_engine/common/transpose/transpose_fusion.cu
transformer_engine/pytorch/csrc/extensions/attention.cu

Fix rng_state issue and minor compiler warning

---

tests/jax/test_fused_attn.py
transformer_engine/common/fused_attn/fused_attn.cpp
transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/csrc/extensions.cpp
transformer_engine/jax/csrc/modules.cpp
transformer_engine/jax/csrc/modules.h
transformer_engine/jax/flax/transformer.py
transformer_engine/jax/fused_attn.py

cuDNN max 512 seqlen fused kernel only supports sm80 and sm90, and arbitrary seqlen requires 8.9.3 to support all CC >= 80.

Error handle for non-sm80/sm90 GPUs when using fused attention

---

examples/paddle/mnist/test_single_gpu_mnist.py
tests/paddle/dist_launcher.py
tests/paddle/parallel_tests/amax_reduction.py
tests/paddle/parallel_tests/group_sharding.py
tests/paddle/parallel_tests/layernorm_linear_tp.py
tests/paddle/parallel_tests/layernorm_mlp_tp.py
tests/paddle/parallel_tests/linear_pp.py
tests/paddle/parallel_tests/linear_tp.py
tests/paddle/parallel_tests/transformer_tp.py
tests/paddle/test_layers.py
tests/paddle/test_operators.py
tests/paddle/test_parallel.py
tests/paddle/utils.py
transformer_engine/paddle/constants.py
transformer_engine/paddle/distributed.py
transformer_engine/paddle/fp8.py
transformer_engine/paddle/fp8_buffer.py
transformer_engine/paddle/layer/attention.py
transformer_engine/paddle/layer/base.py
transformer_engine/paddle/layer/layernorm.py
transformer_engine/paddle/layer/layernorm_linear.py
transformer_engine/paddle/layer/layernorm_mlp.py
transformer_engine/paddle/layer/linear.py
transformer_engine/paddle/layer/transformer.py

Add the following parallel rules:
- TP
- DP
- PP
- Group sharding (FSDP)

[Paddle] Add parallel support

---

transformer_engine/common/util/cuda_runtime.h
transformer_engine/jax/csrc/modules.cpp
transformer_engine/jax/csrc/utils.cu
transformer_engine/jax/csrc/utils.h
transformer_engine/jax/sharding.py

1. When running with only FSDP, `infer_major_sharding_type` cannot correctly infer the right `MajorShardingType`, then custom calls are unble to apply `xmap` to manually shard tensors. That makes XLA to insert unexpected all-gathers for all custom calls. Therefore, submit this PR to fix.
2. Fix memory misaligned issue on LN BWD when 1 CTA handling more than 1 row.
3. Apply `sm_arch` to replace the implementation of `GetDeviceComputeCapability`.

[JAX] Fix incorrect sharding when only enable FSDP and Mem Misaligned in LN_BWD.

---

tests/paddle/parallel_tests/linear_pp.py
tests/paddle/test_layers.py
tests/paddle/utils.py
transformer_engine/paddle/distributed.py
transformer_engine/paddle/layer/attention.py
transformer_engine/paddle/layer/transformer.py

This PR allows user to control the RNG state of attention dropout and hidden dropout. Referring to [PaddleNLP](https://github.com/PaddlePaddle/PaddleNLP/blob/2aa58d83a68ccae29c2c740867e98762e608c559/paddlenlp/trainer/trainer_utils.py#L77), attention dropout uses `local_seed` and hidden dropout uses `global_seed`.

[Paddle] Add control of RNG state

---

tests/paddle/recompute_tests/recompute_transformer_encoder.py
tests/paddle/test_layers.py
tests/paddle/test_operators.py
tests/paddle/test_recompute.py
transformer_engine/paddle/__init__.py
transformer_engine/paddle/constants.py
transformer_engine/paddle/fp8.py
transformer_engine/paddle/fp8_buffer.py
transformer_engine/paddle/layer/attention.py
transformer_engine/paddle/layer/base.py
transformer_engine/paddle/layer/layernorm_linear.py
transformer_engine/paddle/layer/layernorm_mlp.py
transformer_engine/paddle/layer/linear.py
transformer_engine/paddle/layer/transformer.py
transformer_engine/paddle/recompute.py
transformer_engine/paddle/utils.py

This PR supports recompute for TE Paddle. The user can use `te.recompute` to wrap TE layers, or use `recompute_core_attention=True` in `TransformerLayer.forward` to recompute only the core attention part.

[Paddle] Support recompute

---

setup.py
transformer_engine/common/fused_attn/fused_attn.cpp
transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu
transformer_engine/common/fused_attn/fused_attn_f16_max512_seqlen.cu
transformer_engine/common/fused_attn/fused_attn_fp8.cu
transformer_engine/common/fused_attn/utils.h
transformer_engine/pytorch/attention.py
transformer_engine/pytorch/csrc/extensions/attention.cu

This PR:
- adds workspace optimizations for fused attention arbitrary_seqlen backend in cuDNN 8.9.5+
- changes the default of `NVTE_FUSED_ATTN_USE_FAv2_BWD` to 0 as this is the majority of the use cases
- moves zero fill algorithms to FP8 only (other backends do not need zero initialization)

[C/PyTorch] Add workspace optimization for fused attention arbitrary_seqlen backend

---

transformer_engine/pytorch/fp8.py

When setting `NVTE_DP_AMAX_REDUCE_INTERVAL` to 0, performance FP8 AMAX reduction only in TP domain.

Add an option for TP-only AMAX reduction

---

tests/paddle/test_operators.py
transformer_engine/paddle/csrc/custom_ops.cu
transformer_engine/paddle/fp8.py
transformer_engine/paddle/fp8_buffer.py

Paddle dynamic graph inserted a few bubbles when using assign operators/slice operators.
This PR moves `amax_and_scale_update` and `copy_amax_from_buffer` to custom_ops in c level to eliminate those tiny kernels and bubbles.
- `copy_amax_from_buffer`: There was a slice kernel for accessing `amax_history[0]` and multiple kernels for `=` operator. By using the customized `copy_amax_from_buffer` op, all of above kernels can be reduced as a single memcpy. The spent time reduced from 18us to 1.8us.
- `amax_and_scale_update`: There were multiple tiny kernels for updating amax/scale/scale_inv/history. This PR fused a few assign/elementwise operators to a single kernel to reduce the total 13 kernels to 4 kernels. The spent time reduced from ~39us to ~15us.

[Paddle] Eliminate amax update bubbles by using custom_ops

---

setup.py

Running `import flash_attn` with FAv 2.0.7 onwards A100 gives the following error:
```
ImportError: /usr/local/lib/python3.8/dist-packages/flash_attn_2_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceE
```
A bisect of the versions shows that [this](https://github.com/Dao-AILab/flash-attention/commit/f8dccfc90a115ce797fed7d5eaf8b066f2753d34) is the offending commit and that there is an issue with the uploaded wheels for FA.

Keep previous FA version

---

transformer_engine/jax/cpp_extensions.py

The change didn't lend in JAX yet, but it should be there soon.
So we are better to prepare before it lend to not break the nightly.

Make an import optional for a JAX API change that will happen soon.

---

tests/tensorflow/test_layers.py

We've been seeing test failures since https://github.com/NVIDIA/TransformerEngine/pull/427 changed the calculation of scaling factors but it missed the TensorFlow test.
Closed by https://github.com/NVIDIA/TransformerEngine/pull/397 since I've also included this fix there.

Update reference scale calculation in TensorFlow test

---

.github/workflows/build.yml
.github/workflows/lint.yml

We have been experiencing spurious test failures in some of our GitHub CI tests (namely "Build / PyTorch" and "Lint / PyTorch Python"). The [GitHub runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) have 7 GB RAM and 14 GB SSD available, but the NGC PyTorch containers have been growing in size:
| Container version | Compressed size | Uncompressed size |
|----|----|----|
| 22.09 | 7.67 GB | 16.8 GB |
| 23.03 | 9.13 GB | 20.4 GB
| 23.09 | 9.85 GB | 22 GB |
The fix is to disable the tests using the PyTorch container and rely on our internal CI.

Disable GitHub CI jobs using NGC PyTorch container

---

tests/pytorch/test_fused_attn.py
transformer_engine/pytorch/csrc/common.h
transformer_engine/pytorch/csrc/extensions.h
transformer_engine/pytorch/csrc/extensions/misc.cu
transformer_engine/pytorch/csrc/extensions/pybind.cpp

The CUDNN_VERSION env variable is specific to the NGC containers. This PR adds the API for the pyTorch extension to check the cuDNN version that is available (based on the loaded libcudnn*.so library).

Better way of checking cuDNN version

---

transformer_engine/pytorch/module/layernorm_linear.py

We've encountered a runtime error in LayerNormLinear when training LLaMa since RMSNorm is outputting to a buffer with an invalid dtype. In particular, we are not properly handling the case where the RMSNorm output is returned in bf16.
Note that LayerNormMLP handles this correctly:
https://github.com/NVIDIA/TransformerEngine/blob/f456ba19d97e2ce3a4906f631631d0d63e13040a/transformer_engine/pytorch/module/layernorm_mlp.py#L146

Fix incorrect dtype in LayerNormLinear

---

transformer_engine/jax/cpp_extensions.py

Use `jax.dtypes.canonicalize_dtype` to wrap the dtype may from the users to ensure both `jnp.bfloat16` and `'bfloat16'` work.

[JAX] Canonicalize the dtype for the better user experience

---

transformer_engine/jax/fused_attn.py

`extend_fsdp_sharding_meta()` was updated in 6464ced to return a tuple of both the sharding meta and the FSDP axis name.
`self_fused_attn()` was updated to accommodate this API change, but `cross_fused_attn()` was not.
This PR applies the same fix from `self_fused_attn()` to `cross_fused_attn()`.
Bug reported by @terrykong.

Incorrect use of extend_fsdp_sharding_meta() in cross_fused_attn()

---

transformer_engine/CMakeLists.txt
transformer_engine/common/CMakeLists.txt

I encountered some issues while trying to integrate TransformerEngine as a subproject. These are the fixes.
* Replace `CMAKE_SOURCE_DIR` with `CMAKE_CURRENT_SOURCE_DIR`.
* Use `set( )` instead of `list(APPEND )`, as the latter resulted in command line like `...;-threads 4` in our build.

Fix CMakeList.txt to build as a sub-project

---

tests/jax/distributed_configs_helper.py
tests/jax/distributed_ops_helper.py
tests/jax/test_distributed_custom_ops.py

Distributed ops tests now correctly use the `@pytest.skip()` condition instead of prematurely throwing an error when `DistributedConfigsHelper()` checks number of GPUs.
Also renamed helper classes for descriptive consistency.

[JAX] Bugfix for insufficient GPUs crash in distributed ops

---

tests/pytorch/test_fused_attn.py

As discussed in https://github.com/NVIDIA/TransformerEngine/pull/503, the Transformer layer tests involve excessively large hidden sizes, which makes it hard to have tight numerical tolerances. This is a quick hack to disable the offending tests and @cyanguwa will remove it in an upcoming PR. She will refactor the attention tests so each test has its own set of test cases, e.g. dot product attention will be tested with many configurations to test the numerics of the cuDNN kernels while the Transformer layer tests will only have a few small configurations to validate the Python infrastructure.
See https://github.com/NVIDIA/TransformerEngine/pull/503 and https://github.com/cyanguwa/TransformerEngine/blob/fused_attn/graph_api_v1/tests/pytorch/test_fused_attn.py.

[PyTorch] Disable large test cases for Transformer layer

---

examples/jax/mnist/test_single_gpu_mnist.py
tests/jax/test_custom_call_compute.py
tests/jax/utils.py

We have had recent CI failures in `tests/jax/test_custom_call_compute.py::TestFP8Dot::test_grad_fp8_randint` when running on an L40 (e.g. [this recent build for #471](https://github.com/NVIDIA/TransformerEngine/actions/runs/6724992709/job/18278451411)). This is because this test requires bit-wise correct results. The GEMM kernel that executes on L40 can't achieve this level of accuracy, although it still within the expected numerical error for FP8.
This PR adds logic so that we can use dtype-specific tolerances within the `assert_allclose` helper function. Right now we only use it in JAX FP8 tests, but it could be applied to other tests. We can also consider porting this functionality to other framework tests.

[JAX] Use FP8 tolerances in FP8 tests

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

For the M-LM usage of TE API's, custom layer Backward implementations return the accumulated gradient which is of weight.main_grad dtype. This makes Torch insert an unwanted at::to kernel, this is unwanted as wgrad is unused and is already added to the main grad by the TE API. To remove this redundancy, we return an empty tensor of the shape of weight.main_grad shape and weight.dtype. The empty tensor is later freed in the M-LM code.
Have edited layernorm_linear.py, linear.py and layernorm_mlp.py

Returning an empty tensor of param dtype for wgrad

---

transformer_engine/common/utils.cuh

Make code more readable
Partially fixes: https://github.com/NVIDIA/TransformerEngine/issues/422

feat(code quality): Add comments for parallel welford variance calculation

---

transformer_engine/pytorch/attention.py

This PR disables the use of FAv2.1+ for causal mask and cross attention due to the change of behavior in FA: https://github.com/Dao-AILab/flash-attention#21-change-behavior-of-causal-flag

Disable FAv2.1+ for causal mask in cross attention

---

qa/L0_jax_distributed_unittest/test.sh
qa/L0_jax_unittest/test.sh
transformer_engine/jax/fused_attn.py

The current qa scripts run `tests/jax/test_distributed_custom_ops.py` but there is no this file. This PR fixes this issue and also remove an assertion of `NO_MASK`.

[JAX] Fix JAX distributed unit tests

---

transformer_engine/common/common.h

@zlsh80826 has observed that our dtype instantiation macro instantiates `DType::kByte` as `float`, resulting in 4x excessive memory allocations for workspace buffers. This replaces that with `unsigned char`.

Use unsigned char when instantiating DType::kByte

---

transformer_engine/pytorch/attention.py

Getting warnings of the following form using ToT TE:
```
/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/attention.py:852: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
data_ptr = grad_outputs[0].storage().data_ptr()
```

Use non-deprecated PyTorch methods to silence warnings

---

transformer_engine/pytorch/distributed.py
transformer_engine/pytorch/module/linear.py
transformer_engine/pytorch/utils.py

This PR adresses the issue described in #530 by using `gather_along_first_dim` instead of `gather_along_last_dim` as in other places (eg `LayerNormLinear`). The reasoning is that I did not come up with an elegant solution for a correct `gather_along_last_dim` that does not use additional transposes or explicit calls to `torch.cat` which make interleaving with the dgrad computation difficult. But I would be happy to hear other ideas or suggestions.
All in all, the code might be easier if the transpose of the input tensor is always done in the backward pass. Right now the case fp8 and sequence_parallel=False still used the fused cast in the forward pass. Happy to hear your opinion on that as well. Furthermore `gather_along_last_dim` probably should be removed now.
One further question: Is …

[PyTorch] Linear: fix computation for wgrad if sequence_parallel=True

---

tests/jax/test_distributed_fused_attn.py
tests/jax/test_fused_attn.py
transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/csrc/modules.cpp
transformer_engine/jax/flax/transformer.py
transformer_engine/jax/fused_attn.py

This PR does
- Prepare the arbitrary attention backend I/O (requires forward output in the backward)
- Add bias support for the JAX bridge code

[JAX] Prepare cross flash attention

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

Fix a bug: when perform fp8_calibration, it should be abs_max rather than `torch.amax`. `torch.amax` is not a(bs)max.

fix amax -> abs max in fp8_calibration

---

transformer_engine/jax/flax/module.py
transformer_engine/jax/flax/transformer.py
transformer_engine/jax/fused_attn.py

Add `checkpoint_name` for TE's tensors. That enables the support for different [checkpoint_policy](https://github.com/google/praxis/blob/main/praxis/layers/checkpoint_policy.py) in PAXML.

[JAX] Add checkpoint_name for the recompute granularity control

---

transformer_engine/pytorch/transformer.py

In the transformer layer the inter-attention is initialized with `attn_mask_type="padding"` (see https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/transformer.py#L367). This is overriden in the forward call with `self_attn_mask_type`, which is typically causal. This seems wrong to us. In fact this means that in a encoder-decoder architecture, the decoder would look with a causal mask on the encoder.
I would propose to remove the override in the forward pass. This is a clean and simple solution, but it might destroy existing models. Do you have other suggestions?
Looking forward to get this fixed ;-)

[PyTorch] fix attn_mask_type for inter_attention

---

transformer_engine/common/fused_attn/fused_attn.cpp
transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu
transformer_engine/common/util/logging.h
transformer_engine/pytorch/__init__.py

This PR fixes the compiling warnings in SDPA flash after upgrading to cuDNN frontend v1. It also fixes the logic for selecting the SDPA flash backend on sm80 when cuDNN runtime version is >8.9.6.

[PyTorch/C] Fix compiling warnings and backend selection logic for fused attention

---

transformer_engine/jax/cpp_extensions.py

Latest JAX changes for lowering caused our custom op tests to fail due to a device dispatch bug. This PR implements the fix needed to make our primitives work correctly with the latest JAX changes.

[JAX] Fixing custom op test failures due to changes in JAX lowering internals

---

transformer_engine/pytorch/csrc/userbuffers/userbuffers.cu

Avoid redeclaration of "nv_bfloat16" when Compiling in CUDA12.1
`#define half nv_bfloat16` will redeclared `nv_bfloa16` in the file included by `#include<cuda_fp8.h>`. Putting `#include <cuda_fp8.h>` in front of `define half nv_bfloat16` can avoid this problem.
Error log: `/usr/local/cuda/include/cuda_fp16.hpp(2724): error: invalid redeclaration of type name "nv_bfloat16" (declared at line 2837 of /usr/local/cuda/include/cuda_bf16.hpp)`

Fix bug when compiling in CUDA12.1

---

tests/pytorch/test_jit.py
transformer_engine/pytorch/attention.py
transformer_engine/pytorch/jit.py
transformer_engine/pytorch/module/layernorm.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py
transformer_engine/pytorch/module/rmsnorm.py

Changes:
- Changed the `no_torch_dynamo` to a factory of decorators in order to accept the `recursive` argument. This is needed since some of the FusedAttention-specific types exist in the `DotPRoductAttention` forward and we don't want to disable torch.dynamo for the unfused attention case.
- Disabled dynamo for `FusedAttention` and the top level function of the `DotProductAttention`

Disable dynamo for Fused Attention

---

transformer_engine/pytorch/float8_tensor.py

While debugging a convergence issue with LLaMa SFT and https://github.com/NVIDIA/NeMo/pull/7909, I've identified a subtle bug when a model with FP8 params loads a checkpoint. When the model is first initialized, it generates random weights and stores the amax value in `fp8_meta`. However, this amax becomes meaningless when we load the checkpoint and overwrite the weight values. The amax histories are used in the forward pass to update the scaling factors, resulting in bogus scaling factors that clip many FP8 values to the maxval or underflow them to zero.
This PR changes the behavior of copying into a `Float8Tensor` so that it updates the latest amax history if it has an `fp8_meta`. This is similar to how the FP8 cast kernel updates the latest amax history. This should fix the issue I'm …

Update fp8_meta amax when copying into Float8Tensor

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/linear.py

Linear and LayerNormLinear initialization leaves behind unused copies of the weight and bias tensors when there is no parameter split. This PR removes these buffers at the end of the initialization.

[PyTorch] Linear and LayerNormLinear bug fix for excess weight and bias buffers

---

README.rst

We at EleutherAI are going to integrate the TransformerEngine into our GPT-NeoX library, and wanted to go ahead and indicate this in the README.
Look forward to completing full support within the next month!
(picked up from https://github.com/NVIDIA/TransformerEngine/pull/573 instead of continuing to wrestle with DCO and commit histories)

Add GPT-NeoX "coming soon" to README

---

transformer_engine/pytorch/attention.py

PR #499 introduces `ub_name` parameter, which is not optional when using UB, but did not update MHA to actually pass it. This PR fixes that.

Fix UB names in MHA

---

tests/pytorch/test_fused_attn.py
transformer_engine/common/fused_attn/fused_attn_fp8.cu

This PR fixes the order of the input parameters in FP8 fused attention.

[Common/PyTorch] Fix FP8 fused attention input args

---

transformer_engine/pytorch/attention.py
transformer_engine/pytorch/module/_common.py
transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/linear.py

https://github.com/NVIDIA/TransformerEngine/issues/533 reports that `TransformerLayer` doesn't work out-of-the-box with tensor parallelism. The root cause is because the logic for parameter splitting (e.g. for QKV matrices) does not handle tensor parallelism. We've also had another user run into trouble when trying to set `parameters_split` in `Linear` because it currently expects the split names to have exactly one underscore at the end (so `mysplit` and `my_split_` would both fail).
I think this is a good opportunity to refactor this logic:
- Adjust parameter split size as needed for tensor parallelism
- Generalize support for split names. To maintain backward compatibility, we now strip all trailing underscores before appending `_weight` or `_bias`, resulting in parameter names like …

[PyTorch] Refactor parameter splitting in Linear and LayerNormLinear

---

transformer_engine/pytorch/distributed.py

This PR would support automatically checkpoint a model with non-tensors as its modules' inputs/outputs using PyTorch's apply_activation_checkpointing function together with te's checkpoint function.
Currently, te CheckpointFunction.forward/backward implementation assumes input args and outputs are nn.Tensors. 
This restriction only works when users incorporate te fp8/checkpoint in model definition. 
If users want to automatic convert a pytorch model to use te fp8 with checkpoint, this restriction may fail the checkpoint function. For example, when training with Huggingface's llama model , and checkpointing [LlamaDecoderLayer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L764), which has inputs containing non-tensors, …

[PyTorch] Support non-tensor inputs/outputs for te CheckpointFunction

---

tests/jax/test_custom_call_compute.py
transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/dot.py
transformer_engine/jax/flax/module.py
transformer_engine/jax/layernorm.py
transformer_engine/jax/mlp.py

- Add a custom call, `cast`.
- Replace `cast_and_transpose` with `cast` to the kernel of `layernorm_fp8_dot` and the kernel_1 of `layernrom_geglu_fp8_mlp` to allow XLA handle `transpose` for avoiding unnecessary `copy` to break FP8 GEMM pattern matching.
- Replace `cast_and_transpose` with native XLA cast to the x and kernel of `fp8_dot` and the kernel_2 of `layernrom_geglu_fp8_mlp` to allow XLA handle `transpose` for avoiding unnecessary `copy` to break FP8 GEMM pattern matching.
- Fix a bug of enabling `layernrom_geglu_fp8_mlp` in `flax.LayernormMLP`.

[JAX] Fix failure on pattern matching of FP8 GEMM when enabling FSDP.

---

tests/paddle/parallel_tests/linear_pp.py
tests/paddle/test_layers.py
tests/paddle/test_operators.py
transformer_engine/paddle/cpp_extensions.py
transformer_engine/paddle/csrc/custom_ops.cu
transformer_engine/paddle/fp8.py
transformer_engine/paddle/layer/attention.py
transformer_engine/paddle/layer/base.py
transformer_engine/paddle/layer/layernorm_linear.py
transformer_engine/paddle/layer/layernorm_mlp.py
transformer_engine/paddle/layer/linear.py
transformer_engine/paddle/layer/transformer.py
transformer_engine/paddle/utils.py

Note: Merge #561 before this one.
This PR adds the following optimization:
- Actively delete tensor to free memory in FP8 linear backward
- Support FP8 weight caching in pipeline parallel

[Paddle] Optimize memory usage when training in pipeline parallel

---

qa/L0_jax_distributed_unittest/test.sh
qa/L0_jax_unittest/test.sh
tests/jax/test_fused_attn.py
tests/jax/test_layer.py
tests/jax/test_praxis_layers.py
tests/jax/utils.py
transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu
transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/csrc/modules.cpp
transformer_engine/jax/csrc/modules.h
transformer_engine/jax/flax/transformer.py
transformer_engine/jax/fused_attn.py
transformer_engine/jax/praxis/transformer.py

- Support GQA/MQA (`num_gqa_groups`) for both fused attention and unfused attention implementation.
- Fix the `kv_stride` of the flash attention
- Refactor fused attention test and add GQA tests
- Calculate the seqlen before the primitive for the better perf (avoid to recompute it again in bwd)

[JAX][Common] Support GQA

---

examples/pytorch/fsdp/README.md
examples/pytorch/fsdp/fsdp.py
transformer_engine/pytorch/module/_common.py
transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/module/layernorm.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py
transformer_engine/pytorch/module/rmsnorm.py
transformer_engine/pytorch/utils.py

This is primarily meant to support training very large models in `torch.distributed.fsdp.FullyShardedDataParallel` mode. 
FSDP execution flow requires models to be initialized in serial mode before being passed into an FSDP wrapper that shards their parameters. Without `device='meta'` support, this materializes a copy of every module in memory for every host/device and causes OOM errors for large models. Deferring initialization with `device='meta'` materializes the memory only when the FSDP wrapper recursively executes `module.reset_parameters()` on already sharded modules, thus avoiding unsharded duplicates.
~~Databricks has requested us to accelerate upstreaming this feature for `te.Linear` in support of their immediate work instead of waiting to upstream it until the same feature is …

[PyTorch] Deferred Initialization via `device='meta'` option

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

Hello team,
in our regression tests we noticed that after #596 not all biases are initialized to zero. This affects both layer norm biases as well as linear biases. Before #596, the biases were explicitly initialized to zero, as shown [here](https://github.com/NVIDIA/TransformerEngine/blob/bb759adc2a53c57cc387f531c580a16149e3d4ac/transformer_engine/pytorch/module/linear.py#L693) for example.
I crafted a small fix. Could you please double check that I got all the occurances?
We would really appreciate if this could be fixed soon.

[PyTorch] Fix bias initialization introduced in #596

---

setup.py
transformer_engine/CMakeLists.txt

Two changes:
- libpython is only required for embedded python, not for python extensions.
- tell cmake explicitly to use the current interpreter (and includes)
See related issues:
- https://gitlab.kitware.com/cmake/cmake/-/issues/20425
- https://github.com/pypa/manylinux/issues/484

Support building using the manylinux docker image.

---

tests/pytorch/fused_attn/test_fused_attn.py
tests/pytorch/test_numerics.py
tests/pytorch/test_sanity.py
transformer_engine/pytorch/utils.py

[A recent PyTorch API change for `torch.cuda.is_bf16_compatible()`](https://github.com/pytorch/pytorch/commit/fc5fda14bcc41008e5610bf39c53eb066933ea4e) makes the check intentionally more permissive to support `torch.bfloat16` Tensors on some older GPUs. This has caused CI failures for us on V100 and TU102 nodes because TorchInductor supports `torch.bfloat16` only for sm_80 or higher.
This PR replaces `torch.cuda.is_bf16_compatible()` checks with explicit checks on `torch.cuda.get_device_capability()[0] >= 8` to comply with TorchInductor limitations.

[PyTorch] Workaround for incorrect output from torch.cuda.is_bf16_compatible() on V100s and TU102s

---

transformer_engine/pytorch/attention.py

In `MultiHeadAttention`, the `attention_type` is not properly forwarded to `DotProductionAttention`.

[PyTorch] forward attention_type in MultiHeadAttention

---

transformer_engine/pytorch/attention.py

This is a temporary workaround just for release 1.3 for the issue introduced in #497 (the actual fix getting into main is #630). The issue is that the code currently assumes that it is possible to use the layer_number (specifically layer_number being equal to 1) to cache the cu_seqlens needed for fused attention. There are a few problems with this assumption (e.g. it does not check that the seqlen did not actually change from the usage in the first layer), but in the case of pipeline parallelism it breaks completely inside NeMo, since there the layers are numbered globally and so some ranks never set layer_number == 1 to any layer.
In this commit I did not remove the global variables used for caching in order to minimize the changes introduced.

Fix pipeline parallelism with FusedAttn

---

transformer_engine/pytorch/attention.py

Fixes the docstring for the `MultiheadAttention.__init__`. It currently states that the default value for `input_layernorm` is `True`, but it should be `False`.

[PyTorch] Fix MultiheadAttention docstring

---

.gitignore
tests/jax/test_custom_call_compute.py
transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu
transformer_engine/common/fused_attn/fused_attn_f16_max512_seqlen.cu
transformer_engine/common/fused_attn/fused_attn_fp8.cu
transformer_engine/common/layer_norm/ln_api.cpp
transformer_engine/common/rmsnorm/rmsnorm_api.cpp
transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/csrc/extensions.cpp
transformer_engine/jax/csrc/modules.cpp
transformer_engine/jax/csrc/modules.h
transformer_engine/jax/csrc/utils.h
transformer_engine/jax/flax/module.py
transformer_engine/jax/mlp.py

Previously, custom ops allocated their workspace tensors via `WorkspaceManager` in `jax/csrc/utils.h`, which relied on direct `cudaMalloc()`.
This PR removes the `WorkspaceManager` and exposes new Python interfaces to determine workspaces sizes in the custom-op primitives in order to request the same workspace memory allocation from XLA.

[JAX] Custom Op Workspace Tensors from XLA Buffers

---

transformer_engine/pytorch/attention.py
transformer_engine/pytorch/cpu_offload.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

PR does the following:
1) Offloading was breaking for the latest PyTorch versions because torch.compile tried to save some stray tensors which shouldn't be considered for offloading. Added that filter and fixed the issue.
2) Flash Attention and Fused attention can have it's input activations offloaded which wasn't supported before. Added support for that.
3) Native FP8 doesn't use transposed FP8 weights in a cache. Added None guards so that this doesn't break.

Fixed offloading for PyT version/ Added Attention activation offloading support/ Native FP8 support

---

qa/L0_paddle_lint/test.sh
tests/paddle/dist_launcher.py
transformer_engine/paddle/layer/base.py
transformer_engine/paddle/profile.py

Paddle 2.6.0 renamed `paddle.fluid` to `paddle.base` (see https://github.com/PaddlePaddle/Paddle/pull/56576).

[Paddle] Replace paddle.fluid imports with paddle.base

---

README.rst

Updated link and removed coming soon.
We launched integration with TE in SMP v2.0.0 released late December. We currently support this for HF Llama, HF GPTNeoX out of the box with our transform API, and are expanding support.

Update readme about integration with Sagemaker model parallel library

---

qa/L0_jax_distributed_unittest/test.sh
qa/L0_jax_unittest/test.sh
transformer_engine/jax/flax/transformer.py

In the previous GQA PR (https://github.com/NVIDIA/TransformerEngine/pull/578), we added the GQA support for the native JAX attention implementation. However, the new impl results the performance regression. This PR seperates the GQA and MQA to two different implementations so that both of them can keep the best performance.

[JAX] Fix unfused GQA performance

---

transformer_engine/common/fused_attn/utils.h
transformer_engine/pytorch/attention.py

This fixes the SDPA bwd NaN problem when running with cuDNN v9.0.0.306. The problem wasn't with cuDNN but with cuDNN Frontend. Its 1.0.3 fixes the issue.

Update cudnn-frontend to 1.0.3 to fix cuDNN v9 SDPA NaNs

---

transformer_engine/pytorch/__init__.py
transformer_engine/pytorch/cpp_extensions/cast.py
transformer_engine/pytorch/csrc/extensions/cast.cu
transformer_engine/pytorch/csrc/ts_fp8_op.cpp
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py
transformer_engine/pytorch/te_onnx_extensions.py

- Change fp8 cast to be inplace so that its reflected in original fp8 tensor, not Float8 copy
- Change so that fp8 and fp8_t cast occurs in the forward-forward pass when doing recomputation

Recomputation fixes with native fp8

---

tests/cpp/operator/test_rmsnorm.cu
tests/pytorch/test_numerics.py
tests/pytorch/test_onnx_export.py
tests/pytorch/test_sanity.py
transformer_engine/common/include/transformer_engine/rmsnorm.h
transformer_engine/common/rmsnorm/rmsnorm_api.cpp
transformer_engine/common/rmsnorm/rmsnorm_bwd_kernels.cuh
transformer_engine/common/rmsnorm/rmsnorm_fwd_kernels.cuh
transformer_engine/pytorch/csrc/extensions/normalization.cu
transformer_engine/pytorch/module/rmsnorm.py

Fixes #577.
Changes:
- [common] Change the kernel to support zero_centered_gamma option
- [pyTorch] Removed restrictions around zero_centered_gamma usage
- [pyTorch] Added tests (also added test for LayerNorm as for some reason there wasn't one in test_numerics.py) and tightened tolerances

[common][pyTorch]Add zero_centered_gamma option to RMSNorm

---

transformer_engine/pytorch/attention.py

To avoid redundantly calculating cumulative sequence lengths for attention, we only compute when `layer_number == 1` and otherwise use a cached value. However, pipeline parallelism breaks this optimization since most ranks will never have a layer with `layer_number == 1`. This PR removes the caching logic's dependency on `layer_number`, which unfortunately reintroduces redundant calculation except in cases where the sequence lengths are fixed.
This is a quick bugfix, but discussion is welcomed on how best to avoid the redundant calculation. Maybe we could split `layer_number` into two things: the local layer number and the scaling factor used at: https://github.com/NVIDIA/TransformerEngine/blob/6c1a8bb5dffbce386380f8e5a12c45f7032d9b76/transformer_engine/pytorch/attention.py#L1318

[PyTorch] Refactor caching of cumulative sequence lengths

---

docs/examples/quickstart_utils.py

```
File "docs/examples/quickstart_utils.py", line 209, in cast_to_representable
input_type = texcpp.TE_DType[inp.dtype]
^^^^^^^^^^^^^^^
AttributeError: module 'transformer_engine.pytorch.cpp_extensions' has no attribute 'TE_DType'
```
But `TE_DType` was moved to `transformer_engine.pytorch.constants`. Updated the path.
@jahatef -- FYI

Update example to use new TE_DType path

---

tests/pytorch/test_float8tensor.py
transformer_engine/pytorch/float8_tensor.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

The NeMo distributed optimizer manually fills the `Float8Tensor` transpose cache at some arbitrary point in the first microbatch:
https://github.com/NVIDIA/NeMo/blob/b100cd1f7c00ba266134b60c98ee7fb8821be5df/nemo/core/optim/distributed_adam.py#L442
This doesn't have much benefit for now, but it does open the door for some future optimizations (improving load balancing with pipeline parallelism, allowing for multi-tensor kernels). However, passing `is_first_microbatch=True` in the backward pass will cause the `Float8Tensor` to recompute the transpose:
https://github.com/NVIDIA/TransformerEngine/blob/a95006170cf36712dcfb4cb27e32431e73125a2c/transformer_engine/pytorch/module/linear.py#L350
~The solution is a `_lazy_transpose_cache` attribute in `Float8Tensor`. If `True`, then calling …

[PyTorch] Add Float8Tensor option to avoid updating transpose cache when possible

---

tests/jax/test_layer.py
tests/jax/test_praxis_layers.py
tests/jax/utils.py
transformer_engine/jax/flax/transformer.py
transformer_engine/jax/praxis/transformer.py

1. Support various pairing approaches of coordinates in RoPE. `alternate` is to pair index `i` with `i + d/2`
, `d` is the hidden dimension. 'consecutive' pairs index `i` with `i + 1`.

[JAX] Support various implementations of RoPE.

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py

Fixes shape mismatch problem during backward with frozen weights (e.g., fine-tuning benchmarks) when TP overlap and UB bulk wgrad is enabled.

Disable UB bulk wgrad when weights are frozen

---

transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/fused_attn.py

Fix types for forward attention for JAX.
Bias and seed can both be None, type checking is failed otherwise.

Fix types for forward attention for JAX.

---

transformer_engine/common/fused_attn/fused_attn_fp8.cu

As discussed in https://github.com/NVIDIA/TransformerEngine/issues/694, we see some compilation errors when building with the latest version of the cuDNN front-end. In particular, `cudnn_frontend::throw_if` was deprecated in the [1.1.0 release](https://github.com/NVIDIA/cudnn-frontend/pull/60). These checks seem more TE-related than cuDNN-related, so I think it's better to replace it with TE's exception logic. While I don't see a reason to bump the pinned version right now, the bugfix is backward-compatible and might save us some effort in the future.

[Common] Fix build errors with recent cuDNN frontend versions

---

tests/jax/distributed_test_base.py
tests/jax/test_distributed_layernorm.py
transformer_engine/jax/cpp_extensions.py

Sharding affine transformation weights in TE is currently unsupported. This PR forces replication of gamma/beta in the case of LayerNorm and gamma in the case of RMSNorm even if they are sharded as inputs.

Ln force no weight sharding

---

transformer_engine/pytorch/attention.py

The original implementation would result in 'nan' when the value of lse.exp() exceeds the range of double, causing incorrect values and gradients at the corresponding positions.

[Pytorch] Update context parallel softmax lse correction func

---

tests/jax/test_distributed_fused_attn.py
tests/jax/test_fused_attn.py
tests/jax/test_layer.py
tests/jax/test_praxis_layers.py
transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/csrc/extensions.cpp
transformer_engine/jax/csrc/modules.cpp
transformer_engine/jax/csrc/modules.h
transformer_engine/jax/flax/transformer.py
transformer_engine/jax/fused_attn.py

This PR does a few refactorings on JAX fused attention
- The prefixes `self`/`cross` have been renamed to `_qkvpacked`/`_kvpacked` to more accurately reflect their meanings.
- The three separate custom calls for _qkvpacked, _kvpacked, and separate have been consolidated into a single custom call. This simplification is intended to ease the future development works.
- Add `no_mask` and `padding_causal` for mask generalization. 
- For mask with `padding`(i.e. `padding_causal`, `padding`), users are required to supply a runtime mask indicating the positions of padding.
- For mask without `padding` (i.e. `no_mask`, `causal_mask`), TE will generate masks automatically and can reduce the time needed to calculate padding offsets, thereby improving performance.
- The documentation has been …

[JAX] Refactor fused attention

---

transformer_engine/pytorch/cpp_extensions/gemm.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py

I've run into a case where a `LayerNormLinear` configured with column tensor-parallelism, sequence parallelism, and FP8 compute produces NaNs. `LayerNormLinear` exposes an option to return the layernorm output in BF16, so we are computing layernorm in BF16, performing an all-gather, casting to FP8, and computing GEMM in FP8. However, we are casting the wrong tensor to FP8 (layernorm output) and are actually passing a BF16 tensor (all-gather output) into the FP8 GEMM. This is a minimal bugfix PR and I've attempted not to change behavior with Userbuffers.

[PyTorch] Fix bug in FP8 cast in LayerNormLinear/LayerNormMLP

---

transformer_engine/pytorch/distributed.py

Makes the new API backward compatible with previous version. In addition, the `requires_grad` field is checked by PyTorch during the backward call. Checking this in the forward requires user intervention as they need to call vanilla forward during eval steps.

[PyTorch] Fix backward compatibility with checkpoint API

---

transformer_engine/pytorch/distributed.py

[PyTorch] Fix backward compatibility for checkpoint API

---

examples/jax/encoder/test_multiprocessing_encoder.py
tests/jax/test_custom_call_compute.py
tests/jax/utils.py

1. custom primitives requires the same shape for fwd input and bwd corresponding gradients. We used shape = [1] for dummy inputs in the past. This PR changed the input shape to be match as the bwd return output.
2. Latest JAX changed their layernorm fusion kernel, so the original ref code computed the `scale * y + bias` in bfloat16 which leads higher difference with TE's layernorm after 03-14 image. This PR makes the reference code computes `scale * y + bias` in higher precision and then cast back to the bfloat16, which aligns [TE's implementations](https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/common/layer_norm/ln_fwd_kernels.cuh#L120-L125) (fp32 register computation and cast to F16 before saving to global memory).
3. WAR `jax.distributed.init` issue by not …

[JAX] Adapt latest JAX/PAX image

---

setup.py

Fix https://github.com/NVIDIA/TransformerEngine/issues/756. The issue happens because we recently included `common/util/system.h` into PyTorch source CPP files at https://github.com/NVIDIA/TransformerEngine/pull/713/files to utilize the `transformer_engine::getenv` method. As a result, the PyTorch `transformer_engine_extensions` will now search for symbols within the `libtransformer_engine.so` library.
However, if the user builds TransformerEngine in a local environment (conda or PyPI), because the pre-built PyTorch, either from conda or PyPI, has the CXX11_ABI set as False, whereas the common library is using the new CXX11_ABI. As a result, there will be an undefined symbol problem when importing `transformer_engine_extensions`. NGC PyTorch container is using `CXX11_ABI=1`, so there is …

Fix undefined symbol issue for transformer_engine::getenv

---

tests/pytorch/test_onnx_export.py
transformer_engine/paddle/layer/layernorm_linear.py
transformer_engine/paddle/layer/layernorm_mlp.py
transformer_engine/pytorch/cpp_extensions/normalization.py
transformer_engine/pytorch/csrc/extensions.h
transformer_engine/pytorch/csrc/extensions/normalization.cu
transformer_engine/pytorch/csrc/ts_fp8_op.cpp
transformer_engine/pytorch/module/_common.py
transformer_engine/pytorch/module/layernorm.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/rmsnorm.py
transformer_engine/pytorch/te_onnx_extensions.py

Add SM margin to LayerNorm in inference to enable the overlap of parameter AllGather with the validation step

Add SM margin to LayerNorm in inference

---

transformer_engine/pytorch/fp8.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

Introduced in #575;  using `torch.autograd.graph.register_multi_grad_hook` is the suspected reason for hangs in certain workloads. This PR uses a different design to achieve the reduction of amaxes for gradient tensors by directly calling it from the backward pass of the modules if needed.

[PyTorch] Don't use autograd hook for bwd reduction

---

transformer_engine/pytorch/float8_tensor.py

https://pytorch.org/docs/stable/notes/extending.html

[PyTorch] Use __torch_function__ as a class method

---

transformer_engine/pytorch/distributed.py

This PR makes the TE checkpoint recursively search for TE submodules in the checkpointed module and only passes pure-PyTorch modules through to the native PyTorch checkpoint function.
Fix for #776.

[PyTorch] TE checkpoint pass-through logic fix 

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py
transformer_engine/pytorch/utils.py

1. Remove docs for 'is_first_module_in_mha' in Linear API's forward.
2. Add check for FP8 before calling function to update amaxes.
3. Only call `is_first_fp8_module` if any of the inputs or params require grad. We don't want the attribute to be set on a module for which bprop will not be executed.
4. Fix the type check for `grad_output` in Linear backward since it is a Tensor (fwd returns 1 output).

[PyTorch] Misc fixes for release_v1.6

---

transformer_engine/pytorch/distributed.py

Fix for TE checkpoint incorrectly passing custom classes/callables to the native PyTorch checkpoint.

[PyTorch] Fix for type checking failure on custom callables

---

examples/jax/encoder/test_single_gpu_encoder.py
examples/jax/mnist/test_single_gpu_mnist.py
qa/L0_jax_unittest/test.sh
qa/L1_jax_distributed_unittest/test.sh
tests/jax/pytest.ini

This PR fixes the incorrect syntax for `static_argnums` in the single-GPU encoder example.
JAX has apparently been raising a warning about this for close to 2 years that went unnoticed on our end because we run TE/JAX CI with a global warning ignore: `pytest -Wignore`
This PR replaces `-Wignore` with a limited set of filtered warnings defined under `tests/jax/pytest.ini`. The list of warnings here are based on [JAX's own pytest ignores](https://github.com/google/jax/blob/06cd05d1d6722e77744556983e99396d0c208774/pyproject.toml#L59-L88). Any warnings in the CI not covered by this list and need to be filtered should be added to this file moving forward.

[JAX] Fixing CI failure due to incorrect use of `static_argnums` in jax.jit

---

examples/jax/encoder/test_single_gpu_encoder.py
examples/jax/mnist/test_single_gpu_mnist.py
transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/csrc/modules.cpp
transformer_engine/jax/csrc/modules.h

- Pass the uncompressed shape of `dgamma` and `dbeta` to `CustomCallNormDescriptor` for the shape checking in `layernorm_bwd`, which was introduced recently.

[JAX] Allow multi-dims for dgamma and dbeta in LN descriptor.

---

transformer_engine/pytorch/module/base.py

This is a quick PR that fixes a typo from #768 and can be cherry-picked into the 1.6 release. See https://github.com/NVIDIA/TransformerEngine/pull/794 for a full description.

[PyTorch] Fix typo from #768

---

transformer_engine/pytorch/__init__.py
transformer_engine/pytorch/cpu_offload.py
transformer_engine/pytorch/distributed.py
transformer_engine/pytorch/float8_tensor.py
transformer_engine/pytorch/fp8.py
transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/softmax.py

https://github.com/NVIDIA/TransformerEngine/pull/768 introduced a typo that was covered up by a Pylint override. Going forward we should only rely on linter overrides when absolutely necessary. Even if there are cases where it makes code slightly messier, the style consistency and error checking are still worth it.
This PR removes all of the Pylint overrides that were easy to remove.

[PyTorch] Remove unnecessary Pylint overrides

---

examples/jax/encoder/test_single_gpu_encoder.py
examples/jax/mnist/test_single_gpu_mnist.py
qa/L0_jax_unittest/test.sh
qa/L1_jax_distributed_unittest/test.sh
tests/jax/pytest.ini
transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/csrc/modules.cpp
transformer_engine/jax/csrc/modules.h

[JAX] Cherry-pick #785 and #780

---

tests/pytorch/test_sanity.py
transformer_engine/pytorch/cpp_extensions/cast.py
transformer_engine/pytorch/cpp_extensions/gemm.py
transformer_engine/pytorch/cpp_extensions/transpose.py
transformer_engine/pytorch/csrc/extensions/cast.cu
transformer_engine/pytorch/csrc/extensions/transpose.cu
transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/module/linear.py

Add FP8 support for MoE in MCore.
Related MR in MCore:
https://gitlab-master.nvidia.com/ADLR/megatron-lm/-/merge_requests/1089
Implementation details:
- Add `rng_tracker_name` for initialize with EP
- Add if statement in kernel to handle zeros tokens passed to an expert.

FP8 Support for MCore MoE

---

transformer_engine/common/utils.py

Add module level filter for deprecation warning in common

---

transformer_engine/pytorch/attention.py

This PR removes `tp_size`/`tp_group` in `FusedAttention` since amax reduction is handled by `FP8GlobalStateManager.get_fp8_group()`.

[PyTorch] Fix tp_group_initialized error

---

.gitignore
transformer_engine/pytorch/attention.py
transformer_engine/pytorch/float8_tensor.py

We're seeing Pylint failures in the nightly CI because we are defining some PyTorch autograd functions that don't access the autograd context. This PR silences those warnings by renaming the args with a leading underscore.

[PyTorch] Fix linter warnings from unused args

---

transformer_engine/common/recipe/delayed_scaling.cu

The amax history should be rolled only for modules which ran and thus produced a non-zero amax. This bug was introduced in #575.
Fixes #814

Avoid amax roll for non-run modules

---

qa/L0_pytorch_unittest/test.sh
tests/pytorch/test_recipe.py
transformer_engine/common/recipe/delayed_scaling.cu
transformer_engine/pytorch/fp8.py

When the amax is too tiny that the scale becoming infinite in FP32, we set the scale to the max value of FP32. In this case, the tensor’s amax won't get mapped to the FP8 max representable, but rather something below that, but this is the best thing we can do.
cc @Oleg-Goncharov

Handle the scaling factor when amax is too tiny that leads to an infinite scale

---

tests/jax/conftest.py
tests/jax/test_custom_call_compute.py
tests/jax/test_fused_attn.py
tests/jax/test_layer.py
tests/jax/test_praxis_layers.py
tests/jax/test_softmax.py
tests/jax/utils.py
transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/flax/module.py
transformer_engine/jax/flax/transformer.py

This PR does the following changes:
1. Add `layernorm_fp8_dot` unit tests
2. Add `test_softmax.py` for testing the softmax primitives
3. Extend the softmax primitives max seqlen to 16384, which was introduced in https://github.com/NVIDIA/TransformerEngine/pull/652
4. Refactor `test_layer.py` and add the coverage of the following arguments
a. dropout, dropout_dim
b. self_attn_mask, self_attn_bias
c. layernorm_eps, 
d. use_bias
e. RoPE + GQA
5. Move common fixtures to conftest.py

[JAX] Enhance JAX unit tests

---

tests/jax/test_custom_call_compute.py
transformer_engine/common/transpose/cast_transpose_fusion.cu
transformer_engine/jax/cpp_extensions.py
transformer_engine/jax/csrc/extensions.cpp
transformer_engine/jax/csrc/modules.cpp
transformer_engine/jax/csrc/modules.h
transformer_engine/jax/flax/module.py
transformer_engine/jax/mlp.py

This PR generalized the primitive blocks and respective C++ functions for activations.
Note that inputs for all activation functions should have `x.shape[-2] == len(activation_type)`.
Tests and LayerNormMLP were also updated accordingly.

[JAX] Generalizing Activation Primitives

---

tests/pytorch/test_recipe.py

This PR fixes CI failures in the FP8 recipe test, which did not reflect recent changes in https://github.com/NVIDIA/TransformerEngine/pull/575 and https://github.com/NVIDIA/TransformerEngine/pull/825. 
- Update FP8 recipe test to handle cases where amax history roll is skipped

[PyTorch] Update FP8 recipe test to handle recipe changes

---

transformer_engine/jax/cpp_extensions.py

PAXML test raises an error with the latest change in JAX.
It complains that `ActLuPrimitive.impl() missing 1 required positional argument: 'act_enum'`.
This PR addresses that issue.

[JAX] Fixes for the issue with ActLuPrimitive in PAXML

---

transformer_engine/__init__.py

Whenever a user calls `import transformer_engine`, we attempt to import all framework submodules (`transformer_engine.pytorch`, etc) within try-catch statements. However, this can suppress important errors and make debugging tricky. A more sophisticated approach is to [import the submodules lazily](https://docs.python.org/3/library/importlib.html#implementing-lazy-imports), i.e. only import a module the first time it is used. For example, if running with a PyTorch build of TE:
```python
import transformer_engine as te
te.pytorch.__file__  # Imports transformer_engine.pytorch
te.jax.__file__      # Imports transformer_engine.jax, fails, and throws import error
```
- Load framework modules lazily

Import framework submodules lazily

---

qa/L1_pytorch_context_parallel_test/test.sh
tests/pytorch/fused_attn/run_fused_attn_with_cp.py
tests/pytorch/fused_attn/test_fused_attn_with_cp.py
transformer_engine/pytorch/attention.py
transformer_engine/pytorch/csrc/extensions.h
transformer_engine/pytorch/csrc/extensions/attention.cu
transformer_engine/pytorch/csrc/extensions/pybind.cpp

Make Context Parallel support THD format.
Currently only the Flash Attention Backend is supported as Fused Attention doesn't support THD format.

Add THD format support for Context Parallel

---

transformer_engine/__init__.py

This reverts commit 07291027ed353287149e9df6030862e1e815f32f (#839) as it is the cause of several build/runtime failures related to lazy imports.

Revert "Import framework submodules lazily (#839)"

---

setup.py
transformer_engine/pytorch/attention.py

`pkg_resources` has been deprecated a while ago, and the deprecation warning turned into an error with a recent `setuptools` update. This PR replaces `pkg_resources.packaging.Version` in `pytorch/attention.py` with `packaging.version.Version` and adds `packaging` as an install dependency in `setup.py.
- Replace `pkg_sources.packaging.Version` with `packaging.version.Version` in `pytorch/attention.py`.
- Add `packaging` as an install dependency in `setup.py`.

[PyTorch] Replaced deprecated `pkg_resources` with `packaging`

---

tests/pytorch/test_sanity.py
transformer_engine/common/gemm/cublaslt_gemm.cu

[Common] Added Alignment Requirements for CuBLAS heuristics

---

tests/jax/test_layer.py
transformer_engine/jax/flax/module.py

This PR is to fix shaping miss-matching issues inbetween activations and its corresponding sharding contraints in MLP/FF1 when using unfused activation functions.
- Squeeze output tensors of intermediate acitivations.

[JAX] Fixed the shape miss-matching issue in MLP.

---

docs/examples/advanced_optimizations.ipynb

The process group for FP8 amax reductions should be the tensor-parallel group, but we use the data-parallel group in the docs for multi-GPU training. See https://github.com/NVIDIA/TransformerEngine/issues/656#issuecomment-1972000820.
Fixes https://github.com/NVIDIA/TransformerEngine/issues/656.
- Use tensor-parallel group for FP8 group in multi-GPU training docs

Use correct FP8 group in multi-GPU docs

---

transformer_engine/pytorch/attention.py

Our RoPE kernels only support FP32 RoPE tensors, which has resulted in runtime errors when BF16 RoPE tensors are provided. This PR just casts the RoPE tensors to FP32 as needed. If these casts add too much overhead, a more robust solution would be to modify the kernels to handle more dtypes. In that case, we should reimplement the kernels with NVRTC to avoid compiling a bunch of extra kernels.
- Cast RoPE tensors to FP32 if needed

[PyTorch] Make sure RoPE frequencies are in FP32

---

transformer_engine/pytorch/csrc/ts_fp8_op.cpp

https://github.com/NVIDIA/TransformerEngine/pull/772 added `int8_t` arguments to some of the PyTorch extensions. PyTorch support for `int8_t` in Pybind11 extensions was added in PyTorch 2.3.0 (see https://github.com/pytorch/pytorch/pull/119639), resulting in TE build errors with older PyTorch versions (https://github.com/NVIDIA/TransformerEngine/issues/881).
This PR replaces these `int8_t` with `int64_t`. These are cast to `int` anyways, and it doesn't seem inconceivable to set the SM margin above 127.
- Replace `int8_t` in PyTorch extensions with `int64_t`

[PyTorch] Replace `int8_t` in Pybind11 extensions with `int64_t`

---

README.rst
docs/api/common.rst
tests/jax/test_helper.py
tests/pytorch/fused_attn/test_fused_attn.py
tests/pytorch/test_onnx_export.py
tests/pytorch/test_recipe.py
tests/pytorch/test_sanity.py
transformer_engine/common/recipe/__init__.py
transformer_engine/jax/fp8.py
transformer_engine/paddle/fp8.py
transformer_engine/pytorch/fp8.py

Removes the `interval` argument from the delayed scaling recipe, which is unused.
Fixes #805 
Removes the `interval` argument from the delayed scaling recipe.

Remove interval arg from recipe

---

qa/L0_jax_unittest/test.sh
qa/L0_paddle_unittest/test.sh
qa/L0_pytorch_unittest/test.sh
setup.py

#877 revealed an issue when using pytest.ini config with lower version of pytest that result in CI failures in JAX distributed testing.
Upgrade minimum `pytest` version to `8.2.1` for testing.

Upgrade pytest version

---

transformer_engine/common/util/cuda_runtime.cpp
transformer_engine/common/util/system.cpp
transformer_engine/common/util/system.h

This is a cleaner workaround for undefined symbol errors for `transformer_engine::getenv` in the PyTorch `CUDAExtension` for which previously `system.cpp` from the common lib was being included as a source file in the framework build. We still need to be mindful when using `getenv` in the framework extensions henceforth with T as `string` or `filesystem::path` since this would also be the return type and would lead to the same errors.
Changes `transformer_engine::getenv` to use `const char*` arg instead of `std::string` argument.

Make transformer_engine::getenv arguments independent of C++ ABI version

---

transformer_engine/jax/csrc/extensions/packing.cpp

When descriptors are not value initialized the serialization in the HLO is different between different runs of the same computations because of variability in padding bits. This has implications for compilation caching.

Value initialize packing descriptors

---

transformer_engine/pytorch/distributed.py

`te.distributed.checkpoint` + `torch.compile` causes errors with user context functions and `torch.amp.autocast()` support in our checkpointing. The native PyTorch checkpoint wrapper avoids these issues via `@torch._disable_dynamo` for the checkpoint wrapper. This PR applies the same decorator to our own checkpoint.
Deprecation warnings were also discovered with PyTorch autocast API in the course of testing the fix. This PR also incorporates the minor changes required to address those deprecations.
Fixes #890
- Added `@torch._disable_dynamo` decorator to `te.distributed.checkpoint()`.
- Fixed PyTorch deprecations for autocast API used in `te.distributed._get_active_autocast_contexts()` .

[PyTorch] Disabling TorchDynamo for TE activation checkpoint wrapper

---

tests/cpp/CMakeLists.txt

#877 introduced a bug when building the cpp tests after an inplace build. To repro, run:
```
pip install --verbose -e .
cd tests/cpp && mkdir build && cd build && cmake ..
```
Error:
```
CMake Error at CMakeLists.txt:29 (find_library):
Could not find TE_LIB using the following names: transformer_engine
```
Adds the top level TE location to the search path in the test build.

Fix local cpp tests after inplace build

---

transformer_engine/pytorch/jit.py

Nvfuser is depracated starting torch 2.2 so disabling that here
Ignore nvfuser options when torch version >= 2.2

disable using nvfuser when pytorch version >= 2.2

---

transformer_engine/pytorch/optimizers/__init__.py

Expose `multi_tensor_*` kernels under `transformer_engine.pytorch.optimizers` to avoid importing `transformer_engine_torch` outside of TE.

[PyTorch] Expose `multi_tensor_*` kernels

---

transformer_engine/pytorch/distributed.py

PR #916 prematurely updated PyTorch autocast API to v 2.4.0-RC. This PR reverts it back to the API in v2.3.1 and older.
- Revert autocast API changes in PR #916.

[PyTorch] reverting autocast API back to PyTorch v2.3.1 and below

---

transformer_engine/common/rmsnorm/rmsnorm_api.cpp

The optimimzed RMSNorm kernels access data with vectorized loads/stores, and can thus experience alignment issues if the data pointers are misaligned (e.g. they are views within a larger buffer). This PR falls back to unoptimized kernels (with entry-wise memory accesses) if data pointers are not aligned.
This is the same fix as https://github.com/NVIDIA/TransformerEngine/pull/490.
- Use unoptimized RMSNorm kernel if pointers are not aligned

Use unoptimized RMSNorm kernel if pointers are not aligned

---

examples/jax/mnist/test_single_gpu_mnist.py
transformer_engine/common/transpose/cast_transpose_fusion.cu

In JAX, we call `dbias_cast_transpose` and `dact_dbias_cast_transpose` with empty tensors to get the workspace size before calling the actual functions. So this fix is needed.

[Common] Remove CheckTensor if the workspace is empty in cast_transpose_fused

---

transformer_engine/jax/csrc/extensions/activation.cpp
transformer_engine/jax/csrc/extensions/normalization.cpp
transformer_engine/jax/csrc/extensions/quantization.cpp
transformer_engine/jax/csrc/extensions/transpose.cpp

Plain C asserts in TE/JAX custom ops get optimized out of the code at compile time and trigger unused-variable warnings. This PR replaces these asserts with `NVTE_CHECK()` to avoid the warnings. Also removes unused SM margin variables.
- Replace C asserts in TE/JAX with `NVTE_CHECK`.
- Remove unused `sm_margin`.

[JAX] Fixing `unused-variable` warning at TE/JAX extension compile

---

transformer_engine/pytorch/csrc/extensions/pybind.cpp

This PR releases the GIL within PyTorch extensions to enable some multithreaded workflows (see https://github.com/NVIDIA/TransformerEngine/issues/868). As far as I'm aware of, the only time we call Python from within  C++ is when initializing Userbuffers (i.e. when using NCCL to bootstrap UB comms).
Closes https://github.com/NVIDIA/TransformerEngine/issues/868.
- Release GIL in PyTorch extensions

[PyTorch] Release GIL in PyTorch extensions

---

build_tools/build_ext.py
build_tools/jax.py
build_tools/utils.py

- ~~Enabling parallel build with `cmake` via `-j`.~~
- The current configs create two build directories, one is `TE_PATH/build_tools/build/cmake`, the other is `TE_PATH/build`. So I introduced a change in which `cmake` directory is created under `TE_PATH/build`, thus no `build` directory under `TE_PATH/build_tools` is created.
- Adding an option to select particular files with the same file extensions (for example *.cpp) in `all_files_in_dir`.

Improve JAX build tool

---

transformer_engine/pytorch/csrc/userbuffers/userbuffers.cu

This has been mentioned in #560 but somehow someone just changed it back... Importing <cuda_fp8.h>, which imports <cuda_bf16.h>, after defining nv_bfloat16 triggers re-declaration error.

Fix compilation bug with CUDA 12.1

---

tests/pytorch/fused_attn/test_fused_attn_with_cp.py

The `_cudnn_version` function was removed from the fused attention tests in https://github.com/NVIDIA/TransformerEngine/pull/889, but not from the corresponding tests for context parallelism. This has already been fixed in the `main` branch with https://github.com/NVIDIA/TransformerEngine/pull/927, but not in the 1.8 release.
- Fix invalid import in test for context parallelism

[PyTorch] Fix invalid import in test for context parallelism

---

build_tools/utils.py
tests/pytorch/distributed/test_convergence.py
tests/pytorch/fused_attn/test_fused_attn.py
transformer_engine/pytorch/utils.py

[`functools.cache`](https://docs.python.org/3/library/functools.html#functools.cache) was added in Python 3.9, leading to problems with older Python versions (see https://github.com/NVIDIA/TransformerEngine/issues/958). The fix is to replace it with [`functools.lru_cache(maxsize=None)`](https://docs.python.org/3/library/functools.html#functools.lru_cache), which is equivalent.
I've also made some minor stylistic changes in the affected code:
- Alphabetized imports
- Avoided importing individual functions, per [Google's style guide](https://google.github.io/styleguide/pyguide.html#22-imports)
- Replaced `functools.cache` with `functools.lru_cache(maxsize=None)`

Replace functools cache with lru_cache

---

tests/pytorch/fused_attn/test_fused_attn_with_cp.py

This PR disables CP tests for THD format for architectures lower than sm90. In the future, we will add a utility function so users can check this before running any tests.
- [x ] Bug fix (non-breaking change which fixes an issue)
- Skipped tests for fused attention with THD and CP on <sm90.
- [x ] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x ] The functionality is complete
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit …

[PyTorch] Disable THD tests on architectures lower than sm90

---

tests/pytorch/fused_attn/test_fused_attn.py
tests/pytorch/test_sanity.py
transformer_engine/common/fused_attn/fused_attn.cpp
transformer_engine/pytorch/attention.py
transformer_engine/pytorch/csrc/extensions/attention.cu
transformer_engine/pytorch/module/grouped_linear.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/linear.py

Miscellaneous changes to improve attention, update cudnn-frontend, fix logging, etc.
- Update cudnn-frontend to 1.5.2
- Fix logging info in layernorm_linear and linear
- Disable cuDNN 9.1 and 9.2 for THD support (due to numerical issues)
- Set `cu_seqlens_padded` to `cu_seqlens` when it's unset, for BSHD/SBHD
- [x ] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x ] The functionality is complete
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] …

Update FE to 1.5.2 and miscellaneous fixes

---

transformer_engine/common/rmsnorm/rmsnorm_api.cpp

https://github.com/NVIDIA/TransformerEngine/pull/886 introduced a bug by checking the wrong `unordered_map` when deciding whether to use a tuned RMSNorm kernel. See https://github.com/NVIDIA/TransformerEngine/issues/941#issuecomment-2202068692.
- Fix bug from checking wrong `unordered_map` when deciding to whether to use tuned RMSNorm kernel

[Core] Fix bug when selecting tuned RMSNorm kernels

---

transformer_engine/pytorch/csrc/extensions/transpose.cu

Replace the return value from input with output in `fp8_cast`.
When training MoE models and disable gradient accumulation fusion, if an linear expert receive zero number of tokens, this bug will cause tensor shape mismatch between wgrad and weight.
- Change A
- Change B

[MoE][Pytorch]Fix size mismatch error in fp8 transpose.

---

transformer_engine/jax/cpp_extensions/activation.py
transformer_engine/jax/cpp_extensions/softmax.py
transformer_engine/jax/cpp_extensions/transpose.py

JAX introduced a new PR (google/jax#22211) which restrictes the output format of HLO lowering with an additional assertion. The assertion fails when the lowering function returns a single value wrapped in a tuple or a list which we have in a few custom calls in TE. This restriction is then relaxed temporarily in google/jax#22314 by replacing the assertion with a warning.
This PR removed all the singleton wrappers in our TE custom call so no warnings or issues arise.

[TE/JAX] Remove tuple wrapper of singleton in HLO lowering return

---

build_tools/paddle.py
transformer_engine/paddle/csrc/custom_ops.cu

This allows TE-paddle build on paddlepaddle-gpu==2.6.1.
`PADDLE_VERSION` is not defined in `python3.10/site-packages/paddle/include/` so we export runtime paddle version into compiler.

[Paddle] Compile with paddlepaddle-gpu 2.6.1

---

transformer_engine/pytorch/csrc/comm_gemm_overlap.h

PR #1004 broke GEMM + reduce-scatter overlap algorithms for BF16 inputs. This shifts the `TRANSFORMER_ENGINE_TYPE_SWITCH_FP8_ONLY(...)` macro to wrap only the FP8 reduce-scatter kernels in order to avoid invalid type errors.
- Corrected use of `TRANSFORMER_ENGINE_TYPE_SWITCH_FP8_ONLY(...)` in `pytorch/csrc/comm_gemm_overlap.h`

[C/PyTorch] Fixing incorrect use of TYPE_SWITCH_FP8_ONLY in GEMM + reduce-scatter overlap

---

transformer_engine/common/nvtx.h

nvtx3 is a newer nvtx API and it is header-only, where old nvtx requires to link.
PaddlePaddle is using the newer nvtx3 library which conflicts with the current old nvtx used in TE. This PR is to use the newer nvtx3 as the header to address the compatible issue.
https://github.com/NVIDIA/NVTX?tab=readme-ov-file#c-and-c
- Change to use nvtx3 header
- Fix Paddle GitLab CI build

[Common] Use nvtx3

---

transformer_engine/pytorch/ops/sequential.py

https://github.com/pytorch/pytorch/pull/130199 changed `torch.nn.Module` so it stores internal modules in a `dict` instead of a `collections.OrderedDict`. This PR fixes some resulting test failures with `te.Sequential`.
- Update sequential container to handle storing modules in plain dicts

[PyTorch] Update Sequential container to handle changes in module base class

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

Fixed convergence issues when CPU offloading is enabled.
1) When activation offloading was enabled, the reloaded weights during backprop was re-constructed into a torch.nn.Parameter with the `requires_grad` switch as false. This switch should be try to compute weight gradients. Fixed this.
2) When weights are offloaded we try to offload the gradient accumulation buffer, by doing a deep copy of this buffer and recreating this which confuses the Distributed Optimizer about this buffer location. This makes the DistOpt using a stale location to look for fresh gradients from recent micro-batches. This has been fixed by not offloading the gradient accumulation buffer. Offloading gradient accumulation buffer was considered a free lunch but this subtle issues made me go back with my decision.

Fixed convergence issues with CPU offloading

---

transformer_engine/pytorch/cpu_offload.py
transformer_engine/pytorch/module/grouped_linear.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

1) Made a fix to remove unwanted MemcpyDtoD kernels when CPU offloading is enabled. 
2) When initializing the Parameter, we need to pass on the weight and the weight.requires_grad. So adding that.
3) Added the fixes in point#2 for grouped_linear module.

Remove unwanted Memory Copies/Fix weight parameters

---

build_tools/pytorch.py
examples/pytorch/comm_gemm_overlap/README.md
examples/pytorch/comm_gemm_overlap/ln_mlp_with_overlap.py
tests/pytorch/distributed/run_gemm_with_overlap.py
tests/pytorch/distributed/test_comm_gemm_overlap.py
transformer_engine/pytorch/csrc/comm_gemm_overlap.h
transformer_engine/pytorch/csrc/extensions/pybind.cpp
transformer_engine/pytorch/csrc/userbuffers/ipcsocket.cc
transformer_engine/pytorch/csrc/userbuffers/ipcsocket.h
transformer_engine/pytorch/csrc/userbuffers/userbuffers-host.cpp
transformer_engine/pytorch/csrc/userbuffers/userbuffers.cu
transformer_engine/pytorch/csrc/userbuffers/userbuffers.h
transformer_engine/pytorch/module/base.py

Multi-node use cases for comm+GEMM overlap in NeMo started hanging at `initialize_ub()` after PR #901 was merged.
The cause was identified to be the assumption in PR #901 that the user-provided tensor-parallel group is always equivalent to the intra-node MPI communicator in the old MPI-based bootstrapping. As a consequence of this assumption, the new `torch.distributed`-based bootstrapping could potentially try to initialize Userbuffers with local rank/size information that does not span the entire physical node, thus causing the CUDA Multicast shareable handle communication logic (over Unix domain sockets) to silently fail and hang.
This PR re-implements the equivalent of the old MPI-based bootstrapping logic inside `initialize_ub()` via `torch.distributed` collectives. `initialize_ub()` …

[PyTorch] Fixing hang in `initialize_ub()` for multi-node runs after PR901 removal of MPI-dependence

---

.github/workflows/build.yml
setup.py
transformer_engine/common/CMakeLists.txt

We have had users run into build errors using CMake 3.20 (see https://github.com/NVIDIA/TransformerEngine/issues/803#issuecomment-2128275904), so this PR bumps the minimum version to 3.21 and uses it in the core-only build test. I may bump the version again if the build test fails.
I've also removed logic that links NVTX. https://github.com/NVIDIA/TransformerEngine/pull/1025 upgraded to NVTX 3, which is header-only.
Closes https://github.com/NVIDIA/TransformerEngine/issues/803. Also see https://github.com/NVIDIA/TransformerEngine/pull/943.
- Increase minimum CMake version
- No longer link to NVTX

Update minimum CMake version

---

transformer_engine/paddle/csrc/custom_ops.cu

https://github.com/NVIDIA/TransformerEngine/pull/1029 introduced a compilation error when cherry-picked into the `release_v1.9` branch. I would expect a similar error to show up when building with Paddle 2.7+.
- Fix compilation error in Paddle extension

Fix build error with Paddle >2.6.1

---

build_tools/wheel_utils/build_wheels.sh
qa/L0_paddle_wheel/test.sh
transformer_engine/common/CMakeLists.txt
transformer_engine/common/pycudnn.cpp

A follow-up PR to #1036 mainly enabling dynamic loading of a different cudnn lib version at runtime.
- Use dynamic loading for cudnn-frontend using CMake flag.
- Add the symbol for cudnn_dlhandle to debug linker issue.
- Minor fix in paddle wheel CI test.

Fixes for pip wheels

---

transformer_engine/pytorch/attention.py

This bug will cause bug` [ERROR] failed (exitcode: -11) local_rank: 0 (pid: 1761020) of binary: ~/megatron/bin/python.`
That is because we miss the rng_states that is required in attention recompute (for dropout) of backward, but no hint is provided.  
It is very very very difficult to trace and cost me two weeks.
```python
before the start of training step] datetime: 2024-07-22 18:26:45 
[2024-07-22 18:27:00,941] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -11) local_rank: 0 (pid: 1761020) of binary: /home//miniconda3/envs/megatron/bin/python
Traceback (most recent call last):
File "/home//miniconda3/envs/megatron/bin/torchrun", line 33, in <module>
sys.exit(load_entry_point('torch==2.2.1+cu121', 'console_scripts', 'torchrun')())
File …
```

fix bug of attn backward in non-casual model with context parallel open.

---

tests/pytorch/fused_attn/test_fused_attn.py

`pkg_resources` has been fully removed in `setuptools` v70.0.0
Remove unused import in fused attention test

[pytorch] removed unused import causing CI failures in fused attention

---

transformer_engine/pytorch/attention.py

Fix an argument error when using TE with `flash_attn>=2.5.7`, that it will have an argument named [block_table](https://github.com/Dao-AILab/flash-attention/blob/v2.5.7/flash_attn/flash_attn_interface.py#L82) without any default values until 2.6.1, meaning if `flash_attn` version in range `[2.5.7, 2.6.1]` will report an error `TypeError: _flash_attn_varlen_forward() missing 1 required positional argument: 'block_table'`
- Add the missing argument `block_table` when detecting the corresponding flash_attn version in `transformer_engine/pytorch/attention.py`

Fix an argument issue when flash_attn>=2.5.7

---

tests/jax/test_fused_attn.py
transformer_engine/jax/cpp_extensions/attention.py
transformer_engine/jax/cpp_extensions/misc.py
transformer_engine/jax/csrc/extensions/attention.cpp
transformer_engine/jax/csrc/extensions/pybind.cpp
transformer_engine/jax/csrc/utils.cu
transformer_engine/jax/csrc/utils.h

cuDNN 9.3.0 supports act_seqlen=0, which allow us to reuse the same cuDNN graph for different number of segments.
Re-use cuDNN graph when cuDNN version >= 9.3.0

[JAX] Reduce lowering time after cuDNN 90300

---

tests/jax/test_fused_attn.py

Somehow bias = `1HSS` was missing in the current tests. This PR is to add this back.
Add back the bias = 1HSS unit tests.

[JAX] Add the missing 1HSS tests

---

tests/pytorch/test_numerics.py
transformer_engine/pytorch/cpp_extensions/gemm.py
transformer_engine/pytorch/cpp_extensions/transpose.py
transformer_engine/pytorch/csrc/extensions.h
transformer_engine/pytorch/csrc/extensions/pybind.cpp
transformer_engine/pytorch/csrc/extensions/transpose.cu
transformer_engine/pytorch/csrc/ts_fp8_op.cpp
transformer_engine/pytorch/module/grouped_linear.py

Try to reduce the CPU overheads of `GroupedLinear` by:
1. Using `fused_multi_cast_transpose` instead of iterating `cast_transpose_fused` in a for-loop.
a. Changed the API of `fused_multi_cast_transpose` to avoid index-select ops in PyTorch.
b. Allocate output tensors in CPP.
2. Use `at::cuda::current_device()`, which has a cache, to get current device id to avoid `cudaGetDriverEntryPoint` calls.
3. Reduce `torch.Tensor()` calls.
4. TODO.
Fix:
1. Zero `grad_bias` in `fused_cast_transpose_bgrad` when input is empty.
2. Typos.

[PyTorch] Reduce the CPU overheads of `GroupedLinear`

---

qa/L0_pytorch_unittest/test.sh

test_recipe.py was invoked twice in pyTorch unittests.
- Removed second invocation of the test_recipe test.

Remove duplicate test

---

qa/L0_jax_unittest/test.sh

NLTK's latest versions have introduced a [bug](https://github.com/Unstructured-IO/unstructured/issues/3511) resulting in JAX ci failures.
Pin NLTK version to 3.8.1 for CI tests.

Pin NLTK version to fix JAX ci

---

tests/pytorch/fused_attn/test_fused_attn.py
tests/pytorch/test_onnx_export.py
transformer_engine/pytorch/attention.py

This PR merges `k_channels` and `v_channels` back to `kv_channels` in `DotProductAttention.__init__()` to avoid breaking backward compatibility, but it allows users to pass in a tuple `(int, int)` in MLA (multi-latent attention) cases.
We will add support for MLA in `MultiHeadAttention` and `TransformerLayer` in future PRs.
- Merge `k_channels` and `v_channels` back to `kv_channels` in `DotProductAttention`

[PyTorch] Merge `k_channels` and `v_channels` back to `kv_channels`

---

examples/jax/encoder/requirements.txt
examples/jax/encoder/test_model_parallel_encoder.py
examples/jax/encoder/test_multigpu_encoder.py
examples/jax/encoder/test_multiprocessing_encoder.py
examples/jax/encoder/test_single_gpu_encoder.py
qa/L0_jax_unittest/test.sh

#1096 pinned `nltk==3.8.1` for the JAX ci since `nltk>=3.8.2` introduced a breaking change. However, this is because the `punkt` package consists of unsafe pickles, so it is deprecated and not used in NLTK 3.8.2 to circumvent the underlying security vulnerability. Further reading:
1. https://github.com/nltk/nltk/issues/3293#issuecomment-2283807174
2. https://github.com/nltk/nltk/issues/3266#issuecomment-2284001819
3. https://www.vicarius.io/vsociety/posts/rce-in-python-nltk-cve-2024-39705-39706
- Pin minimum version of `nltk` to `3.8.2` for jax tests
- Switch from `punkt` to `punkt_tab` package for `nltk`.

Upgrade NLTK version to circumvent unsafe pickling in v3.8.1

---

setup.py

Remove total time measurement as having bdist time is already a good indicator.

Remove Total Time Measurement

---

build_tools/jax.py
build_tools/utils.py

PR #946 added new custom calls with FFI, which requires XLA FFI path to be included for the cmake build. 
`jax.extend.ffi.include_dir()` was used to extract the path which caused an [issue in the NVIDIA/JAX-Toolbox](https://github.com/NVIDIA/JAX-Toolbox/actions/runs/10385063935/job/28753692698#step:10:2073), as `jax` is not installed at the time TE wheel build, thus impossible to import.
This PR added an option to use a default path if `jax` is unavailable.

[TE/JAX] Add default include path for XLA FFI

---

transformer_engine/common/include/transformer_engine/fused_attn.h
transformer_engine/pytorch/attention.py

This PR corrects the explanation about `t` in `thd`. It's the total number of tokens, rather than sequences in a batch.
Fixes #1110. 
- Fix docstring related to `t` in `thd`

Fix docstring related to `t` in `thd`

---

docs/conf.py

This PR removes the commit hash from the release version of the documentation. This is because we changed the branching model of the repo and the commit hashes in the `stable` branch no longer correspond to the hashes we use to build the documentation (which are tips of the `release_vX.X` branches), even though the content is the same. In order to avoid confusion it is better to just not include the hash.
- Removed the commit hash from the version string visible in the documentation

Remove the commit hash from the release documentation

---

transformer_engine/pytorch/optimizers/fused_adam.py

Avoid adding master_param to state dict if value is None.
- Change A
- Change B

don't put master_param to state if None

---

build_tools/pytorch.py
build_tools/utils.py
setup.py

This PR adds an build-time environmental variable NVTE_CUDA_ARCHS that lets the user decide on which architectures TE will compile by default. If not set it will retain old behaviour of building TE on 70, 80, 89 and 90
- Added NVTE_CUDA_ARCHS envvar
- Common (CMake) and Pytorch Extension now respects envvar if set

Let user limit number of architectures, to improve build time

---

transformer_engine/common/CMakeLists.txt
transformer_engine/common/libtransformer_engine.version

`libtransformer_engine` currently exposes all symbols globally, which can lead to symbol resolution conflicts when certain libraries are exported after TE's shared object file is loaded dynamically, for .e.g.,
```
pip install rdkit==2024.3.3
python -c "import transformer_engine; from rdkit import Chem"
```
Leads to the following error:
```
terminate called after throwing an instance of 'std::bad_alloc'
what():  std::bad_alloc
Aborted (core dumped)
```
- Limit exposing unnecessary symbols in `libtransformer_engine`.

Hide non-necessary symbols from shared object

---

docs/api/pytorch.rst
qa/L0_pytorch_unittest/test.sh
tests/pytorch/test_permutation.py
transformer_engine/pytorch/permutation.py

- Previous `moe_permute` and `moe_unpermute` methods require users passing `tex.DType` as an argument. I think exposing `tex.DType` outside of TE should be avoided. This PR just gets the dtype from input tensors, including Float8Tensor.
- Added permutation UTs to QA.
- Change A
- Change B

[PyTorch] Remove `dtype` from args of permutation

---

tests/pytorch/fused_attn/test_fused_attn.py
transformer_engine/pytorch/attention.py

This PR fixes the backend selection logic when FA2 is present but FA3 is not. It fixes tests `test_mha_fp8_vs_f16`, `test_dpa_fp8_vs_f16` and `test_custom_mha_fp8_vs_f16` in `tests/pytorch/fused_attn/test_fused_attn.py`.
It also enforces preference for `FusedAttention` over FA3 when FP8 execution is required. FA3 currently assumes all scaling factors to be 1, while `FusedAttention` allows the use of more customized scaling factors (to each tensor and each iteration) in `fp8_meta`.
- Sets `use_flash_attention=False` when FA3 is not available, for FP8 tests
- Avoids FA3 tests when it's not installed 
- Prefers `FusedAttention` over FA3 for FP8 attention, when both FA3 and `FusedAttention` are eligible backends

[PyTorch] Fix FP8 logic related to FA2/FA3

---

transformer_engine/pytorch/attention.py

Fix the QKV dtype in the bwd of FP8+CP.
- Change A
- Change B

Fix QKV dtype in the bwd of FP8+CP

---

transformer_engine/pytorch/csrc/extensions/gemm.cu

The type of input and output of `te_grouped_gemm` is `std::vector<at::Tensor>`. If the tensor is not contiguous it will causes potential accuracy problem and **it is hard to debug**. It's a useful safe operator to check every tensor is contiguous.
Why use `is_contiguous` instead of `contiguous`?
If tensor is non-contiguous `contiguous` will call aten::clone to generate a new tensor. It will cause potential performance fallback and generally user is hard to find reason (maybe them need profile).
- Add contiguous check for `te_grouped_gemm`

[PyTorch] Add contiguous check for `te_grouped_gemm`

---

transformer_engine/pytorch/attention.py

This PR allows offloading the QKV activation tensors for FP8 Attention.

Added offloading support FP8 attention

---

tests/cpp/operator/CMakeLists.txt
tests/cpp/operator/test_multi_padding.cu
tests/pytorch/test_numerics.py
transformer_engine/common/CMakeLists.txt
transformer_engine/common/include/transformer_engine/padding.h
transformer_engine/common/util/padding.cu
transformer_engine/pytorch/__init__.py
transformer_engine/pytorch/cpp_extensions/__init__.py
transformer_engine/pytorch/cpp_extensions/padding.py
transformer_engine/pytorch/csrc/common.h
transformer_engine/pytorch/csrc/extensions.h
transformer_engine/pytorch/csrc/extensions/padding.cu
transformer_engine/pytorch/csrc/extensions/pybind.cpp
transformer_engine/pytorch/module/__init__.py
transformer_engine/pytorch/module/fp8_padding.py
transformer_engine/pytorch/module/fp8_unpadding.py

Currently the FP8 unpadding backward is implemented by torch.autograd. it involves num_gemms * aten::fill + DtoD call that hurts the MoE model performance in FP8 training. So we implemented Fp8 padding and unpadding module to eliminate the overhead of autograd. The workflow shows below.
Workflow:
I show 2% E2E performance gain in our MoE model.
- Implement a kernel `multi_padding_kernel` which fused multi-tensor padding.
- Implement `FP8Padding` and `FP8Unpadding` module.

[PyTorch] Implement Fp8 padding and unpadding module

---

transformer_engine/common/CMakeLists.txt

Reverts NVIDIA/TransformerEngine#1158
Fix: https://github.com/NVIDIA/cudnn-frontend/pull/105

Revert "[C] Suppress 128-D warning from cudnn-frontend"

---

tests/pytorch/test_numerics.py
transformer_engine/pytorch/cpp_extensions/gemm.py
transformer_engine/pytorch/cpp_extensions/transpose.py
transformer_engine/pytorch/csrc/extensions.h
transformer_engine/pytorch/csrc/extensions/gemm.cu
transformer_engine/pytorch/csrc/ts_fp8_op.cpp
transformer_engine/pytorch/module/grouped_linear.py

This PR
- Propagates the fp8 scale-inverse modification to `GroupedLinear`.
- Fixes a bug that wrong `scale_inv` is used for weights in `fp8_grouped_gemm`.
- Adds a new grouped gemm interface for separate scale_inv (for weights) and single output (for fwd output and bwd dgrad).

[PyTorch] Propagate fp8 scale-inverse modification to `GroupedLinear`

---

tests/jax/test_fused_attn.py

The JAX unit tests for fused attention are exercising a bug introduced in cuDNN 9.4 where zero-legth sequences would cause cuDNN error at runtime.
More details are in cuDNN9.4 release notes here: https://docs.nvidia.com/deeplearning/cudnn/latest/release-notes.html#cudnn-9-4-0
Avoid zero-length sequences in Jax fused attention unit test on cuDNN 9.4.

[JAX] Fix  unit tests to work around cuDNN 9.4 regression of 0 length sequences

---

transformer_engine/pytorch/optimizers/multi_tensor_apply.py

multi_tensor_apply needs to work directly on the local shards of the DTensors in the optimizer states.
- If tensor is DTensor, replace it with its local shard.

Add dtensor support for TE optimizers

---

tests/jax/distributed_test_base.py
tests/jax/test_distributed_fused_attn.py
transformer_engine/jax/attention.py
transformer_engine/jax/cpp_extensions/attention.py
transformer_engine/jax/csrc/extensions/pybind.cpp
transformer_engine/jax/sharding.py

Adds support for context parallel fused attention based on an all-gather/reduce-scatter approach. This implementation exposes the collective communication between CP ranks.
The first implementation of CP only support causal and no masking without bias. Additional QKV formats and configurations will be added to subsequent PRs.
Adds context parallel axis resource and new primitives to fused attention.

[JAX] Context Parallel Attention with All-Gather

---

transformer_engine/common/__init__.py

This PR ensures that we always look for cuDNN and NVRTC under `/usr/local/cuda` when importing Transformer Engine without requiring `CUDA_HOME` or `CUDA_PATH` to be set to the default CUDA installation path. The user should only need to set these variables if CUDA is installed in a non-standard/custom path.
- Dynamically loading cuDNN and NVRTC now always falls back on checking `/usr/local/cuda` when `CUDA_HOME` or `CUDA_PATH` variables are *not* set.

[Common] Default CUDA_HOME to /usr/local/cuda when dynamically loading cuDNN and NVRTC

---

build_tools/build_ext.py

Allow specifying which directory to store cmake build cache, which makes user defined docker buildx workflows more flexible.
- [x ] New feature (non-breaking change which adds functionality)
- Change A
- Change B
- [x ] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x ] The functionality is complete
- [na] I have commented my code, particularly in hard-to-understand areas
- [na ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [na] I have added tests that prove my fix is effective or that my feature works
- [na] New …

Allow specifying cmake setup directory

---

README.rst
docs/installation.rst

Adds documentation for installing directly from PyPI.
Add TE install instructions from PyPI into README and installation guide.

Add docs for installing from PyPI

---

tests/pytorch/test_fused_optimizer.py

The fused optimizers from Apex (see https://github.com/NVIDIA/TransformerEngine/pull/867) included `unittest` tests. This PR ports them to `pytest` so they will run in our CI pipelines.
- Port fused optimizer tests from unittest to pytest

[PyTorch] Port fused optimizer tests to pytest

---

transformer_engine/pytorch/module/base.py

`te.initialize_ub()` constructs a list of ranks on the same physical node by comparing hostnames from network interfaces defined by `NVTE_UB_SOCKET_IFNAME`, `NCCL_SOCKET_IFNAME` or `GLOO_SOCKET_IFNAME` environment variables, in that order of priority. If none are defined, it falls back on using `os.gethostname()` instead.
This approach fails when `NCCL_SOCKET_IFNAME` is set to a base name like `eth` while the actual network interfaces are named `eth0`, `eth1`, and so on.
This PR avoids the error by checking the detected interface name against interfaces found in `socket.if_nameindex()` and falling back onto `os.gethostname()` with a useful warning message when the detected name is not valid.
Fixes #1170

[PyTorch] Check network interface name when initializing Userbuffers

---

transformer_engine/pytorch/attention.py

The continuity requirements and behavior of FlashAttention are:
- q/k/v are contiguous **at the last dimension**. [[ref 1](https://github.com/Dao-AILab/flash-attention/blob/bdf733be55f0b323a8cf7cc6745a81c3f43cd7f0/flash_attn/flash_attn_interface.py#L15)][[ref 2](https://github.com/Dao-AILab/flash-attention/blob/bdf733be55f0b323a8cf7cc6745a81c3f43cd7f0/csrc/flash_attn/flash_api.cpp#L379-L381)]
- out has the same layout (stride) as q. [[ref](https://github.com/Dao-AILab/flash-attention/blob/bdf733be55f0b323a8cf7cc6745a81c3f43cd7f0/csrc/flash_attn/flash_api.cpp#L441)]
So we can just remove the `.contiguous()` calls on q/k/v and rely on FlashAttention doing the minimum continuity check. For `sbhd` formats, all the four `.contiguous()` calls on q/k/v/out are removed.
For context parallel, we …

[PyTorch] Relax the contiguous check for flash attention

---

transformer_engine/pytorch/distributed.py

`with` statement with parentheses was introduced in Python 3.10.
Fixes #1177 
- Changed with statements to not use parentheses

Restore compatibility with Python 3.8

---

build_tools/pytorch.py

Fix reading `NVTE_UB_WITH_MPI` env var.
- Fix reading str to reading as bool

fix NVTE_UB_WITH_MPI read

---

transformer_engine/pytorch/graph.py

Support for user pre-allocated graph pool was added to `make_graphed_callables` in [this upstream PR](https://github.com/pytorch/pytorch/pull/121475). This PR replicates that functionality.
Fixes #1201 
- Added `pool` argument to `make_graphed_callables`.

[PyTorch] Add pool argument to make_graphed_callable

---

transformer_engine/pytorch/module/grouped_linear.py

Some options in the GroupedLinear were unused (like parallel_mode) and tensor-parallelism related. Can't fully remove them now since MCore apparently sets them, but at least removing them from documentation to not cause confusion and false expectations.
Also, the offsets for the FP8 meta were set as global Python variables. This is not correct, since there could be multiple instances of the GroupedLinear with different number of GEMMs inside. Changed those to be per-module parameters.

Removed the unused options from GroupedLinear docs and fixed the bug with offsets

---

transformer_engine/pytorch/attention.py

This PR fixes issue #1213. 
- Move `block_table` argument to FA varlen function only

[PyTorch] Move `block_table` argument to FA varlen function

---

tests/pytorch/fused_attn/test_fused_attn.py
transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu

This PR adjusts the sliding window size in `FusedAttention` (cuDNN attention) so it's consistent with our support in `FlashAttention` and `UnfusedDotProductAttention`. 
cuDNN supports sliding window `(i - window_size_left, i]`, exclusive of the `i -window_size_left` element. By passing `window_size_left + 1` to cuDNN, we achieve the same effect as the `[i - window_size_left, i]` support.
This PR also reduces the window size in our unit tests so any numerical differences between backends will be easier to notice.
Fixes #1197 
- Adjust the `window_size` passed to cuDNN
- Test smaller window sizes in unit tests

Fix cuDNN sliding window size

---

tests/pytorch/test_float8tensor.py
tests/pytorch/test_fusible_ops.py
transformer_engine/pytorch/ops/basic/basic_linear.py
transformer_engine/pytorch/ops/basic/bias.py
transformer_engine/pytorch/ops/fused/backward_linear_add.py
transformer_engine/pytorch/ops/fused/forward_linear_bias_activation.py
transformer_engine/pytorch/ops/fused/forward_linear_bias_add.py
transformer_engine/pytorch/tensor/__init__.py
transformer_engine/pytorch/tensor/float8_tensor.py

Some users initialize model dtypes using module casting functions like [`torch.nn.Module.float`](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.float). However, we experience weird errors when casting fusible operations, largely because the module casting functions don't properly handle `Float8Tensor`. This PR monkey-patches some module casting functions (`float`, `half`, `bfloat16`) so they properly handle `Float8Tensor`. This PR also adds logic in the linear operation to respect [PyTorch autocasting](https://pytorch.org/docs/stable/amp.html).
- Support setting `Float8Tensor.data` to arbitrary tensors
- Monkey-patch module dtype cast functions (e.g. `torch.nn.Module.float`) to handle `Float8Tensor`
- Respect PyTorch autocast dtype in linear operation

[PyTorch] Debug dtype casting in operation-based API

---

docs/faq.rst
docs/index.rst
tests/pytorch/test_sanity.py
transformer_engine/pytorch/attention.py

This PR adds an FAQ page to the documentation, and adds a section to the FAQ about FP8 checkpoint compatibility. It also adds a sanity unit test for checkpointing with 1.11(save)/1.11(load), and 1.6(save)/1.11(load).
- Adds documentation and tests for FP8 checkpointing

[PyTorch] Add documentation for FP8 attention checkpointing

---

transformer_engine/pytorch/attention.py

This PR improves the `get_qkv_layout()` logic.
Fixes #1195 
- Improves `get_qkv_layout` function.

[PyTorch] Improve `get_qkv_layout`

---

tests/jax/test_fused_attn.py
tests/jax/test_layer.py
tests/jax/test_praxis_layers.py
tests/jax/utils.py
transformer_engine/jax/attention.py
transformer_engine/jax/cpp_extensions/attention.py
transformer_engine/jax/csrc/extensions.h
transformer_engine/jax/csrc/extensions/attention.cpp
transformer_engine/jax/csrc/extensions/packing.cpp
transformer_engine/jax/flax/transformer.py
transformer_engine/jax/praxis/transformer.py

Recent models employ sliding window attention (SWA). Some frameworks use cuDNN fused attention through the TE-JAX Flash Attention API. The SWA support has not been exposed to this API yet. However, on the backend TE does have support for the SWA. This PR expose the SWA support to the Flash Attention API.
Expose sliding window attention to the TE-JAX API

[JAX] Expose sliding window attn to TE-JAX API

---

.gitignore
transformer_engine/pytorch/tensor/float8_tensor.py

Small fixes to Float8Tensor class, mostly coming from static analysis.
- Removed a few instances of dead code coming from assuming that scale/scale_inv can be passed as something else than torch.Tensor
- Changed the position of type annotations to be consistent with [PEP 526](https://peps.python.org/pep-0526/#class-and-instance-variable-annotations)
- (unrelated) added compile_commands.json to .gitignore

Small fixes to Float8Tensor

---

transformer_engine/pytorch/attention.py

When NVTE_TORCH_COMPILE is 0,  jit_fuser will be torch.jit.script.
And the compiled function don't accept interger. Then, bug will occur in the function below  due to the `seq_dim` argument.
```
@jit_fuser
def flash_attn_fwd_out_correction(out, out_per_step, seq_dim, softmax_lse, softmax_lse_per_step):
"""Merge partial outputs of each step in Attention with context parallelism"""
softmax_lse_corrected_exp = torch.exp(softmax_lse_per_step - softmax_lse).movedim(2, seq_dim)
softmax_lse_corrected_exp = softmax_lse_corrected_exp.unsqueeze(-1)
out_corrected = out_per_step * softmax_lse_corrected_exp
out.add_(out_corrected)
```
- Change A
- Change B

Fix bug in torch compile and seqdim is integer

---

transformer_engine/common/CMakeLists.txt

It is bad practice to link against the CUDA driver library (`libcuda.so.1` on Linux) at build time because it may differ from the library at run time. In particular, the CUDA Toolkit provides stubs in case CUDA code is being compiled on a system without GPUs. TE already has infrastructure to access with CUDA driver library indirectly via [`cudaGetDriverEntryPoint`](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DRIVER__ENTRY__POINT.html#group__CUDART__DRIVER__ENTRY__POINT_1gcf55d143722ccfa9252758181701c876) (see https://github.com/NVIDIA/TransformerEngine/pull/970 and https://github.com/NVIDIA/TransformerEngine/pull/138). However, we should avoid explicitly linking against the CUDA driver in CMake to reduce the risk of linker snafus, e.g. if a future developer accidentally …

Do not link against CUDA driver when building

---

tests/jax/test_distributed_fused_attn.py
transformer_engine/jax/attention.py
transformer_engine/jax/cpp_extensions/attention.py

Adds additional checks to avoid running unsupported datatypes or shardings of fused attention on Jax.
Skip tests unless on SM 90+

Check for backend support in Jax context parallel fused attention test

---

examples/README.md

Our examples are split between examples/ and docs/examples/. We also have features (e.g. inference) hidden in our examples that would be worth summarizing in a single README. 
I'd also like to extend this to include third party examples (e.g. Hugging Face Accelerate) using TE.
- Created a new README.md

Create README.md for examples/

---

qa/L1_pytorch_FA_versions_test/test.sh
setup.py
tests/pytorch/fused_attn/test_fused_attn.py
transformer_engine/pytorch/attention.py
transformer_engine/pytorch/setup.py

This PR removes [flash-attention](https://github.com/Dao-AILab/flash-attention) as a required dependency for Transformer Engine. Users can choose to install FA2 via:
```
pip install flash-attn==2.6.3
```
or FA3 via:
```
1) pip install "git+https://github.com/Dao-AILab/flash-attention.git#egg=flashattn-hopper&subdirectory=hopper"
2) python_path=`python -c "import site; print(site.getsitepackages()[0])"`
3) mkdir -p $python_path/flashattn_hopper
4) wget -P $python_path/flashattn_hopper https://raw.githubusercontent.com/Dao-AILab/flash-attention/main/hopper/flash_attn_interface.py
```
- Remove flash-attention as a build dependency
- Change logic around backend selection/recommendation in attention

[PyTorch] Drop FA as an installation requirement

---

transformer_engine/pytorch/module/grouped_linear.py

Fix wgrads for `GroupedLinear` when weights don't require grad.
- Change A
- Change B

[PyTorch] Fix wgrads for GroupedLinear when weights don't require grad

---

qa/L0_paddle_wheel/test.sh

We have experienced test failures in the PaddlePaddle test for building Python wheels because the base container has installed `python3-wheel` with APT. This causes problems when we try installing the correct `wheel` version with Pip. This PR works around this issue by installing `wheel` locally.
- Install `wheel` locally in PaddlePaddle test for building Python wheels

[Paddle] Debug wheel test

---

qa/L3_pytorch_FA_versions_test/test.sh

This PR removes `2.4.0.post1` from the FA version sweep in the `L3_pytorch_FA_versions_test`, which would help reduce CI runtime to a more reasonable amount. 
- Reduce the number of FA versions tested in L3 tests

[PyTorch] Reduce the number of FA versions in L3 tests

---

transformer_engine/common/common.h
transformer_engine/common/fused_attn/fused_attn.cpp
transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu
transformer_engine/common/fused_attn/fused_attn_fp8.cu
transformer_engine/common/fused_attn/utils.cu
transformer_engine/common/fused_attn/utils.h
transformer_engine/common/include/transformer_engine/transformer_engine.h
transformer_engine/jax/csrc/extensions/attention.cpp

This PR updates the data type of the ragged offset tensors, e.g. [offset_q](https://github.com/NVIDIA/TransformerEngine/blob/3b89c36f0e7427199e4e87076b8a5e1545d70346/transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu#L144), in the THD path of cuDNN attention. For long sequences, these offset tensors could have `int32` overflow. This PR updates them to `int64` for cuDNN 9.5+.
Add logic to determine if cuDNN 9.5+ is available to support 64-bit offset.

Fused Attention Support 64-bit Ragged Offsets for Large THD Tensors

---

examples/jax/encoder/common.py
examples/jax/encoder/test_model_parallel_encoder.py
examples/jax/encoder/test_multigpu_encoder.py
examples/jax/encoder/test_multiprocessing_encoder.py
examples/jax/encoder/test_single_gpu_encoder.py
qa/L0_jax_unittest/test.sh

V100 doesn't have BF16 hardware support, this PR is to skip the V100 failing tests with BF16 data type.
- Skip all encoder tests if the CC < 80

[JAX] Skip V100 encoder tests

---

transformer_engine/paddle/csrc/custom_ops.cu

We have experienced compilation errors when building with Paddle 3.0 since they've changed some type names in their CUDA graph infrastructure (see https://github.com/PaddlePaddle/Paddle/pull/62832).
Pinging @eee4017
- Update type names for Paddle 3.0

[Paddle] Update type names for Paddle 3.0

---

transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/module/grouped_linear.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

https://github.com/NVIDIA/TransformerEngine/pull/1191 added a fast accessor for params to work around CPU overheads from how PyTorch modules store params. This saves ~1 us per forward pass (out of a total ~100 us) in small benchmarks with the linear layer. However, we have experienced some problems with FSDP since it internally replaces the params with a flattened param and turns the original params into a plain tensor. The fast accessor was very hacky, and this edge case makes me think it's not worth the performance benefit.
- Remove fast param accessor in TE modules

[PyTorch] Remove fast param getter from modules

---

tests/pytorch/test_fused_optimizer.py
transformer_engine/pytorch/csrc/extensions/multi_tensor/multi_tensor_adam.cu
transformer_engine/pytorch/optimizers/fused_adam.py

Add options to set the dtypes of master weights, exp_avg and exp_avg_sq of FusedAdam.
- Support using fp32/fp16 master weights
- Support using fp32/fp16/fp8 exp_avg
- Support using fp32/fp16/fp8 exp_avg_sq

Support using fp16 master weights and fp16/fp8 optimizer states in FusedAdam

---

transformer_engine/jax/cpp_extensions/attention.py

`bool(os.getenv("NVTE_JAX_FUSED_ATTN_WITH_FFI", "0"))` returns `True` which is unwanted.
- Change A
- Change B

[JAX] Fix for Disable FusedAttn with FFI by default

---

transformer_engine/pytorch/module/base.py

Fix for multi-domain code path in `te.module.base.initialize_ub()` missing a list of intra-domain ranks for info printout (not used functionally).
- Added missing variable when initializing Userbuffers.

[PyTorch] Missing intra-domain ranks list when initializing Userbuffers with data parallelism

---

tests/jax/test_distributed_fused_attn.py
transformer_engine/jax/attention.py
transformer_engine/jax/flax/transformer.py

Surface the context parallelism parameters to the JAX `DotProductAttention` API
- added the required 2 CP configs to the high level jax DPA api
- removed the `is_context_parallel` arg from `is_fused_attn_available(). 
- removed the attention mask check for CP from `is_fused_attn_available()`. The `check_supported()` inside `_FusedAttnCPWithAllGatherHelper` essentially performs the check
- fixed the `test_distributed_fused_attn` accordingly by removing the last arg related to `is_context_parallel` flag from `is _fused_attn_available()` api calls

[JAX] Expose cp params to jax DPA api

---

transformer_engine/jax/cpp_extensions/normalization.py
transformer_engine/jax/csrc/extensions.h
transformer_engine/jax/csrc/extensions/normalization.cpp
transformer_engine/jax/csrc/extensions/pybind.cpp

This PR introduced the following primitives implemented with the new custom calls:
* `LayerNormForwardFFI`
* `RmsNormFwdPrimitive`
* `RmsNormFwdFp8Primitive`
* `RmsNormBwdPrimitive`
All primitives in `transformer_engine/jax/cpp_extensions/normalization.py` support FFI call after this PR.

[TE/JAX] XLA FFI calls for layer norm and RMS norm

---

qa/L0_jax_unittest/test.sh

There was a segfault issue on XLA, so we temporary disabled the deterministic flag in https://github.com/NVIDIA/TransformerEngine/pull/1262. XLA recently fixed the issue in https://github.com/openxla/xla/pull/18766, so it is good to add back that flag now.
Add `--xla_gpu_deterministic_ops` to have run-to-run deterministic to have the stable CI results

[JAX] Add back the xla deterministic flag

---

tests/jax/test_custom_call_compute.py
transformer_engine/jax/cpp_extensions/transpose.py
transformer_engine/jax/csrc/extensions.h
transformer_engine/jax/csrc/extensions/activation.cpp
transformer_engine/jax/csrc/extensions/pybind.cpp
transformer_engine/jax/csrc/extensions/transpose.cpp
transformer_engine/jax/layernorm_mlp.py

This PR introduced the following primitives implemented with the new custom calls:
* `DBiasCastTransposePrimitive`
* `DActLuDBiasCastTransposePrimitive`
* `DgatedActLuCastTransposePrimitive`

[TE/JAX] XLA FFI calls for three cast transpose functions

---

transformer_engine/common/CMakeLists.txt
transformer_engine/common/cudnn_utils.cpp
transformer_engine/common/include/transformer_engine/cudnn.h
transformer_engine/jax/cpp_extensions/attention.py
transformer_engine/jax/cpp_extensions/custom_call.py
transformer_engine/jax/csrc/extensions.h
transformer_engine/jax/csrc/extensions/cudnn.cpp
transformer_engine/jax/csrc/extensions/ffi.h
transformer_engine/jax/csrc/extensions/pybind.cpp

In this PR, the FusedAttnForwardFFI is registered to XLA via 2 phases:
1. `prepare` where the `te_cudnn_handle_init_ffi` is called.
2.  `execute` phase where the actual fused attention function is called.
In the past, the default was to have only the `execute` phase.
This helps to avoid memory allocation for the handle in the cudaGraph capturing area, thus resolving the issue we have in the distributed run with cudaGraph.
In general, all the custom calls that involve cuDNN kernels should be registered with these two phases in the future. Since the prepare function needs to have the same function argument list with the execute function ones, variadic args are used to make this `te_cudnn_handle_init_ffi` general so that it can be called in any custom calls.

[JAX] Added prepare phase for the FusedAttnForwardFFI

---

transformer_engine/jax/csrc/extensions/activation.cpp

Clang (18.1.8 on my system) errors on building the jax native extension without these explicit casts.
- Add a pair of `static_cast`s

Fix an int conversion error

---

transformer_engine/pytorch/ops/op.py

https://github.com/NVIDIA/TransformerEngine/pull/1063 added logic so that TE ops include FP8 scaling factors in checkpoints by implementing the `get_extra_state`/`set_extra_state` functions. When running without FP8, it sets the extra state to `None`. However, ONNX export assumes that the extra state is a tensor and it fails when calling the `detach` function:
https://github.com/pytorch/pytorch/blob/d3788190685685cb828bdf6bed90270c0b60affc/torch/jit/_trace.py#L81
This PR changes the checkpointing logic so that the ops return an empty tensor if FP8 is not enabled.
The TE modules work around this issue by having a separate code path when ONNX export is enabled: https://github.com/NVIDIA/TransformerEngine/blob/e5ffaa7696092bfa2d8a8973024a26e1655e4353/transformer_engine/pytorch/module/base.py# …

[PyTorch] Fix ONNX export bug with operation-based API

---

transformer_engine/pytorch/attention.py

The torch autograd functions for attention with context parallelism incorrectly make multiple calls to `ctx.saved_tensors` in backward pass resulting in the following error:
```
Unpack is being triggered for a tensor that was already unpacked once. If you are calling ctx.saved_tensors in backward, make sure to do so only once. Otherwise please open an issue with details on your use case.
```
- Call `ctx.saved_tensors` exactly once before unpacking into separate variables

[PyTorch] Fix multiple calls to saved_tensors in CP attention

---

transformer_engine/common/CMakeLists.txt

Calculate the path to `cudnn-frontend` as a relative path from `transformer_engine/common/CMakeLists.txt`, rather than a relative path from the directory specified to the `cmake` command.
This will allow other CMake projects to use TransformerEngine as a sub-project (e.g., by adding `add_subdirectory(third_party/TransformerEngine/transformer_engine/common)` in their CMakeLists.txt) to build TransformerEngine as a part of their build.
- Use CMAKE_CURRENT_SOURCE_DIR instead of CMAKE_SOURCE_DIR
- Display CUDNN_FRONTEND_INCLUDE_DIR on error

Use `CMAKE_CURRENT_SOURCE_DIR` instead of `CMAKE_SOURCE_DIR`

---

transformer_engine/pytorch/attention.py

This PR fixes the error message for GQA when the key/value shape does not match what's expected.
- Replace `num_gqa_groups` with `num_gqa_groups_per_partition` in GQA error message.

[PyTorch] Fix GQA error message

---

qa/L1_pytorch_mcore_integration/test.sh
qa/L1_pytorch_mcore_integrationtest/test.sh
transformer_engine/pytorch/module/layernorm.py
transformer_engine/pytorch/module/rmsnorm.py
transformer_engine/pytorch/ops/basic/layer_norm.py
transformer_engine/pytorch/ops/basic/rmsnorm.py
transformer_engine/pytorch/ops/fuser.py

https://github.com/NVIDIA/TransformerEngine/pull/1033 broke Megatron-LM's wrappers for the LayerNorm and RMSNorm modules:
- We renamed the `hidden_size` arg to `normalized_shape` in order to match [`torch.nn.LayerNorm`](https://pytorch.org/docs/stable/generated/torch.nn.LayerNorm.html), but Megatron-LM treats `hidden_size` as a kwarg:
https://github.com/NVIDIA/Megatron-LM/blob/aded519cfb1de2abf96f36ca059f992294b7876f/megatron/core/extensions/transformer_engine.py#L65.
This PR adds logic to handle the `hidden_size` arg and print a deprecation warning.
- Megatron-LM has the option to initialize modules in CPU, but TE's LayerNorm and RMSNorm ops assume they are initialized on GPU. This PR allows LayerNorm and RMSNorm ops to be initialized on CPU, although it still assumes it is transferred …

[PyTorch] Integration test for Megatron-LM

---

tests/cpp/util/test_string.cpp
transformer_engine/common/util/string.h

This PR adds a C++ utility function that can convert some C++ containers (mainly `vector`) to a string. This can be used to generate more descriptive error messages:
```c++
NVTE_CHECK(in.shape == out.shape,
"Input dims ", in.shape, " and output dims ", out.shape, " do not match");
// Assertion failed: in.shape == out.shape, Input dims (2,4) and output dims (8) do not match
```
- Add C++ utility function to convert container to string

[Core] Add function to convert container to string

---

transformer_engine/pytorch/distributed.py
transformer_engine/pytorch/fp8.py
transformer_engine/pytorch/graph.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

Different from non-MoE models like llama2, MoE models have dynamic shaped activations in FFN layers, so one cudagraph can only capture a part of one transformer layer, instead of covering the whole layer. We call this a "breaking-layer" cudagraph mode. This PR adds breaking-layer cudagraph supports for MoE models on the TE side, and fixes several related bugs in TE.
- Add `is_initialized()` method in CudaRNGStatesTracker to align with what is already done in MCore.
- Fix wrong `per_callable_module_params` order bug in `_make_graphed_callables` when `_order` is given.
- Fix warmup argument mismatch bug in `_make_graphed_callables` when `_order` is given.
- Fix fp8 accuracy issue by adding `fp8_group` argument to …

Support CUDA Graph for MoE models

---

.github/workflows/build.yml
transformer_engine/common/CMakeLists.txt
transformer_engine/common/fused_attn/thd_utils.cu
transformer_engine/common/fused_attn/thd_utils.h
transformer_engine/pytorch/csrc/extensions/attention.cu

Moves several kernels that are used for context parallelism + THD fused attention to shared location so they can be called by Jax and other frameworks.
Moves common code out of pytorch filder.

[Common] Moved framework agnostic THD kernels to common.

---

tests/jax/test_distributed_fused_attn.py

Avoids running with tiny sequence lengths when CP size is large in the Jax distributed fused attention tests.
Update unit test to scale sequence length by CP size.

[JAX] Scale sequence length in CP tests to avoid tiny sizes.

---

tests/pytorch/fused_attn/run_fused_attn_with_cp.py
transformer_engine/pytorch/attention.py

Fix qkv_format setting in DotProductAttention.
Use padding mask type for flash attention with THD format in CP unit tests.

Fix attention mask type for Flash Attention + CP + THD

---

transformer_engine/jax/praxis/module.py
transformer_engine/jax/praxis/transformer.py

This PR addresses an issue caused by using mutable default values in dataclass fields, which can lead to unexpected behavior. More details are available in the [official documentation](https://docs.python.org/3/library/dataclasses.html#mutable-default-values).
Starting with Python 3.11, an explicit error is raised when mutable values are used as default values in dataclass fields. To resolve this, the default_factory parameter is now used as recommended in the [documentation](https://docs.python.org/3/library/dataclasses.html#mutable-default-values:~:text=Using%20default%20factory%20functions%20is%20a%20way%20to%20create%20new%20instances%20of%20mutable%20types%20as%20default%20values%20for%20fields%3A). This approach ensures that new instances of mutable types are created for each …

[JAX] Use default factory for not sharing mutable default values

---

transformer_engine/common/normalization/common.h
transformer_engine/jax/cpp_extensions/normalization.py
transformer_engine/jax/csrc/extensions/pybind.cpp

- Added CudnnHandlerInit into the `prepare` phases of normalization custom calls. 
- Make `NormalizationPlanRegistry` `thread_local`.
These changes should fix the failures in `test_distributed_layernorm.py`.

[JAX] Bug fix for distributed normalization

---

transformer_engine/jax/cpp_extensions/activation.py
transformer_engine/jax/cpp_extensions/base.py
transformer_engine/jax/cpp_extensions/normalization.py
transformer_engine/jax/cpp_extensions/softmax.py
transformer_engine/jax/csrc/extensions/pybind.cpp

Softmax FFIs with correct Encapsulates

[JAX] Bug Fix: Softmax FFIs with correct Encapsulates

---

transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu

This PR adds `max_t` support for KV when `qkv_format=thd`. This helps reduce the memory usage for MQA/GQA + THD cases.
- Add max_t for KV for THD

[common] Add max_t support for KV in THD

---

tests/pytorch/test_float8tensor.py
tests/pytorch/test_sanity.py
tests/pytorch/test_torch_save_load.py

This PR adds `weights_only=False` to `torch.load()` calls to future-proof PyTorch unit tests.
- Add weights_only=False for torch.load

[PyTorch] Add weights_only=False for torch.load

---

qa/L0_pytorch_unittest/test.sh
tests/jax/test_fused_attn.py
tests/pytorch/fused_attn/test_fused_attn.py
tests/pytorch/fused_attn/test_fused_attn_with_cp.py
transformer_engine/common/fused_attn/fused_attn.cpp
transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu
transformer_engine/pytorch/attention.py

This PR adds SWA (left, 0) support to the `FusedAttention` backend for {`bshd`, `sbhd`, `thd`} formats and {`no_mask`, `causal`, `causal_bottom_right`, `padding`, `padding_causal`, `padding_causal_bottom_right`} masks.
Previously, the support was only for SWA (left, 0) with {`bshd`, `sbhd`} formats, and {`no_mask`, `causal`} mask.
This PR requires cudnn-frontend 1.9.
- Add cuDNN SWA (left, 0) + padding + bottom right causal

[common/PyTorch] Add cuDNN SWA (left, 0) + padding + bottom right causal

---

tests/jax/test_fused_attn.py
tests/jax/utils.py
transformer_engine/jax/attention.py
transformer_engine/jax/flax/transformer.py

- Adds THD + SWA unit tests
- Generalizes make_swa_mask by accepting pos_q and pos_kv instead of seqlen, making it work for THD/non-THD and both top-left and bottom-right alignments.
- Previously, make_swa_mask took seqlen and relied on an attn_mask_type (e.g., CAUSAL_MASK or CAUSAL_BOTTOM_RIGHT_MASK) to differentiate top-left vs. bottom-right alignments.
- Now, by providing pos_q and pos_kv directly, we can generate the same patterns without a separate attn_mask_type.
For examples, consider non-THD case with q_seqlen=2, kv_seqlen=4.
In the past, we can pass q_seqlen=2, kv_seqlen=4, attn_mask=AttnMaskType.CAUSAL_BOTTOM_RIGHT_MASK for bottom-right alignment, window_size=(-1, 0), which generates mask like
```
1 1 1 0
1 1 1 1
```
And passing attn_mask=AttnMaskType.CAUSAL_MASK for top-left …

[JAX] Add THD + SWA unit tests

---

transformer_engine/pytorch/module/layernorm_mlp.py

the current implementation would release the output of ln, leading to an error if setting `return_layernorm_output=True`.
The current implementation would release the output of ln, leading to an error if setting `return_layernorm_output=True`.
- check `return_layernorm_output` before `lear_tensor_data(ln_out_total)`

bug fix for using `return_layernorm_output=True`

---

tests/jax/test_distributed_fused_attn.py
transformer_engine/jax/cpp_extensions/attention.py

The original implementation of ring attention applied output correct after generating all partial outputs from ring attention. This consumes large amounts of memory when CP degree is large so instead we update the output eagerly after each step.
Update output and softmax_aux after each step of ring attention.

[JAX] Correct fused attention output after each step of ring attention

---

transformer_engine/common/fused_attn/thd_utils.h
transformer_engine/pytorch/attention.py
transformer_engine/pytorch/csrc/extensions.h
transformer_engine/pytorch/csrc/extensions/attention.cu

Fused attention has [token count quantization](https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/common/fused_attn/utils.cu#L480-L496). This can make T of `sfotmax_lse` mismatch with Q and O. For example, both T=1000 and T=500 will create T=1024 in `softmax_lse`, so we cannot assume half of T will have 2x smaller shape of `softmax_lse.` Fix CP results correction by taking this quantization into consideration.

Take token count quantization of fused attention into consideration for CP results correction

---

examples/jax/encoder/common.py
examples/jax/encoder/conftest.py
examples/jax/encoder/run_test_multiprocessing_encoder.sh
examples/jax/encoder/test_multiprocessing_encoder.py
qa/L0_jax_distributed_unittest/test.sh

Using the `multithreading` module which uses `os.fork()` with JAX which is already multithreading can lead to deadlocks and is not recommended.
This PR removed the usage of `multithreading`, but spawning processes in a bash script helper.

[JAX] Test_multiprocessing_encoder with process spawn in bash

---

tests/pytorch/distributed/run_layer_with_overlap.py
tests/pytorch/distributed/test_comm_gemm_overlap.py
transformer_engine/pytorch/module/linear.py

`te.Linear` currently only supports TP overlap with `parallel_mode="row"` where it overlaps reduce-scatter in the forward pass, and all-gather with dgrad in the backward pass.
This PR adds new options to enable all-gather overlap in the forward pass, and reduce-scatter overlap with dgrad in the backward pass, when `parallel_mode="column"`.
Fixes #1312

[PyTorch] Adding TP overlap support for `te.Linear` with `parallel_mode="column"`

---

setup.py
transformer_engine/common/CMakeLists.txt

Make it an option to compile activation functions with fast math. By default it's off and the activation kernels won't be compiled with fast math, which is consistent with previous behavior.
- Change A
- Change B

Make it an option to compile activation functions with fast math

---

tests/jax/distributed_test_base.py
tests/jax/test_distributed_fused_attn.py
tests/jax/test_fused_attn.py

Consolidate test code for distributed fused attention to used FusedAttnRunner so we can share the logic that generates the sequences and masking.
Updates to fused attention tests.

[JAX] Consolidate the distributed fused attention test code

---

transformer_engine/pytorch/attention.py

`DotProductAttention` calls `get_attention_backend()` to choose an appropriate backend for a given `AttentionParams`. This call is CPU intensive and is only called when `attention_params != _attention_backends["attention_params"]`. For FP8, there are a number of entries in `AttentionParams.fp8_meta`, for example, `fp8_meta["scaling_fwd"]`, but what's really important is `fp8_meta["recipe"]`. This PR overwrites the `__eq__` function of `AttentionParams` to only compare the recipe entry for FP8 configs.
Before this PR, `NVTE_DEBUG=1 NVTE_DEBUG_LEVEL=1 pytest -o log_cli=true --log-cli-level=INFO -s -v tests/pytorch/test_sanity.py::test_sanity_attention_extra_state[dtype0-large]` produces:
```
INFO     DotProductAttention:attention.py:8245 Running with FusedAttention backend (sub-backend 2) …
```

[PyTorch] Fix AttentionParams comparison logic

---

transformer_engine/pytorch/ops/fuser.py

We have recently experienced some esoteric errors in the LayerNorm backward pass:
```
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/_tensor.py", line 626, in backward
[rank0]:     torch.autograd.backward(
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/autograd/__init__.py", line 347, in backward
[rank0]:     _engine_run_backward(
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py", line 823, in _engine_run_backward
[rank0]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py", …
```

[PyTorch] Avoid `parameters` function in op backward pass

---

tests/jax/test_distributed_fused_attn.py
tests/jax/test_fused_attn.py
transformer_engine/jax/attention.py
transformer_engine/jax/cpp_extensions/attention.py
transformer_engine/jax/csrc/extensions/attention.cpp

This PR adds `segment_ids/pos` limited support and deprecated `fused_attn_thd` API.
- Add a new `SequenceDescriptor` class for different sequence descriptions scenario.
- `from_seqlens` for non-THD
- `from_seqlens_and_offsets` for THD
- `from_segment_ids_and_pos` for THD + ring attn (haven't implemented)
- Change the old `fused_attn` `mask` parameter to `SequenceDescriptor`. Passing `mask` in the position argument will work for a while but generating deprecation warning.
- Deprecate `fused_attn_thd` API as the refactored `fused_attn` can also support THD format.
- Remove small inputs in `test_fused_attn.py` as the long sequence inputs should cover.
- Add different sequence inputs tests in `test_fused_attn.py`

[JAX] Support segment_ids/pos as FA inputs

---

docs/api/pytorch.rst
tests/pytorch/test_permutation.py
transformer_engine/pytorch/__init__.py
transformer_engine/pytorch/permutation.py
transformer_engine/pytorch/triton/__init__.py
transformer_engine/pytorch/triton/permutation.py

Add mask-based token permutation and local chunk permutation fused kernels. These kernels are implemented with OpenAI Triton.
Related commit in Megatron-LM https://github.com/NVIDIA/Megatron-LM/commit/ac0474d26e8d8688b950704ea58d14858c9d047f
- Non-breaking API changes in `te.pytorch.permutation.moe_permute` and `te.pytorch.permutation.moe_unpermute`
- Add new APIs of `te.pytorch.permutation.moe_sort_chunks_by_indices`

[MoE][PyTorch] Add mask-based MoE permutation

---

transformer_engine/pytorch/attention.py

This function is more accurate than torch.log() for small values of input - https://pytorch.org/docs/stable/generated/torch.log1p.html
Found with TorchFix https://github.com/pytorch-labs/torchfix/

Use log1p(x) instead of log(1+x)

---

qa/L1_pytorch_distributed_unittest/test.sh
transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/module/grouped_linear.py
transformer_engine/pytorch/ops/basic/basic_linear.py
transformer_engine/pytorch/ops/fused/userbuffers_backward_linear.py
transformer_engine/pytorch/ops/fused/userbuffers_forward_linear.py

Fix some minor linter warnings. In particular, suppress warnings from Userbuffers support in operation-based API, which will not be functional in TE 2.0.
- Fix minor linter warnings
- Add warnings in Userbuffers implementation in operation-based API
- Disable test for Userbuffers support in operation-based API

[PyTorch] Fix linter warnings

---

tests/cpp/run_norm_tests.sh
transformer_engine/pytorch/module/_common.py

Adds a path via envvar to disable cudnn-norms for MXFP8
- Fix envvar used for CPP norm tests.
- Add `NVTE_CUDNN_MXFP8_NORM` env to disable cudnn-norms.

Add path to disable cudnn norm for mxfp8

---

transformer_engine/pytorch/ops/basic/basic_linear.py

As part of the 2.0 refactor, we exposed quantizers in the functional linear API (`BasicLinear._functional_forward`/`BasicLinear._functional_backward`). These functions internally set the quantizer usages so that the GEMMs have the data they need, but I didn't consider a case where the weight quantizer has an extra usage (i.e. so we can cache it for the backward pass). This PR modifies the functional linear API so it only sets the required usages and doesn't wipe out any user-provided usages.
- Respect existing quantizer usages in functional linear API

[PyTorch] Respect existing quantizer usages in functional linear API

---

README.rst

Followup PR to https://github.com/NVIDIA/TransformerEngine/pull/587
As of https://github.com/EleutherAI/gpt-neox/pull/1282, we've completed TE integration into gpt-neox!

Update neox to completed

---

transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/tensor/float8_tensor.py
transformer_engine/pytorch/tensor/mxfp8_tensor.py

[NeMo's distributed optimizer](https://github.com/NVIDIA/NeMo/blob/main/nemo/core/optim/distributed_adam.py) interacts with the internals of `Float8Tensor` in order to perform FP8 casts. While debugging in https://github.com/NVIDIA/NeMo/pull/12004, I've also fixed some miscellaneous bugs in the quantized tensors.
- Avoid internal quantized tensor class when creating params or setting `data` attr
- Debug `MXFP8Tensor` views

[PyTorch] Debug NeMo distributed optimizer

---

tests/pytorch/distributed/run_numerics.py
tests/pytorch/distributed/test_fusible_ops.py
tests/pytorch/test_cuda_graphs.py
tests/pytorch/test_fusible_ops.py
tests/pytorch/test_numerics.py
transformer_engine/common/recipe/__init__.py
transformer_engine/pytorch/fp8.py
transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/module/grouped_linear.py
transformer_engine/pytorch/ops/op.py

Rename `BlockScaling` recipe to `MXFP8BlockScaling`

Rename block scaling recipe

---

transformer_engine/pytorch/distributed.py

https://github.com/NVIDIA/TransformerEngine/pull/1431 added padding to MXFP8 scale-inverses to satisfy alignment requirements in MXFP8 kernels. However, we didn't properly handle the padding in tensor-parallel all-gathers. This PR makes sure to remove padding when necessary.
- Remove MXFP8 scale-inv padding in MXFP8 all-gather

[PyTorch] Remove MXFP8 scale-inv padding in MXFP8 all-gather

---

transformer_engine/pytorch/csrc/extensions/normalization.cpp

cuDNN MXFP8 normalization does not support the strided scaling factors.
- Change A
- Change B

Fix MXFP8 normalization

---

tests/cpp/operator/test_act.cu
tests/cpp/operator/test_cast.cu
tests/cpp/operator/test_cast_dbias.cu
tests/cpp/operator/test_cast_dbias_dgelu.cu
tests/cpp/operator/test_cast_gated_swiglu.cu
tests/cpp/operator/test_cast_mxfp8.cu
tests/cpp/operator/test_cast_mxfp8_gated_swiglu.cu
tests/cpp/operator/test_cast_transpose.cu
tests/cpp/operator/test_cast_transpose_dbias.cu
tests/cpp/operator/test_cast_transpose_dbias_dgelu.cu
tests/cpp/operator/test_cast_transpose_dgeglu.cu
tests/cpp/operator/test_causal_softmax.cu
tests/cpp/operator/test_dequantize_mxfp8.cu
tests/cpp/operator/test_multi_cast_transpose.cu
tests/cpp/operator/test_multi_padding.cu
tests/cpp/operator/test_normalization.cu
tests/cpp/operator/test_normalization_mxfp8.cu
tests/cpp/operator/test_qdq.cu
tests/cpp/operator/test_swizzle.cu
tests/cpp/operator/test_transpose.cu
tests/cpp/test_common.cu
tests/cpp/test_common.h
transformer_engine/common/activation/activation_template.h
transformer_engine/common/util/cast.cu
transformer_engine/common/util/cast_kernels.cuh

This PR supersedes PR #1460. There was a bug introduced in the dActivation kernels for Blackwell where the activation input and the gradient input were swapped. This uncovered the issue with the tests, where different tensors were seeded with the same values.
- Properly seed the tensors in C++ tests
- Fix the dActivation logic

Fix dActivation

---

transformer_engine/jax/cpp_extensions/attention.py
transformer_engine/jax/dot.py
transformer_engine/jax/flax/module.py
transformer_engine/jax/flax/transformer.py

Issue #1451 pointed out that TE Flax modules initialize all params with the `dtype=jnp.float32` and ignore the `module.dtype`. This PR introduced the fixes for that.
In addition, unnecessary reshape ops were removed. 

[JAX] Flax module init with a given dtype

---

transformer_engine/pytorch/attention.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/linear.py
transformer_engine/pytorch/utils.py

Adds NVTX ranges to categorize different parts of the execution.
- Change A
- Change B

Add NVTX ranges to categorize execution

---

tests/pytorch/test_numerics.py
transformer_engine/pytorch/csrc/extensions/gemm.cpp
transformer_engine/pytorch/module/grouped_linear.py

`at::from_blob` cannot create CUDA tensors with `nullptr`, otherwise it will throw the error
```
RuntimeError: The specified pointer resides on host memory and is not registered with any CUDA device.
```
- Change A
- Change B

Fix a bug for D being nullptr in grouped gemm

---

transformer_engine/jax/flax/module.py
transformer_engine/jax/flax/transformer.py

[UPDATED] PR #1472 caused convergence issues in MaxText. 
MaxText has `weight_dtype` as the data type of the parameters and `dtype` as the compute type, whereas the current TE only has `dtype`.
This PR adds the `weight_dtype` as an optional arg with default value `jnp.float32`.

[JAX] Flax params initialization with weight_dtype

---

transformer_engine/jax/cpp_extensions/attention.py
transformer_engine/jax/flax/transformer.py

Expose THD format to the flax module to allow DotProductAttention module to use THD format.
- Rename mask to sequence_descriptor for DotProductAttention module while maintaining the compatibility but generating a warning.
- The renamed sequence_descriptor accepts new SequenceDescriptor API for different kind of sequence representation
- [ x New and existing unit tests pass locally with my changes

[JAX] Expose THD format to the flax module

---

examples/jax/encoder/test_model_parallel_encoder.py
examples/jax/encoder/test_multigpu_encoder.py
examples/jax/encoder/test_multiprocessing_encoder.py
examples/jax/encoder/test_single_gpu_encoder.py
examples/jax/mnist/test_single_gpu_mnist.py
tests/jax/test_distributed_layernorm_mlp.py
tests/jax/test_layer.py
tests/jax/utils.py
transformer_engine/jax/flax/module.py
transformer_engine/jax/flax/transformer.py

Flax modules should use `dtype` to initialize their parameters while the compute type should depend on the input data type. 
This PR adds the capability to infer the compute type from the input type.

[JAX] Flax with compute dtype inferred from input dtype. 

---

tests/pytorch/test_numerics.py
transformer_engine/pytorch/module/grouped_linear.py

Due to the wrong indent, the wgrad computation is not called when `ctx.fuse_wgrad_accumulation == True`.
Also update the test to cover this case.
- Change A
- Change B

[PyTorch] Fix fuse_wgrad_accumulation for GroupedLinear

---

tests/pytorch/distributed/test_torch_fsdp2.py
transformer_engine/pytorch/ops/_common.py
transformer_engine/pytorch/utils.py

TE sequential currently uses some newer PyTorch APIs that were introduced in v2.4.3 which break execution for older versions.
Fixes #1473 
- Restore PyTorch compatibility for operations API for versions 2.4.2 and lower.
- Move `get_torch_version` from the FSDP test file to utils.

Fix TE ops API compatibility with PyTorch versions < 2.4.3

---

transformer_engine/common/fused_attn/fused_attn.cpp
transformer_engine/pytorch/attention.py

This PR fixes two things:
- allow flash-attn 2.7.4 to run on sm100+, and allow head_dim=256 on sm100+
- include sm120 in certain sm100+ restrictions that were left out (related to head_dim and bottom right causal mask)
See above.

Minor fixes for attention

---

transformer_engine/common/common.cu
transformer_engine/common/common.h
transformer_engine/common/util/cast_kernels.cuh

Added memory alignment check to `cast_fp8_1D` kernels which use TMA, but do not explicitly use tensor descriptors (TMA alignment requirement of tensors was not checked).

Added memory alignment check to cast_fp8_1D

---

tests/pytorch/fused_attn/test_fused_attn_with_cp.py

Some tests in [`test_fused_attn_with_cp.py`](https://github.com/NVIDIA/TransformerEngine/blob/main/tests/pytorch/fused_attn/test_fused_attn_with_cp.py) require 4 GPUs and they fail on nodes with 2 GPUs. This PR only runs tests if there are enough available GPUs.
- Skip context parallelism tests if not enough GPUs

[PyTorch] Skip context parallelism tests if not enough GPUs

---

transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers.cu

Vectorized load/store for p2p-based ReduceScatter overlap.
- Vectorize the loads/stores of local reduction after TP ReduceScatter for (1) FP8 comm > FP32 reduce > BF16 out, (2) BF16 comm > FP32 reduce > BF16 out

Support vectorized local reduction for p2p-based ReduceScatter overlap

---

tests/pytorch/test_float8tensor.py
transformer_engine/pytorch/tensor/float8_tensor.py
transformer_engine/pytorch/tensor/quantized_tensor.py

In functions such as `split`, `chunk` etc. in which the shape of the input and output differs, the returned tensor is correct but with the incorrect shape which leads to bugs, e.g. in FSDP2 or checkpoint loading. A small repro:
```
import torch
from transformer_engine.pytorch.tensor.float8_tensor import Float8Quantizer
import transformer_engine_torch as tex
t = torch.randn(4, 4)
quantizer = Float8Quantizer(
scale=torch.full([1], 1.0, dtype=torch.float32, device="cuda"),
amax=torch.empty([1], dtype=torch.float32, device="cuda"),
fp8_dtype=tex.DType.kFloat8E4M3,
)
x = quantizer(t.cuda())
a, b = x.chunk(2, dim=0)
print(x.shape, a.shape, b.shape)
print(x, a, b)
``` 
- If data

Fix shape of new quantized tensor in `make_like`

---

qa/L0_pytorch_unittest/test.sh
setup.py
tests/pytorch/distributed/test_torch_fsdp2.py
transformer_engine/pytorch/__init__.py
transformer_engine/pytorch/attention.py
transformer_engine/pytorch/jit.py
transformer_engine/pytorch/ops/_common.py
transformer_engine/pytorch/utils.py

Enforce torch version 2.1 as the minimum required. See #1512 
- Enforce minimum torch version 2.1.
- Enable `torch.compile` for fused attention tests.
- Disables torch.compile fully when `NVTE_TORCH_COMPILE` is 0.

Enforce PyTorch version 2.1 and run attention tests with torch.compile

---

transformer_engine/pytorch/module/layernorm.py
transformer_engine/pytorch/module/rmsnorm.py

https://github.com/NVIDIA/TransformerEngine/pull/1033 introduced a bug with Mcore integration: the LayerNorm or RMSNorm modules might not set the `sequence_parallel` attr in its params, which is used in Mcore sequence parallelism.
- Set flags in norm modules for Mcore sequence-parallel support

[PyTorch] Set flags in norm modules for Mcore sequence-parallel support

---

tests/jax/test_distributed_fused_attn.py
tests/jax/test_fused_attn.py
transformer_engine/jax/attention.py
transformer_engine/jax/cpp_extensions/attention.py
transformer_engine/jax/csrc/extensions/attention.cpp

Support P2P context parallel (ring attn) with THD format. This feature is only available for self attn + causal + segment_ids/pos + load balancing (reorder before the attn and inverse-reorder after the attn).
- Refactor reorder/inverse_reorder_causal_loading_balancing API to support different reorder strategy.
- Support P2P context parallel. The limitations are list above.
- Reduce the number of test configs of `kv_groups` in `test_distributed_fused_attn`
- Use `AttnBiasType`, `AttnMaskType`, `QKVLayout` in cpp_extenion/attention.py for maintaining the readibility.

[JAX] THD ring attention

---

transformer_engine/common/util/cast_kernels.cuh

Removed tensor boundary checks in MXFP8 kernels for amax computation in non-activation kernels, as they do not affect results for zero inputs. Slightly improves performance.

[common] Removed tensor boundary checks in MXFP8 kernels

---

qa/L0_pytorch_unittest/test.sh

Runs the [TE integration test](https://github.com/Lightning-AI/lightning-thunder/blob/fb7a8714513a18ffd322a28db86e9c8e6baf710e/thunder/tests/test_transformer_engine_executor.py) from [lightning-thunder](https://github.com/Lightning-AI/lightning-thunder) as a sanity check.
- Introduces the integration test for `lightning-thunder`.

Add sanity test for lightning-thunder integration

---

examples/pytorch/comm_gemm_overlap/te_layer_with_overlap.py
tests/pytorch/distributed/run_gemm_with_overlap.py
tests/pytorch/distributed/run_layer_with_overlap.py
transformer_engine/common/CMakeLists.txt
transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers-host.cpp
transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers.cu
transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers.h
transformer_engine/common/util/cuda_driver.cpp
transformer_engine/common/util/cuda_nvml.cpp
transformer_engine/common/util/cuda_nvml.h
transformer_engine/common/util/shared_lib_wrapper.h
transformer_engine/pytorch/csrc/extensions.h
transformer_engine/pytorch/csrc/extensions/comm_gemm_overlap.cpp
transformer_engine/pytorch/csrc/extensions/pybind.cpp
transformer_engine/pytorch/module/base.py

- Register UB buffers with Multi-Node NVLink when possible.
- Remove logic for the inter-node communicator setup which was never used in TE, therefore being dead code.
This helps with removing the assumption that a NVLINK domain is a single node and that NVLINK domain sizes need to be symmetric in a job. AKA with DP4-TP16, the cluster orchestrator can allocate 4x 16-GPU NVLINK domains but also 1x 32-GPU NVLINK domain + 2x 160GPU NVLINK domains for example.
This removes the hostname exchange which is not valid for kubernetes env running one container per process/gpu.
- Support for TP across multi-node NVLINK.

Add support for UB MNNVL

---

transformer_engine/jax/__init__.py
transformer_engine/pytorch/__init__.py
transformer_engine/pytorch/attention.py

Currently transformer_engine is writing to the root logger upon import, which implicitly initializes the root logger preventing downstream applications from controlling it effectively. 
For further motivation on why the root logger should not be used by a library see https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library
> Note It is strongly advised that you do not log to the root logger in your library. Instead, use a logger with a unique and easily identifiable name, such as the __name__ for your library’s top-level package or module. Logging to the root logger will make it difficult or impossible for the application developer to configure the logging verbosity or handlers of your library as they wish.
This PR addresses this problem by ensuring all logging calls …

Don't touch nor send messages to the root logger.

---

qa/L0_pytorch_unittest/test.sh
qa/L1_pytorch_thunder_integration/test.sh

This moves the Lightning-Thunder integration test (added in https://github.com/NVIDIA/TransformerEngine/pull/1531) to a standalone L1 test. This test isn't a core TE functionality and it adds Thunder-specific dependencies, so it's better to separate it from the rest of the L0 tests. This PR also adds some checks to avoid spurious failures on A100.
- Move Lightning-Thunder integration test to L1

[PyTorch] Move Lightning-Thunder integration test to L1

---

transformer_engine/pytorch/attention.py

Loss curve of CP>1 and CP=1 does not match with cuDNN fused attention while batch size > 1, this is due to the non-contiguous dout. This PR fixed it.
cuDNN Fused Attn and Tri Dao' Flash Attn has different requirements on tensor memory format. Tri Dao's Attn only requires the last dim to be contiguous. TE integration of cuDNN Attn specifies qkv_format (bshd, sbhd, thd), tensors need to be contiguous in the specified format, this is a stronger requirement than Tri Dao's Attn. This is why it only shows issue with cuDNN Attn.

make sure dout is contiguous

---

transformer_engine/pytorch/tensor/_internal/float8_tensor_base.py
transformer_engine/pytorch/tensor/_internal/mxfp8_tensor_base.py
transformer_engine/pytorch/tensor/float8_tensor.py
transformer_engine/pytorch/tensor/mxfp8_tensor.py

https://github.com/NVIDIA/TransformerEngine/pull/1548 made some changes without updating the docs.
- Update docstrings for quantized tensor `prepare_for_saving` function

[PyTorch] Fix incorrect docstrings in tensor saving functions

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

FP8 input to the modules is temporary and fully internal variable.
- Set input_quantizer to internal for Linear, LayerNormLinear and LayerNormMLP

Use internal quantizer for input to the modules

---

.github/workflows/build.yml

Our build process has gotten too intensive for the GitHub runners to reliably handle. The core build test sometimes fails due to OOM, so this PR disables parallelism.
- Disable parallelilsm in GitHub core build test

Disable parallelism in core build test

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

Reverts NVIDIA/TransformerEngine#1551
Distributed tests are failing with this change and there are more issues that need to be fixed in the followup PR.

Revert "Use internal quantizer for input to the modules"

---

transformer_engine/pytorch/attention.py

This PR corrects the `fake_dtype` and `dqkv_type` used in `fused_attn_bwd` for FP8.
- Fix FP8 dtypes for fused attention backward

[PyTorch] Fix fused attention backward's FP8 dtypes

---

transformer_engine/jax/cpp_extensions/activation.py
transformer_engine/jax/cpp_extensions/attention.py
transformer_engine/jax/cpp_extensions/custom_call.py
transformer_engine/jax/cpp_extensions/normalization.py
transformer_engine/jax/cpp_extensions/quantization.py
transformer_engine/jax/cpp_extensions/softmax.py
transformer_engine/jax/cpp_extensions/transpose.py

JAX version >= 0.5 moves `jax.extend.ffi` to `jax.ffi`, we also changed to use `jax.ffi` in https://github.com/NVIDIA/TransformerEngine/pull/1469, but that is not compatible with users still using jax < 0.5. 
- Import `jax.ffi` for jax version >= 0.5 and `jax.extend.ffi` for jax version < 0.5.

[JAX] FFI API compatibility with both 0.4 and 0.5

---

transformer_engine/pytorch/csrc/extensions/bias.cpp
transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/module/layernorm_mlp.py

Supports calling bgrad quantize fusion for fp8 current scaling recipe.
```
pytest tests/pytorch/test_float8_current_scaling_exact.py::TestFP8CurrentScalingRecipeLinear::test_fp8_current_scaling_with_linear_module -s -v
pytest tests/pytorch/test_float8_current_scaling_exact.py::TestFP8CurrentScalingRecipeLayerNormLinear::test_fp8_current_scaling_with_layernorm_linear_module -s -v
PYTORCH_JIT=0 NVTE_TORCH_COMPILE=0 NVTE_ALLOW_NONDETERMINISTIC_ALGO=0 pytest tests/pytorch/test_numerics.py -s -v
pytest tests/pytorch/distributed/test_numerics.py -s -v
```

[PyTorch] Support Bgrad Cast FP8 Fusion for FP8 Current Scaling Recipe

---

tests/pytorch/distributed/run_layer_with_overlap.py
tests/pytorch/distributed/test_comm_gemm_overlap.py
transformer_engine/common/gemm/cublaslt_gemm.cu
transformer_engine/common/recipe/__init__.py
transformer_engine/pytorch/csrc/extensions/quantizer.cpp
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py
transformer_engine/pytorch/tensor/float8_tensor.py

Enable TP/Comm Overlap for Per-Tensor Current Scaling Recipe.
Python Unit Tests
```
pytest -s tests/pytorch/distributed/test_comm_gemm_overlap.py -k "FP8 and CURRENT" -v
pytest -s tests/pytorch/distributed/test_comm_gemm_overlap.py -v
torchrun --nproc_per_node 2 tests/pytorch/distributed/run_layer_with_overlap.py --seq-length=1024 --batch-size=1 --num-heads=8 --head-dim=64 --layer-type=layernormlinear --fp8 --quantization=fp8_current_scaling
```

[PyTorch] Support TP Overlap in Per-Tensor Current Scaling Recipe

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/linear.py

This PR adds support for offloading with MCore DistOpt. 
DistOpt needs some backward hooks to be triggered, current offloading in TE modifies the weight tensor attributes which affects the hook triggering in MCore. Fixed the issue in this PR.

Distopt with offload

---

tests/pytorch/test_numerics.py
transformer_engine/pytorch/distributed.py

The recompute context uses the same recipe
and fp8 settings as the original fwd pass.
By saving the recipe and fp8 configuration, recompute doesn't require the same fp8_autocast when loss.backward() is called.
Fixes #1568 
https://github.com/NVIDIA/TransformerEngine/issues/1568
Recompute fp8 recipe is saved in context.

Update full recompute feature to save recipe.

---

transformer_engine/jax/cpp_extensions/attention.py

cudnn 9.6+ supported packed format for softmax aux. This PR updates the shapes and partition inference rules to match.
Fix shape and sharding inference in fused attention C++ extension.

[JAX] Fix softmax aux shapes for packed/THD format

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

Currently for Hopper FP8 training, when weight is Float8Tensor and weight._transpose is invalidated by the optimizer step, no mechanism handles the creation of weight transpose thus the Dgrad errors out. This PR updates weight usage and ensure columnwise data is there before saved for bprop. 
- Change A
- Change B

Ensure weight transpose is valid for Hopper FP8 training

---

tests/pytorch/test_jit.py
transformer_engine/pytorch/jit.py

Currently, running `import transformer_engine` invokes torch.compile for a bunch of jit-functions, causing the inductor backend to spawn a number of processes. This defers the torch.compile step until the first time these functions are used to try to speed up the module's import time.
- Changes `jit_fuser` to use a lazy compile function, rather than torch.compile directly
- Adds a test to ensure these lazily-compiled functions are callable.

[PyTorch] Defer torch compilation steps until first function call

---

tests/pytorch/distributed/run_numerics.py
transformer_engine/pytorch/csrc/common.h
transformer_engine/pytorch/csrc/extensions/quantizer.cpp
transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py
transformer_engine/pytorch/tensor/float8_tensor.py
transformer_engine/pytorch/utils.py

We currently experience segfaults when FP8 current scaling is configured with the default PyTorch process group (`None`). This is because we access the process group from C++ and don't handle the case where it is `None`. This PR adds logic to canonicalize the process group before using it.
- Canonicalize amax reduction group before FP8 current scaling quantizer uses it
- Remove logic for amax reduction group size from FP8 current scaling quantizer

[PyTorch] Support default process group with FP8 current scaling

---

transformer_engine/pytorch/module/layernorm_mlp.py

The out_dtype in the computation of the weight gradient for the LayerNormMLP class ist not set properly if `fuse_wgrad_accumulation` is active. This leads to the following error:
```
RuntimeError: /tmp/builds/transformer-engine/TransformerEngine/transformer_engine/pytorch/csrc/extensions/gemm.cpp:117 in function gemm: Assertion failed: *out_dtype == D_tensor.dtype(). GEMM output has invalid dtype (expected 5, found 3)
```
For `Linear` and `LayerNormLinear` this is already properly handled, see https://github.com/NVIDIA/TransformerEngine/blob/0356010ca068b4205bda4e2f5feffa7fbd5e38ae/transformer_engine/pytorch/module/linear.py#L623-L625 for example.

[PyTorch] fix fuse_wgrad_accumulation in LayerNormMLP backward

---

transformer_engine/jax/__init__.py
transformer_engine/jax/quantize/helper.py

PR #1627 removed some of the exposed API that broke some of the current user's code.
This PR exposes those back:
- `NVTE_FP8_COLLECTION_NAME`
- `update_collections`
-  `get_delayed_scaling`

[JAX] Backward compatible Fixes

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py

TE v2.0 refactor inadvertently removed support for `fp8_buf` when using TP overlap.
- Enable fp8 output when using `fp8_buf` with UB.

Fix fp8_buf for Linear and LayerNormLinear

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py

`Linear`, `LayerNormLinear`, and `LayerNormMLP` have logic to make sure that the weight matrix has the required data formats for the dgrad GEMM. For `Linear`, we can skip this if we're going to skip the dgrad GEMM. However, `LayerNormLinear` and `LayerNormMLP` never skip the dgrad GEMM because its needed to compute norm grads. This PR fixes incorrect copy-pasted logic.
- Debug weight matrix usages for dgrad GEMM in `LayerNormLinear` and `LayerNormMLP`

[PyTorch] Debug weight matrix usages for dgrad GEMM

---

transformer_engine/common/include/transformer_engine/transformer_engine.h
transformer_engine/jax/cpp_extensions/gemm.py
transformer_engine/jax/csrc/extensions/gemm.cpp
transformer_engine/jax/quantize/scaling_modes.py

PR #1627 introduced `NVTE_NO_SCALING`; however, it is not yet supported in TE/Common.
Thus, this PR removes this scaling mode to avoid confusion for external developers.
- [] I have made corresponding changes to the documentation

Removing NVTE_NO_SCALING 

---

examples/jax/encoder/test_model_parallel_encoder.py
examples/jax/encoder/test_multigpu_encoder.py
examples/jax/encoder/test_single_gpu_encoder.py
examples/jax/mnist/test_single_gpu_mnist.py
qa/L0_jax_distributed_unittest/test.sh
tests/jax/test_custom_call_compute.py
tests/jax/test_distributed_layernorm.py
tests/jax/test_distributed_layernorm_mlp.py
tests/jax/test_layer.py
transformer_engine/jax/cpp_extensions/activation.py
transformer_engine/jax/cpp_extensions/gemm.py
transformer_engine/jax/cpp_extensions/misc.py
transformer_engine/jax/cpp_extensions/normalization.py
transformer_engine/jax/cpp_extensions/quantization.py
transformer_engine/jax/csrc/extensions.h
transformer_engine/jax/csrc/extensions/activation.cpp
transformer_engine/jax/csrc/extensions/gemm.cpp
transformer_engine/jax/csrc/extensions/misc.h
transformer_engine/jax/csrc/extensions/normalization.cpp
transformer_engine/jax/csrc/extensions/pybind.cpp
transformer_engine/jax/csrc/extensions/quantization.cpp
transformer_engine/jax/flax/module.py
transformer_engine/jax/quantize/dequantizer.py
transformer_engine/jax/quantize/helper.py
transformer_engine/jax/quantize/quantizer.py
transformer_engine/jax/quantize/scaling_modes.py
transformer_engine/jax/quantize/tensor.py

This PR discoupled the Scaling Enum value in JAX extension from the Scaling Enum value from TE/Common.
In addition, I also updated part of the NormPrimitive so that it is consistent with others.

[JAX] Scaling Enum Abstracting

---

tests/pytorch/test_fusible_ops.py
transformer_engine/pytorch/ops/basic/basic_linear.py

I've experienced some failures with `te.Sequential` when the linear op recieves quantized tensors without the required usages. This PR is a quick bugfix that explicity specifies the required usages for the dgrad and wgrad GEMMs.
- Explicity specify quantized tensor usages needed for linear op backward
- Include backward SwiGLU+cast fusion in tests (closes #1463)

[PyTorch] Explicitly specify quantized tensor usages needed for linear op backward

---

tests/pytorch/test_fusible_ops.py
transformer_engine/pytorch/ops/op.py
transformer_engine/pytorch/tensor/mxfp8_tensor.py

TE 2.0 changed how the fusible ops handled FP8 state, i.e. using quantizers rather than `fp8_meta` dicts, but the `get_extra_state`/`set_extra_state` functions were not updated. This PR updates these functions so they are similar to the module `get_extra_state`/`set_extra_state` functions:
https://github.com/NVIDIA/TransformerEngine/blob/be055eb027106afd3c5bd797c8617e509d11f0bb/transformer_engine/pytorch/module/base.py#L556
https://github.com/NVIDIA/TransformerEngine/blob/be055eb027106afd3c5bd797c8617e509d11f0bb/transformer_engine/pytorch/module/base.py#L616
I've also added a unit test.
- Update checkpointing functions in fusible ops with changes from TE 2.0
- Add tests for checkpointing fusible ops

[PyTorch] Debug checkpointing with te.Sequential

---

tests/pytorch/test_fusible_ops.py
transformer_engine/pytorch/ops/basic/activation.py

This PR adds experimental support in the activation fusible ops to cache input tensors in FP8. This reduces memory usage, at the expense of extra quantize/dequantize kernels and increased numerical error.
- Add option in activation ops to cache input in FP8

[PyTorch] Add option in activation ops to cache input in FP8

---

qa/L0_jax_unittest/test.sh
qa/L2_jax_unittest/test.sh

- Standardize test failure handling using the unified `test_fail` function and `error_exit` function
- New feature (non-breaking change which adds functionality)
Similar to https://github.com/NVIDIA/TransformerEngine/pull/1570
- Introduce `test_fail` function to track and report failed test cases.
Modify the test script in `L2_jax_unittest` to replace set -e with a custom error handling function `test_fail`, which captures case failure and allows the script to continue running subsequent cases. This change ensures that if the former case fails, the latter case will still be executed. 
Now, the script records specific failed test cases, prints an error message for each failed test case to facilitate search, and summarizes all failed test cases at the end of the script.
```
set -x
function …
```

[QA] Extend error handling

---

tests/pytorch/test_permutation.py
transformer_engine/common/permutation/permutation.cu
transformer_engine/pytorch/csrc/extensions/permutation.cu
transformer_engine/pytorch/permutation.py
transformer_engine/pytorch/triton/permutation.py

This PR aims to:
1. Support new recipes (blockwise, mxfp8) for permute fusion with `map_type == "mask"`.
2. We now limit the usage of fp8 to cases where only memory reordering is involved (such as permute.forward and unpermute.backward). For other cases, we force high precision. That's
```
On Permute:
Forward => FP8 input, FP8 output
Backward => BF16 input, BF16 output
On Unpermute:
Forward => BF16 input, BF16 output
Backward => FP8 input, FP8 output
```
- Change A
- Change B

[MoE] Support new recipes for permute_fusion

---

examples/jax/encoder/run_test_multiprocessing_encoder.sh
examples/jax/encoder/test_model_parallel_encoder.py
examples/jax/encoder/test_multigpu_encoder.py
examples/jax/encoder/test_multiprocessing_encoder.py
examples/jax/encoder/test_single_gpu_encoder.py
tests/jax/pytest.ini
tests/jax/test_distributed_fused_attn.py
tests/jax/test_distributed_layernorm.py
tests/jax/test_distributed_layernorm_mlp.py
tests/jax/test_distributed_softmax.py
transformer_engine/jax/cpp_extensions/activation.py
transformer_engine/jax/cpp_extensions/attention.py
transformer_engine/jax/cpp_extensions/base.py
transformer_engine/jax/cpp_extensions/normalization.py
transformer_engine/jax/cpp_extensions/quantization.py
transformer_engine/jax/cpp_extensions/softmax.py
transformer_engine/jax/quantize/scaling_modes.py

This is experimental and not intended for production use. If you try this, please file issues for problems you encounter.
Shardy is a new partitioning system in JAX. It currently replaces the sharding propagation passes in GSPMD.
This PR adds Shardy support for TE's attention, normalization, quantization and softmax primitives.
To use this, simply enable Shardy:
```
jax.config.update("jax_use_shardy_partitioner", True)
```
- Adds functions to provide Shardy sharding rules to primitives.

Add experimental Shardy support.

---

transformer_engine/pytorch/ops/basic/basic_linear.py

The linear op avoids modifying its input tensor since it assumes it could be used elsewhere. This results in it caching unnecessary data for the backward pass since it cannot discard unneeded tensor usages. This PR modifies its behavior so that it detaches the input tensor, allowing it to freely change the tensor usages without any external impact.
- Avoid unnecessary tensor usage when caching for linear op backward

[PyTorch] Avoid unnecessary tensor usages when caching for linear op backward

---

tests/pytorch/distributed/run_cast_master_weights_to_fp8.py
transformer_engine/pytorch/module/grouped_linear.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py
transformer_engine/pytorch/tensor/utils.py

Added a check for fp8 weight transpose cache in backward, and regenerated it if it does not exist. In FSDP, we may delete the FP8 transpose cache and then regenerate it in backward. This MR ensures that this function works properly.
In addition, this MR comes with an edge case treatment for FSDP + FP8 current scaling. The FSDP shard model weight may be a unit8 tensor instead of a float8 tensor. This situation is specially handled in the cast_master_weight_to_fp8 function.
Error stacktrace:
```
[rank2]: Traceback (most recent call last):
[rank2]:   File "/lustre/fsw/portfolios/coreai/users/jianbinc/playground/fp8_TE2.2/megatron-lm/pretrain_gpt.py", line 316, in <module>
[rank2]:     pretrain(
[rank2]:   File "/lustre/fsw/portfolios/coreai/users/jianbinc/playground/fp8_TE2.2/megatron-lm/mega …
```

[PyTorch] check and try to generate fp8 weight transpose cache before dgrad backward

---

tests/jax/test_layer.py
tests/jax/test_softmax.py
transformer_engine/jax/cpp_extensions/softmax.py
transformer_engine/jax/flax/module.py
transformer_engine/jax/flax/transformer.py

Fixes #1524 
Simplifies and corrects logic around mapping attn mask to softmax mask, while adding additional testing capabilities
1. Add test cases for better coverage in `test_layer.py`
- causal and window size None
- causal and window size default (-1,1)
- no_mask and window size default (-1,1)
- no_mask and window size default (2,2)
- padding and window size None
- padding_causal and window_size (2,2)
2. Correctly map `padding_causal` to `scaled_masked` instead of `scaled_upper_triangle`
3. Add fallback jax implementation for `scaled_upper_triangle` (#1524 )
4. Add tests for `Softmax` wrapper/module in `jax.flax.module.Softmax`
5. Simplify logic for jax based softmax
6. Add support table in comments for attn mask, SWA and softmax type
Add …

Fix #1524 and other softmax mask functionality

---

tests/cpp/operator/test_normalization.cu
tests/cpp/operator/test_normalization.h
tests/cpp/operator/test_normalization_mxfp8.cu
transformer_engine/common/include/transformer_engine/normalization.h
transformer_engine/common/normalization/common.cpp
transformer_engine/common/normalization/layernorm/ln_api.cpp
transformer_engine/common/normalization/rmsnorm/rmsnorm_api.cpp
transformer_engine/jax/cpp_extensions/normalization.py

Before this PR, when using CuDNN the operation `gamma += 1.0f` for zero-centered gamma in Norm operations was always computed in the datatype of `gamma`. This is different from our TE backend which always uses the compute datatype (fp32). In this PR, I make this configurable via an environment variable.
Note, this changes the default type for CuDNN `gamma += 1.0f` to be the compute dtype (fp32). This matches the TE backend dtype so I feel like this being the default makes sense here. However, this is different than the current precision which only supports the gamma weight datatype. Now, an environment variable `NVTE_ZERO_CENTERED_GAMMA_IN_WTYPE=1` can change it to be performed in the gamma datatype.
- Update CuDNN normalization plan to …

Support computing zero-centered gamma in compute dtype for CuDNN

---

transformer_engine/common/transformer_engine.cpp
transformer_engine/pytorch/cpp_extensions/gemm.py
transformer_engine/pytorch/csrc/extensions.h
transformer_engine/pytorch/csrc/extensions/apply_rope.cpp
transformer_engine/pytorch/csrc/extensions/attention.cu
transformer_engine/pytorch/csrc/extensions/gemm.cpp
transformer_engine/pytorch/csrc/extensions/swizzle.cpp
transformer_engine/pytorch/csrc/util.h

1. Move swizzle scaling factor to cpp, so we don't need to reset it after the gemm.
2. Replace `c10::optional` with `std::optional` since we're using C++17. PyTorch upstream is deprecating `c10::optional`. See https://github.com/pytorch/pytorch/pull/150464.

[PyTorch] Move swizzle scaling factor to cpp

---

tests/cpp/test_common.cu
tests/cpp/test_common.h
transformer_engine/common/common.h
transformer_engine/common/include/transformer_engine/transformer_engine.h
transformer_engine/common/transformer_engine.cpp
transformer_engine/pytorch/csrc/extensions/attention.cu

Reverts NVIDIA/TransformerEngine#1674
It turns out that the implementation of `NVTEShape` in #1674 is dangerous. `NVTEShape` contains an array and a pointer, and the pointer is usually initialized to point to the array. Since it is a POD type (required for C compatibility), copying the `NVTEShape` will naively copy the pointer. This results in unpredictable data corruption if `NVTEShape`s are initialized on the stack within local scope and are copied anywhere.
I liked how #1674 preserved API backward compatibility, but I think this issue may be fatal for that design. In order for `NVTEShape` to store its own data, we may need to go all the way and remove the pointer (see https://github.com/NVIDIA/TransformerEngine/pull/1674#discussion_r2045366875).

Revert "Allow NVTEShape to own data."

---

tests/cpp/operator/test_memset.cu
transformer_engine/common/common.cu
transformer_engine/common/include/transformer_engine/transformer_engine.h
transformer_engine/jax/csrc/extensions/activation.cpp
transformer_engine/jax/csrc/extensions/normalization.cpp
transformer_engine/jax/csrc/extensions/quantization.cpp

Adds a new API call and kernel for `nvte_memset`, a drop-in replacement for `cudaMemsetAsync` which uses a fill kernel for small sizes and falls back to `cudaMemsetAsync` for larger sizes.
In profiling small 4B memsets in TE/JAX, this takes less time
`cudaMemsetAsync` + latency gap: ~3.2us
`nvte_memset` + latency gap: 0.8us
- Created a new API call and kernel for `nvte_memset` which runs on a fill kernel on small sizes and falls back to `cudaMemsetAsync` for larger sizes
- Add cpp tests for nvte_memset
- Update TE/JAX extension to use `nvte_memset` to reduce gaps in profiles from `cudaMemsetAsync` on 4B zero-ing out of amax buffers before TE common kernels

Introduce nvte_memset to provide a fill kernel that is faster than cudaMemsetAsync for small sizes

---

transformer_engine/pytorch/module/base.py

In cases where `initialize_ub()`+`destroy_ub()` pairs are called more than once (e.g. in-process restarts), the cuBLAS workspace allocation is mishandled and grows exponentially. This PR safeguards the workspace expansion in `initialize_ub()` to avoid this leak.

[PyTorch] Fix cuBLAS workspace leak in applications that initialize+destroy Userbuffers more than once

---

transformer_engine/pytorch/module/grouped_linear.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/linear.py

Currently, TE's `Linear`, `LayerNormLinear` and `GroupedLinear` de-quantized the fp8 weights to bf16 when self.fp8 is False. This MR changes the de-quantization to raising an error, to prevent fp8 weights + non-fp8 computation.

Warn when using fp8 weights + non-fp8 computation

---

examples/jax/encoder/common.py
examples/jax/encoder/run_test_multiprocessing_encoder.sh
examples/jax/encoder/test_multigpu_encoder.py
examples/jax/encoder/test_multiprocessing_encoder.py
examples/jax/encoder/test_single_gpu_encoder.py
examples/jax/mnist/test_single_gpu_mnist.py
tests/jax/test_distributed_layernorm.py
tests/jax/test_distributed_layernorm_mlp.py
tests/jax/test_helper.py
transformer_engine/common/recipe/current_scaling.cu
transformer_engine/jax/cpp_extensions/activation.py
transformer_engine/jax/cpp_extensions/gemm.py
transformer_engine/jax/cpp_extensions/normalization.py
transformer_engine/jax/cpp_extensions/quantization.py
transformer_engine/jax/csrc/extensions/quantization.cpp
transformer_engine/jax/quantize/helper.py
transformer_engine/jax/quantize/quantizer.py

Supports distributed partitioning for multi-GPU current scaling. This implementation computes a global amax before quantizing with current scaling. This differs from PyTorch that computes a per-device amax and persists this into per-device scale_invs that persist through the gemm. This difference is due to differences on per-device tensors with JAX's auto-partitioning system. Pending discussion on ideas to implement this more similarly to PyTorch with per-device scale/amax.
- Implement partitioning for current scaling for DBiasQuantizePrimitive (including Shardy). Other primitives do not need to implement current scaling partitioning as other primitives are called in higher-precision before quantizing for current scaling.
- Compute global …

[JAX] Distributed Current Scaling

---

tests/pytorch/distributed/test_cast_master_weights_to_fp8.py

We were seeing test failures for FP8 block-scaling on systems that don't support it.
- Check if FP8 block scaling is supported in tests

[PyTorch] Check if FP8 block scaling is supported in tests

---

transformer_engine/common/CMakeLists.txt
transformer_engine/common/include/transformer_engine/recipe.h
transformer_engine/common/recipe/fp8_block_scaling.cu
transformer_engine/pytorch/csrc/extensions/fp8_block_scaling_partial_cast.cpp

Follow up PR in an effort to make framework extensions pure CPP
- Move fp8 block scaling related kernels to core lib.

[C][PyTorch] Move FP8 block scaling kernels to core

---

tests/jax/test_distributed_layernorm.py
transformer_engine/jax/cpp_extensions/quantization.py

Fixes a CI failure in which the incorrect number of communication bytes occurred in some `test_distributed_layernorm.py` tests for current scaling. The issue was the test was set up to assert 4 bytes of all reduce communication for an fp32 amax reduction, however the current scaling amax reduction was missing a cast to fp32 so in smaller dtypes would result in only 2 bytes of communication. Amax calculation and reduction is now always performed in fp32.
- For current scaling, cast input data to fp32 before performing the amax reduction.

[JAX] Fix distributed Layernorm test failure

---

tests/jax/test_custom_call_compute.py
transformer_engine/jax/cpp_extensions/gemm.py
transformer_engine/jax/dense.py

The current GroupedGemm APIs involves dynamic shapes thus it is not usable in JIT.
The new API is under ongoing development in PR #1721, which has a major difference in the API. 
So, we decided to remove the old API from the upcoming release.

[JAX] Exclude GroupedGemm APIs for TE 2.3

---

transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py

https://github.com/NVIDIA/TransformerEngine/pull/1686 introduced a bug when returning the norm output from `LayerNormLinear`/`LayerNormMLP`. In particular, this line breaks the logic for reshaping the norm output:
https://github.com/NVIDIA/TransformerEngine/blob/dac098d816cd6001a3dc4ce8f1b2f65e1fea5bc6/transformer_engine/pytorch/module/layernorm_linear.py#L142
- Fix bug when reshaping norm output from `LayerNormLinear`/`LayerNormMLP`

[PyTorch] Fix bug when reshaping norm output from LayerNormLinear

---

transformer_engine/jax/cpp_extensions/activation.py
transformer_engine/jax/cpp_extensions/normalization.py
transformer_engine/jax/csrc/extensions/activation.cpp

Fixes two issues occurring in MaxText integration with TE. 1) NaNs caused on multi-gpu usage of the LayerNormMLP layer 2) Partitioning shape mismatch errors caused by using TE's LayerNorm layer with TP>1
- Add additional shape checks on TE/JAX cpp extension for dact to ensure we pass the correct shapes after partitioning and don't implicitly assume `dz` and `x` are the same shape.
- In the dact primitive, make `dz` always use the same partitioning as `x`. In combination with the checks above, this prevents NaNs from running dact on `dz` and `x` partitioned differently leading to out of bounds reads.
- In the norm primitive, make the input `x` not partition along the TP axis. This prevents partitioning shape errors we were encountering where `x` was partitioned along TP but the norm output …

[JAX] Fix partitioning issues in LayerNorm and LayerNormMLP layers

---

README.rst

Updates the README to list the JAX NGC container in addition to the PyTorch container
- Update README to mention the JAX NGC container

Update README to list JAX NGC container

---

.github/workflows/build.yml

Fix the workflow builds to be aligned with current installation recommendation.
- Remove build isolation from workflow builds.

Remove build isolation from GH builds

---

transformer_engine/pytorch/module/grouped_linear.py

https://github.com/NVIDIA/TransformerEngine/pull/1712 added a spurious warning when running the `GroupedLinear` module without any quantization. We should only warn if running `GroupedLinear` without quantization _and_ it has quantized weights.
- Avoid spurious warning with non-FP8 GroupedLinear

[PyTorch] Avoid spurious warning with non-FP8 GroupedLinear

---

build_tools/jax.py
build_tools/pytorch.py

Size of TE torch `.so` before fix: 116MB
Size of TE torch `.so` after fix: 2MB
Root cause: distutils adds debug info `-g` by default to compilation flags.
- Use debug flags only when necessary.

Reduce framework extensions' binary size and fix debug builds

---

transformer_engine/jax/cpp_extensions/gemm.py

Reverts PR #1740 as it caused shape mismatches in MaxText/TE integration GEMMs when delayed scaling FP8 was enabled, which is the gemm type this PR modified. Reverting the PR fixes the GEMM shape issues.
- Add back in reshapes around tensor scaling FP8 GEMM for now to prevent shape mismatch issues.

Revert "[JAX] Removes unneccessary reshapes for FP8 GEMM (#1740)"

---

transformer_engine/pytorch/module/layernorm.py
transformer_engine/pytorch/module/rmsnorm.py

The current implementation has a problematic ordering:
- In `__init__`, `super().__init__()` is called first
- Then `self.sequence_parallel` is set
- If `reset_parameters()` gets called during the parent's initialization, it will try to use `self.sequence_parallel` before it's been set.
This could lead to the `sequence_parallel` not being properly applied to the parameters during initialization.
Currently, this is fixed with (in `__init__`):
https://github.com/NVIDIA/TransformerEngine/blob/51cd441501e8e6dee18c00056f008e1b53b89ebd/transformer_engine/pytorch/module/layernorm.py#L107-L109
but this does not seem right
Set sequence_parallel before super().__init__() in norm modules

Set sequence_parallel before super().__init__() in norm modules

---

qa/L3_pytorch_FA_versions_test/test.sh

This PR reduces the number of FA versions tested in L3 PyTorch CI. This CI constantly times out after 4hrs and we'd like to remove some of the older versions, i.e. 2.3.0 and 2.4.1, which are from over a year ago and not frequently used by users.
- Remove 2.3 and 2.4.1 from L3 CI.

[PyTorch] Reduce FA versions in L3 CI

---

transformer_engine/pytorch/attention/multi_head_attention.py
transformer_engine/pytorch/transformer.py

A model we're working on uses interleaved rotary embeddings, which while supported by `apply_rotary_pos_emb`, isn't exposed to the `MultiHeadAttention` or `TransformerLayer` classes.
Adds the `rotary_pos_interleaved` parameter to the MultiHeadAttention and TransformerLayer classes.

Expose interleaved parameter for rotary position embeddings

---

build_tools/build_ext.py
setup.py
transformer_engine/__init__.py
transformer_engine/common/__init__.py
transformer_engine/jax/__init__.py
transformer_engine/pytorch/__init__.py

A cleanup and minor refactor of the runtime library loading infrastructure during TE import, along with miscellaneous bug fixes.
- Avoid use of `subprocess` to run python/pip, this is leading to esoteric failures during library loading in various environments.
- Consolidate logic for finding TE's shared object files in a single function based on various cases.
- Cleanup the framework's `__init__.py` files.
- Fix various cases of library loading after editable/source/wheel install and catch errors in case of any discrepancies.
- Remove a few unused lines in main `setup.py`.
- Fix duplication of shared object file during editable installation.
Create robust build testing suite to check for above cases in the CI.

Fix miscellaneous bugs during library loading

---

examples/jax/encoder/test_multiprocessing_encoder.py
tests/jax/utils.py
transformer_engine/jax/dense.py
transformer_engine/jax/flax/module.py
transformer_engine/jax/flax/transformer.py
transformer_engine/jax/layernorm_mlp.py
transformer_engine/jax/sharding.py

TE/JAX Flax modules are using weight initialization that only supports physical mesh partitioning axes, not logical axes used in some frameworks, such as MaxText. To support partitioning in these frameworks weight initialization was updated to a newer way that supports logical axes.
- Update Flax modules in `module.py` and `transformer.py` to replace usages of `nn_partitioning.param_with_axes` with `self.param(..., nn.with_logical_partitioning(...), ...)`
- Fix bug where ffn1 intermediate result in the LayerNormMLP layer incorrectly added a sharding constraint to replicate the tensor and following gemm, leading to OOM on some configs that normal MaxText did not have OOM on.

[JAX] Support logical partitioning axes in TE Flax modules

---

qa/L0_pytorch_unittest/test.sh
setup.py
tests/pytorch/test_hf_integration.py
transformer_engine/pytorch/module/base.py

This switches the default `extra_state` item for no FP8 metadata to an empty torch tensor, so that we ensure that all entries in the model's state_dict will be torch tensors for maximum compatibility.
- Change A
- Change B

Use an empty torch tensor to indicate no fp8 information in extra_state

---

docs/api/c/comm_gemm_overlap.rst
docs/api/c/index.rst

Remove `comm_gemm_overlap` doc.
- Remove `comm_gemm_overlap` doc.

Remove `comm_gemm_overlap` doc

---

transformer_engine/jax/cpp_extensions/activation.py
transformer_engine/jax/cpp_extensions/base.py
transformer_engine/jax/cpp_extensions/quantization.py

Split primitives with and without dbias into separate primitive subclasses. The actual implementation is still shared between them in a shared base class. This is purely organization for disabling TE custom call primitives with better granularity with `NVTE_JAX_CUSTOM_CALLS_RE`.
- Split DAct primitive into two primitives classes, one with DBias in the name and one without.
- Split Quantization primitive into two primitives classes, one with DBias in the name and one without.

[JAX] Make primitive names more granular for better disabling granularity

---

docs/api/common.rst
transformer_engine/common/recipe/__init__.py

Document `Float8CurrentScaling` and `Float8BlockScaling` recipes.
- Document `Float8CurrentScaling` and `Float8BlockScaling` recipes.

Add docs for missing FP8 recipes.

---

transformer_engine/jax/cpp_extensions/gemm.py

XLA-FP8 feature that pattern-matched QDQ->dot is unstable and going to be [deprecated](https://flax-linen.readthedocs.io/en/latest/guides/quantization/fp8_basics.html#deprecated-apis).
Hence, we replace the pattern-matching GEMM with doing direct FP8 GEMM and dequantizing the output, as recommended by [the JAX guideline](https://flax-linen.readthedocs.io/en/latest/guides/quantization/fp8_basics.html#delayed-scaling).

[JAX] FP8 GEMM via dot_general + direct quant

---

transformer_engine/jax/cpp_extensions/misc.py
transformer_engine/jax/cpp_extensions/quantization.py

Use 1x quantization with `QuantizePrimitive` and transpose in JAX instead of 2x fused transpose + quantization as it performed better on Blackwell and on Hopper.
- Update `_quantize_dbias_impl` to use 1x quantization and a JAX transpose instead of 2x fused transpose + quantization.

[JAX] Use 1x quantization + jax transpose for performance for tensor-scaling

---

transformer_engine/jax/csrc/extensions/attention.cpp

Fixed leaking NVTETensors in `attention.cpp` created with `nvte_tensor_pack_create` but were missing frees with `nvte_tensor_pack_destory`.
Reproduced issue locally with `pytest tests/jax/test_distributed_fused_attn.py`. Confirmed with local testing with this fix PR and debug info enabled on `TensorAllocator` in `transformer_engine.cpp` that the capacity of the pool did not exceed `256`. Previously the tests failed due to exceeding `81920` unfreed NVTETensors.
- Added two missing `nvte_tensor_pack_destory` calls in `attention.cpp`.

[JAX] Fix NVTETensor leak in attention.cpp

---

transformer_engine/jax/cpp_extensions/misc.py
transformer_engine/jax/cpp_extensions/quantization.py

Fixes issue with #1830 that would attempt to call a 1x + fused dbias kernel that doesn't exist on Hopper, leading to the following error:
```
/opt/transformerengine/transformer_engine/common/util/cast_kernels.cuh:1164 in function fp8_quantize_arch_l_100: Not implemented scaling mode or fusion: NVTE_DELAYED_TENSOR_SCALING on GPU with compute capability < 10.0.
```
- Do not force 1x quantization if on Hopper and using dbias as a 1x fused quantize and dbias kernel does not exist for Hopper.

[JAX] Fix 1x quantize kernel availability check on hopper

---

transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers-host.cpp
transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers.h

Fixed the Userbuffers communicator destructor to cover imported Multicast handles.

[Common] Missing CUDA driver deallocations in Userbuffers

---

transformer_engine/pytorch/module/grouped_linear.py

Let `GroupedLinear` get `skip_fp8_weight_update` only in CUDA Graph capturing, to align the behavior of `Linear`/`LayernormLinear`.
- Change A
- Change B

[PyTorch] Get `skip_fp8_weight_update` only in CUDA Graph Capturing

---

transformer_engine/pytorch/module/base.py

Fix loading checkpoints created before #1799.
- Check if state is `None` before proceeding to load.

[PyTorch] Fix backward compatibility for checkpoint loading

---

tests/jax/test_custom_call_compute.py
transformer_engine/jax/cpp_extensions/gemm.py
transformer_engine/jax/cpp_extensions/quantization.py
transformer_engine/jax/csrc/extensions.h
transformer_engine/jax/csrc/extensions/gemm.cpp
transformer_engine/jax/csrc/extensions/pybind.cpp
transformer_engine/jax/dense.py
transformer_engine/jax/quantize/dequantizer.py
transformer_engine/jax/quantize/tensor.py

- Fixes for JIT-able grouped_gemm and grouped_quantize
- Enforcing workspace to be aligned by 256.

Fixes for JIT-able grouped_gemm

---

tests/pytorch/test_sanity.py
transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/tensor/mxfp8_tensor.py

When initializing a model with quantized weights, the required data is different for training and inference (training requires row-wise data for forward GEMM and column-wise data for dgrad GEMM, inference only requires column-wise). This PR adds logic so the model will only initialize quantized weights with the data required for inference when initialized within [no-grad mode](https://docs.pytorch.org/docs/stable/notes/autograd.html#no-grad-mode) or [inference mode](https://docs.pytorch.org/docs/stable/notes/autograd.html#inference-mode). It is also less aggressive about deallocating weight data in order to handle cases where we were alternating between training and validation modes.
This is an alternative to https://github.com/NVIDIA/TransformerEngine/pull/1827. The heuristic API in that …

[PyTorch] Inference mode disables initializing quantized weights with column-wise usage

---

tests/pytorch/distributed/test_fusible_ops.py
tests/pytorch/distributed/test_fusible_ops_with_userbuffers.py
tests/pytorch/test_fusible_ops.py
tests/pytorch/utils.py
transformer_engine/pytorch/distributed.py
transformer_engine/pytorch/ops/basic/basic_linear.py
transformer_engine/pytorch/ops/fused/userbuffers_forward_linear.py

This PR makes some minor changes needed for te.Sequential to support FP8 current scaling. It also modifies the te.Sequential unit tests to more gracefully handle quantization schemes other than FP8 delayed scaling.
- Support FP8 current scaling in operation-based API
- Generalize support for quantizers in tests for operation-based API

[PyTorch] Add support for FP8 current scaling in operation-based API

---

tests/cpp/util/test_string.cpp

One test case for our string utility functions assumes that `char` is signed, but ARM64 systems usually use an unsigned type. This PR explicitly specifies `signed char` for this case.
-Fix test case that assumes `char` is signed

Fix test case that assumes char is signed

---

tests/pytorch/distributed/run_numerics.py
tests/pytorch/distributed/test_numerics.py

https://github.com/NVIDIA/TransformerEngine/pull/1806 relaxed the numerical tolerances for the distributed tests using FP32 because they are actually doing compute in TF32. However, it seems the tolerances are still too tight because we are still seeing test failures on some systems. Since TF32 has the same number of mantissa bits as FP16, this PR drops the FP32 tolerances to match the FP16 tolerances in [`torch.testing.assert_close`](https://docs.pytorch.org/docs/stable/testing.html#torch.testing.assert_close).
- Use FP16 tols for distributed tests with TF32 compute

[PyTorch] Use FP16 tols for distributed tests with TF32 compute

---

examples/jax/encoder/test_model_parallel_encoder.py
examples/jax/encoder/test_multigpu_encoder.py
examples/jax/encoder/test_multiprocessing_encoder.py

Switch to use keyword args for `jax.jit(f, in_shardings=in_shardings, out_shardings=out_shardings)` as position args are no longer supported in latest JAX versions.
- Use keyword args for `jit` sharding args

[JAX] Use keyword args for jit in_shardings and out_shardings

---

tests/pytorch/distributed/test_fusible_ops.py
tests/pytorch/distributed/test_fusible_ops_with_userbuffers.py
tests/pytorch/test_fusible_ops.py
transformer_engine/pytorch/ops/_common.py
transformer_engine/pytorch/ops/basic/activation.py
transformer_engine/pytorch/ops/basic/add_in_place.py
transformer_engine/pytorch/ops/basic/all_gather.py
transformer_engine/pytorch/ops/basic/all_reduce.py
transformer_engine/pytorch/ops/basic/basic_linear.py
transformer_engine/pytorch/ops/basic/bias.py
transformer_engine/pytorch/ops/basic/identity.py
transformer_engine/pytorch/ops/basic/l2normalization.py
transformer_engine/pytorch/ops/basic/layer_norm.py
transformer_engine/pytorch/ops/basic/make_extra_output.py
transformer_engine/pytorch/ops/basic/quantize.py
transformer_engine/pytorch/ops/basic/reduce_scatter.py
transformer_engine/pytorch/ops/basic/reshape.py
transformer_engine/pytorch/ops/basic/rmsnorm.py
transformer_engine/pytorch/ops/fused/forward_linear_bias_activation.py
transformer_engine/pytorch/ops/fused/forward_linear_bias_add.py
transformer_engine/pytorch/ops/fused/userbuffers_backward_linear.py
transformer_engine/pytorch/ops/fused/userbuffers_forward_linear.py
transformer_engine/pytorch/ops/fuser.py
transformer_engine/pytorch/ops/op.py
transformer_engine/pytorch/tensor/_internal/float8_tensor_base.py

Enable use of internal tensors (ex. `Float8TensorBase`) instead of regular quantized tensor (ex. `Float8Tensor`) in `te.Sequential`. Essentially, this removes calls to `Float8Tensor.__new__` and to `detach` (see visual comparison of forward pass below).
Expected performance gain: E2E FP8 GPT encoder Transformer layer implemented using Sequential: +15% over `main`.
1. (39ea63da05c23565201e2270626afbcc8672155a) Replace free function `is_float8_tensor` with `is_quantized_tensor` in `_common.py` and use it throughout the `ops` codebase to check if a tensor is a (possibly internal) quantized tensor
2. (9e5acd94af7ceaa3a94598474bbebac162b5dcdd) Change interface of `fuser_forward` and `op_forward` to no longer take preceding and following ops and instead take the following op's input quantizer …

Enable use of internal tensors in Sequential

---

tests/pytorch/test_fusible_ops.py
transformer_engine/pytorch/ops/basic/basic_linear.py
transformer_engine/pytorch/tensor/_internal/float8_blockwise_tensor_base.py
transformer_engine/pytorch/tensor/_internal/float8_tensor_base.py
transformer_engine/pytorch/tensor/_internal/mxfp8_tensor_base.py
transformer_engine/pytorch/tensor/mxfp8_tensor.py

Adds a test checking the validity of a `LayerNormMLP` implementation using `te.ops.Sequential` to `test_fusible_ops.py`. The test doesn't check for numerical accuracy, but only whether execution actually works, as using multiple layers together makes the results incommensurable with the reference implementation.
Additionally, this PR implements some fixes for issues uncovered with the test.
- Renamed `TestSequential` to `TestSequentialContainer` in `test_fusible_ops.py`
- Added `TestSequentialModules` with `TestSequentialModules.test_layernorm_mlp` to `test_fusible_ops.py`
- Fixed access to unimplemented methods of `torch.Tensor` when using internal quantized tensors
- Added missing method `view` to `MXFP8TensorBase`
- Added check for tensor being quantized before accessing its `dtype` in …

Add test for `LayerNormMLP` implementation using `te.ops.Sequential` to `test_fusible_ops.py`

---

transformer_engine/pytorch/graph.py
transformer_engine/pytorch/ops/basic/basic_linear.py
transformer_engine/pytorch/ops/basic/bias.py
transformer_engine/pytorch/ops/basic/layer_norm.py
transformer_engine/pytorch/ops/basic/rmsnorm.py
transformer_engine/pytorch/ops/fuser.py
transformer_engine/pytorch/ops/op.py
transformer_engine/pytorch/ops/sequential.py

Change `FusibleOperation.pre_forward` to `FusibleOperation.pre_first_forward` and call it only before the first forward iteration using a given recipe type in `OperationFuser.__call__`. Additionally, reset fusions on recipe type change to enable recipe-dependent fusions and retrigger a call to `pre_first_forward`. See removed calls in the visual comparison of forward pass below.
Resultant performance gain in benchmark scenario: +4% for FP8 Sequential.
- Rename `FusibleOperation.pre_forward` to `FusibleOperation.pre_first_forward`
- Call `pre_first_forward` only before the first forward in `OperationFuser` instead of calling it every iteration
- Pass `recipe: Optional[Recipe]` as argument to `pre_first_forward` instead of access via `FP8GlobalStateManager`
- Remove redundant `set_usage` …

Call `pre_(first_)forward` only when global state changes

---

transformer_engine/pytorch/module/fp8_padding.py
transformer_engine/pytorch/module/fp8_unpadding.py

The `Fp8Padding`/`Fp8Unpadding` module could be initialized before FP8 is initialized, so `FP8GlobalStateManager.get_fp8_recipe()` would just return the default fp8 recipe instead of the real one.
- Change A
- Change B

[PyTorch] Fix setting `align_size` when FP8 is not initialized

---

.gitignore
qa/L0_pytorch_unittest/test.sh
tests/pytorch/test_checkpoint.py
tests/pytorch/utils.py

Some downstream users experienced pain when we merged https://github.com/NVIDIA/TransformerEngine/pull/1033 because it affected the checkpoint format, namely by adding `_extra_state` to the state dict for the `LayerNorm` and `RMSNorm` modules. This PR adds tests for loading previously-generated checkpoints with [`strict=True`](https://docs.pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.load_state_dict). Even if we decide to change the checkpoint format in the future, these tests will make sure that it is a deliberate decision.
Note that these tests don't check correctness since that's tested in a few other places:
https://github.com/NVIDIA/TransformerEngine/blob/cc0cb35d4cb516669e1f166add37ccdc30f71488/tests/pytorch/test_numerics.py#L846 …

[PyTorch] Tests for loading previously-generated checkpoints

---

benchmarks/linear/benchmark_grouped_linear.py
transformer_engine/pytorch/csrc/common.h
transformer_engine/pytorch/csrc/extensions/cast.cpp
transformer_engine/pytorch/csrc/quantizer.cpp
transformer_engine/pytorch/tensor/_internal/mxfp8_tensor_base.py
transformer_engine/pytorch/tensor/mxfp8_tensor.py

Previous PR with the same technique: https://github.com/NVIDIA/TransformerEngine/pull/1793
Relevant PR that can help with CPU overhead in GroupedLinear: https://github.com/NVIDIA/TransformerEngine/pull/1912
- Change A
- Change B

[PyTorch][MoE] MXFP8 Support to Reduce CPU Overhead By Fuse Torch Empty Calls

---

examples/jax/encoder/requirements.txt
examples/jax/mnist/requirements.txt

HuggingFace datasets version 4.0 update broke the encoder examples. Capping version to keep using previous 3.6 instead.

[JAX] Capped HuggingFace datasets version for TE/JAX encoder examples

---

tests/pytorch/test_fusible_ops.py
transformer_engine/common/util/cast_gated_kernels.cuh
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/ops/basic/activation.py
transformer_engine/pytorch/ops/basic/add_in_place.py
transformer_engine/pytorch/ops/basic/all_gather.py
transformer_engine/pytorch/ops/basic/all_reduce.py
transformer_engine/pytorch/ops/basic/basic_linear.py
transformer_engine/pytorch/ops/basic/bias.py
transformer_engine/pytorch/ops/basic/identity.py
transformer_engine/pytorch/ops/basic/l2normalization.py
transformer_engine/pytorch/ops/basic/layer_norm.py
transformer_engine/pytorch/ops/basic/make_extra_output.py
transformer_engine/pytorch/ops/basic/quantize.py
transformer_engine/pytorch/ops/basic/reduce_scatter.py
transformer_engine/pytorch/ops/basic/reshape.py
transformer_engine/pytorch/ops/basic/rmsnorm.py
transformer_engine/pytorch/ops/fused/__init__.py
transformer_engine/pytorch/ops/fused/backward_bias_activation.py
transformer_engine/pytorch/ops/fused/backward_linear_add.py
transformer_engine/pytorch/ops/fused/forward_linear_bias_activation.py
transformer_engine/pytorch/ops/fused/forward_linear_bias_add.py
transformer_engine/pytorch/ops/fused/userbuffers_backward_linear.py
transformer_engine/pytorch/ops/fused/userbuffers_forward_linear.py
transformer_engine/pytorch/ops/fuser.py
transformer_engine/pytorch/ops/op.py
transformer_engine/pytorch/ops/sequential.py

Adds two backward fusions to `te.ops.Sequential`: dbias+quantize and dbias+dactivation+quantize. See fusions in the visual comparison of backward pass below.
Resultant performance gain in small model CPU-bound benchmark scenario: +4% on B100, +7% on H100 for FP8 Sequential.
Resultant performance gain in large model GPU-bound benchmark scenario: +5% on B100 for FP8 Sequential.
[<img width="1843" height="765" alt="image" src="https://github.com/user-attachments/assets/92990d7f-65f8-4eb5-bbf3-76385ec0604a" />](https://github.com/user-attachments/assets/92990d7f-65f8-4eb5-bbf3-76385ec0604a)
- (5befeb456974e0bdb225ccfab00aaf4b93e227f0) Mark inputs to `OperationFuser` which `require_grad` as `do_not_clear` to prevent backward from deleting them with `clear_tensor_data`. Remove `is_first_op` …

Add backward fusions of dbias+quantize and dbias+dactivation+quantize to `te.Sequential`

---

transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers-host.cpp
transformer_engine/common/gemm/cublaslt_gemm.cu
transformer_engine/common/util/cuda_runtime.cpp
transformer_engine/common/util/cuda_runtime.h
transformer_engine/common/util/rtc.cpp

Some users have experienced errors when running TE on systems with older CUDA versions (https://github.com/NVIDIA/TransformerEngine/issues/1585, https://github.com/NVIDIA/TransformerEngine/issues/1922). This is because we build the core library (`libtransformer_engine.so`) with a recent CUDA version and distribute it in a Pip wheel, so the compile-time and run-time CUDA versions may not match. This PR adds some more careful version checking logic, especially for cuBLAS GEMMs and CUDA multicast operations.
Closes https://github.com/NVIDIA/TransformerEngine/issues/1585. Closes https://github.com/NVIDIA/TransformerEngine/issues/1922.
- Add run-time checks for CUDA and cuBLAS versions

Run-time checks for CUDA and cuBLAS versions

---

tests/jax/test_helper.py

This small PR resolves a test method name conflict by renaming duplicated `test_fp8_autocast_mxfp8_scaling` methods to distinct names: `test_fp8_autocast_mxfp8_current_scaling` for `Float8CurrentScaling` tests and `test_fp8_autocast_mxfp8_block_scaling` for `MXFP8BlockScaling` tests.
- Resolve test conflict in JAX helper tests

[JAX] Resolve test conflict in JAX helper tests

---

examples/jax/encoder/test_model_parallel_encoder.py
examples/jax/encoder/test_multigpu_encoder.py
examples/jax/encoder/test_multiprocessing_encoder.py
transformer_engine/jax/flax/transformer.py
transformer_engine/jax/sharding.py

Updates our `with_sharding_constraint_by_logical_axes` helper function to support and prefer Flax logical axis rules when they exist in the current context. If no Flax logical axes rules exist in the current context, it will fall back to TE's hardcoded logical axes, though this functionality is no deprecated and will be removed in the future.
- Update `with_sharding_constraint_by_logical_axes` to check if Flax logical axis rules exist in the current context, and if so call the sharding constraint with `flax.linen.with_logical_constraint`
- Update unfused attention in `transformers.py` to remove duplicate SEQLEN_AXIS usage in a single sharding constraint. This was not flagged before since our TE hardcoded axis system didn't check for this and it was always mapped to `None`/replicated.
- …

[JAX] Support Flax sharding constraints

---

transformer_engine/common/multi_tensor/adam.cu
transformer_engine/common/multi_tensor/multi_tensor_apply.cuh
transformer_engine/common/transformer_engine.cpp

One of our multi-tensor Adam kernels incorrectly downcasts an FP32 tensor to BF16 (https://github.com/NVIDIA/TransformerEngine/issues/1863). This PR fixes that bug. I've also taken the opportunity to add more safety checks.
Closes #1863.
- Fix unnecessary cast in capturable Adam kernel
- Add safety checks to multi-tensor Adam functions

Handle dtypes more carefully in multi-tensor Adam

---

examples/jax/encoder/test_model_parallel_encoder.py
examples/jax/encoder/test_multigpu_encoder.py

Tighten Encoder Test tolerances, which were previously relaxed by the PR #1855.

[JAX] Tighten Encoder Test tolerances

---

tests/jax/test_distributed_layernorm.py
transformer_engine/jax/cpp_extensions/gemm.py
transformer_engine/jax/quantize/dequantizer.py
transformer_engine/jax/quantize/scaling_modes.py
transformer_engine/jax/quantize/tensor.py

This PR removes unnecessary padding steps in the MXFP8 workflow, which should improve the recipe performance.
Right now, we do
```
1. Allocate padded scale in inner_primitive.abstract() 
2. Slice out the padding in Primitive.impl(), after calling the inner_primitve
3. Add padding in ScaledTensor.__post_init__()
4. Remove padding before calling the custom call
5. Adding padding in the Primitive.impl() before calling the inner_primitive
```
This PR removes unnecessary padding steps, the new workflow becomes:
```
1. Allocate padded scale in inner_primitive.abstract() 
2. Slice out the padding in Primitive.impl(), after calling the inner_primitve
5. Adding padding in the Primitive.impl() before calling the inner_primitive
```
(3) and (4) are removed.
- [] I have commented my code, …

[JAX] Remove unneccessary MXFP8 scale_inv padding 

---

transformer_engine/common/fused_attn/kv_cache.cu
transformer_engine/pytorch/attention/inference.py

This PR improves the runtime performance of the `reindex_kv_cache` and `copy_to_kv_cache` kernels, by remapping CUDA blocks/threads to different `b`, `s`, `hxd` dimensions, parallelizing one loop that was previously serial, and skipping reindexing if there are no new sequences added to the batch.
Example problem size: b=64, max_s=1024, current_s=128, new_s=8, h=12, d=256, on Hopper
Before: reindex: 4.8ms, copy: 1.3ms
After: reindex: 46us, copy: 13us
- Optimize reindex and copy kernels in KV caching

[Common] Optimize KV cache related kernels

---

transformer_engine/common/fused_attn/fused_attn.cpp

This PR updates `cudnn-frontend` module to 1.13.0. It also updates TE's `head_dim` logic to align with 1.13.0's changes.
- Update FE to 1.13.0 and related `head_dim` support logic.

Update cudnn-frontend to 1.13.0

---

tests/jax/test_distributed_layernorm_mlp.py

JAX's FP8 GEMM, `jax.lax.dot_general`, now uses the Triton backend by default. The error of the Triton FP8 gemm has been verified to be less than or equal to the error of the cuDNN FP8 gemm w.r.t a float32 ground truth. However, Triton can auto-tune a different kernel for the single GPU and multi-GPU run in this test, meaning the diff between single GPU and multi-GPU can be larger in some cases, even though both are within tolerance to the float32 ground truth.
- Update tolerance for failing FP8 cases in `test_distributed_layernorm_mlp.py` due to Triton now becoming the default backend

[JAX] Update tolerance of distributed layernorm MLP for FP8

---

build_tools/pytorch.py
docs/debug/1_getting_started.rst

Dependencies pinned via GH URLs block package upload to PyPI.
- Remove install deps that are given directly via GH URL. This is technically a breaking change from the user pov for the debug feature in TE/PyTorch but it is a requirement for the user to install, initialize, and configure `nvidia-dlfw-inspect` before use, so it is okay in this case.

[PyTorch] Remove GH pinned deps

---

transformer_engine/pytorch/module/base.py

Some users have encountered problems with quantized weight caching when running validation steps, followed by training steps. This PR checks if FP8 cached weights have the required data.
This fix is similar to https://github.com/NVIDIA/TransformerEngine/pull/1593, which focused on MXFP8 cached weights. As discussed [here](https://github.com/NVIDIA/TransformerEngine/pull/1593#issuecomment-2741229675), a better long-term solution is to change `tex.quantize` so it allocates any missing buffers (implemented in https://github.com/NVIDIA/TransformerEngine/pull/1836 or https://github.com/NVIDIA/TransformerEngine/pull/1952).
- Reset FP8 weight workspace if usages are invalid

[PyTorch] Reset FP8 weight workspace if usages are invalid

---

transformer_engine/pytorch/graph.py
transformer_engine/pytorch/ops/basic/basic_linear.py
transformer_engine/pytorch/ops/fuser.py
transformer_engine/pytorch/ops/op.py

https://github.com/NVIDIA/TransformerEngine/pull/1951 changed the behavior of the fusible ops to only change the quantizer recipe state (mostly in `BasicOperation._fp8_metas`) when the recipe class changed. It turns out this was causing problems when the recipe changes but keeps the same type, e.g. if FP8 delayed scaling changes the amax history length. This PR is a quick fix that fixes the case where the FP8 amax history length changes, although it's not robust to other changes (e.g. with the FP8 amax reduction group).
- Reset recipe state in fusible operations when FP8 amax history length changes

[PyTorch] Reset recipe state in fusible operations when FP8 amax history length changes

---

qa/L0_jax_unittest/test.sh
tests/jax/test_helper.py

Fix issue with current scaling test_helper.py check and enable test_helper.py tests in L0
- Fix current scaling assert in `test_helper.py` to remove `.margin` check as the field doesn't exist on the `Float8CurrentScalingRecipe` class
- Correct the pytest skip check for current scaling tests in `test_helper.py` to check for `fp8_supported` instead of `mxfp8_supported`
- Remove the filter that disabled `test_helper.py` from L0 tests so it will be in our L0 suite

[JAX] Fix current scaling test_helper.py and enable test_helper.py in L0

---

tests/pytorch/test_fusible_ops.py
transformer_engine/pytorch/ops/basic/__init__.py
transformer_engine/pytorch/ops/basic/add_extra_input.py
transformer_engine/pytorch/ops/basic/make_extra_output.py
transformer_engine/pytorch/ops/fused/backward_linear_add.py
transformer_engine/pytorch/ops/fused/forward_linear_bias_add.py
transformer_engine/pytorch/ops/fuser.py

Adds `in_place` kwarg to `MakeExtraOutput` and `AddExtraInput` (renamed from `AddInPlace`).
- (77eabef3d48717b491d5ff4aec4e8835008bde5e) Mark output tensors as not deletable in backward (this was previously overlooked and could potentially cause issues with extra outputs).
- (e4013105c1c66ba69ffc4d85519f6696b457b9fb) Add `in_place` kwarg to `MakeExtraOutput`
- (79269822ca2551f11ee79062c442593c9eee6690) Rename `AddInPlace` to `AddExtraInput` and add an `in_place` kwarg

Add `in_place` kwarg to extra tensor ops

---

tests/cpp/operator/test_cast_mxfp8.cu
tests/cpp/operator/test_cast_mxfp8_gated_swiglu.cu
transformer_engine/common/util/cast_gated_kernels.cuh
transformer_engine/common/util/cast_kernels.cuh

This PR fixes integer overflow issue when computing offset indices in large tensors in cast kernels.
- Replaced **int** with **size_t** in cast kernels and the corresponding test suites

[Common] Fixed integer overflow issue in cast kernels

---

transformer_engine/jax/cpp_extensions/gemm.py
transformer_engine/jax/dense.py
transformer_engine/jax/flax/module.py
transformer_engine/jax/flax/transformer.py
transformer_engine/jax/layernorm_dense.py
transformer_engine/jax/layernorm_mlp.py
transformer_engine/jax/sharding.py

`GemmPrimitive` was originally developed to inherit the partitioning rules of the native `jax.nn.scaled_matmul` implementation. However, this causes partitioning rules to effectively kill tensor-parallelism in the MLP block when FFN1 receives a sequence-parallel input.
This PR changes the partitioning rules to avoid all-gathering tensor-parallel RHS operands under any conditions, and instead rely on an extra boolean flag input to convert the `jax.lax.psum` on the GEMM output into a `jax.lax.psum_scatter`.

[JAX] Fixing GemmPrimitive partitioning rules to handle tensor-parallelism correctly for sequence-parallel inputs

---

tests/pytorch/test_fusible_ops.py
transformer_engine/pytorch/ops/basic/__init__.py
transformer_engine/pytorch/ops/basic/constant_scale.py
transformer_engine/pytorch/ops/basic/dropout.py

This PR adds fusible ops for dropout (heavily based on [`torch.nn.Dropout`](https://docs.pytorch.org/docs/stable/generated/torch.nn.Dropout.html)) and multiplying by a constant scalar. These are not performant, but they provide an API for future custom implementations or fusions.
- Add fusible ops for dropout and constant scale

[PyTorch] Add ops for dropout and constant scale

---

transformer_engine/pytorch/csrc/extensions/normalization.cpp

Make sure that the backing storage has the same scope as the TensorWrapper referencing it.
- Change A
- Change B

Fix the use-after-free bug in unfused normalization

---

transformer_engine/common/transformer_engine.cpp
transformer_engine/common/util/vectorized_pointwise.h
transformer_engine/pytorch/csrc/common.h
transformer_engine/pytorch/csrc/extensions/activation.cpp
transformer_engine/pytorch/csrc/quantizer.cpp
transformer_engine/pytorch/tensor/float8_tensor.py

This PR fuses amax computation into activation (both forward and backward) kernels for non-quantized outputs when using FP8 current scaling removing a call to `nvte_compute_amax`.
- (646062940a1e768f7738e36e4acc4f814b5abe70) Compute amax in activation kernels when the output pointer is provided, even for non-fp8 outputs
- (234774a38ef04f6b06bff0285ac20dcf492eaa5a) Initialize metatensor values for the `Float8CurrentScalingQuantizer` to avoid using atomic max on uninitialized amax
- (8a686d6c88a6fa2532758f53d30ffcb2e3ec83d1) Fuse computation of amax into the activation kernel for fp8 current scaling. Adds two new member functions to `Float8CurrentScalingQuantizer`.
```cpp
class Float8CurrentScalingQuantizer : public Quantizer {
public:
...
/*! @brief Convert to a quantized data format …
```

Fuse amax computation into activation kernel

---

transformer_engine/pytorch/ops/fuser.py

https://github.com/NVIDIA/TransformerEngine/pull/1977 renamed a tensor attr from `do_not_clear` to `_do_not_clear`, but it missed one usage from https://github.com/NVIDIA/TransformerEngine/pull/1983.
- Fix bug with clearing op outputs during backward

[PyTorch] Fix bug with clearing op outputs during backward

---

transformer_engine/pytorch/csrc/extensions/normalization.cpp

Refactor normalization.cpp to use quantizer logic introduced in #1952 instead of manual quantization.
- (7a77ab40916f95ae140a7fcd569ed9077b9cdb07) Replace manual quantization logic with `quantizer->quantize` in `normalization.cpp`

Refactor normalization.cpp to use quantizer logic introduced in #1952

---

transformer_engine/common/normalization/layernorm/ln_api.cpp
transformer_engine/common/normalization/layernorm/ln_fwd_kernels.cuh
transformer_engine/common/normalization/rmsnorm/rmsnorm_api.cpp
transformer_engine/common/normalization/rmsnorm/rmsnorm_fwd_kernels.cuh
transformer_engine/pytorch/csrc/extensions/normalization.cpp

This PR is analogous to #2004. This PR makes the TE custom LayerNorm and RMSNorm forward kernels output the `amax` even if the output is not quantized (as long as the output pointer is provided). This removes the need to separately compute the `amax` with `nvte_compute_amax` and instead use `Float8CurrentScalingQuantizer::quantize_with_amax` (introduced in #2004). It also forces `nvte_layernorm_fwd` and `nvte_rmsnorm_fwd` to use those kernels if the fusion is requested.
- (ef7ba38859756f62b80e9564e3b55a390630d163) Compute `amax` in normalization kernels as long as the `amax` output pointer is provided, even if using non quantized output
- (a74db8f31c26ab10c1d706d03b1601a43753b53c) Change C++ code to take advantage of the kernel's new capability by using …

Fuse amax computation into normalization kernel for current scaling

---

transformer_engine/common/common.h

The original dytpe int would be an issue if the tensor element numbers are larger than int32's range (which is not a super large number in real workloads)
- Change A
- Change B

Tensor numel() return dtype to be size_t

---

tests/jax/conftest.py
tests/jax/test_distributed_softmax.py

L1 jax tests occasionally timeout due to long running attention and softmax tests. This PR addresses the softmax tests.
Before:
```
================================================================================
TEST RUNTIME SUMMARY (grouped by function)
test_distributed_softmax.py
================================================================================
test_softmax                                                 | 288x | 2082.61s | avg:   7.23s
test_softmax_shardy                                          |  24x |   10.02s | avg:   0.42s
================================================================================
TOTAL RUNTIME                                                |      | 2092.63s |
================================================================================
``` …

[JAX] Reduce L1 tests/jax/test_distributed_softmax.py test runtime

---

transformer_engine/common/util/cast_kernels.cuh

Since the quantization for different input tensors are independent, we can enable PDL for the kernels to overlap them to some extent. Compared to multi-stream launch, PDL gives us a fine-grained control to reduce the interference as much as possible. For example, in the MXFP8 quantization kernel, we let the former kernel's last stage computation overlap with the latter kernel's TMA load.
Here're the Nsys profiles for 8 consecutive MXFP8 quantization kernels (input tensors in shape [4096, 4096]) with 1) launch sequentially, 2) multi-stream launch, 3) PDL launch. Multi-stream launch doesn't show perf gain while PDL launch gives about 1.22x speedup.
1. launch sequentially
2. multi-stream launch
3. PDL launch
- Change A
- Change B

[Common] PDL for Quantization Kernels

---

transformer_engine/pytorch/csrc/common.cpp
transformer_engine/pytorch/csrc/common.h

Fixed potential integer overflow in buffer allocation when handling large tensor groups. This addresses a critical edge case where buffer_size calculations could overflow due to incorrect type usage in roundup function.
Anyone can reproduce the bug using the following code:
```
import torch
from transformer_engine.pytorch.module import GroupedLinear
from transformer_engine.pytorch.fp8 import fp8_autocast
from transformer_engine.common.recipe import Float8BlockScaling, Format
def test_grouped_linear_fp8():
local_experts = 4
hidden_size = 6144 
total_tokens = 398016
out_features = hidden_size
x = torch.randn(total_tokens, hidden_size, dtype=torch.bfloat16, device='cuda')  
m_splits = [total_tokens // local_experts] * local_experts
m_splits[-1] += total_tokens % local_experts
layer = …
```

[PyTorch] Fix numeric overflow caused by int-type parameters and return value in the roundup function

---

tests/jax/test_custom_call_compute.py
transformer_engine/jax/csrc/extensions/gemm.cpp
transformer_engine/jax/csrc/extensions/quantization.cpp

This PR removes the cudaGraph compatible trait from `GroupedGemmFFI` and `GroupedQuantizeFFI`. This helps to prevent these two FFI nodes from getting registered into the graph, as they are not CUDA Graph compatible due to the usage of `cudaStreamSynchronize`. 
With this change, we can now execute a jitted `grouped_gemm` in CUDAGraph-enabled runs.

[JAX] Remove cudaGraph compatible trait from GroupedGemmFFI and GroupedQuantizeFFI

---

transformer_engine/jax/cpp_extensions/base.py
transformer_engine/jax/layernorm_mlp.py
transformer_engine/jax/quantize/helper.py

With changes introduced in the GH-2023, the TE GEMM custom calls outperform the built-in JAX `dot_general` in most of the parallelism schemes (except TP + Sharding in the hidden dimension of remaining unsharded activations) for all recipes.
Hence, this PR enabled TE GEMM custom calls as the default. 
In addition, a warning is raised when sharding in the hidden dimension of the MLP activation input is detected.

[JAX] Enable TE GEMM custom call for all recipes

---

transformer_engine/pytorch/ops/basic/basic_linear.py
transformer_engine/pytorch/ops/fuser.py
transformer_engine/pytorch/ops/op.py

The fusible ops have a bug with FP8 delayed scaling where the amax pointers in the quantizer and `FP8GlobalStateManager` are not updated when the amax history is reallocated. This results in the FP8 scales never being updated.
This hadn't caused problems since we initialized the amax history during the first forward pass and it's uncommon to change the amax history length during training. However, https://github.com/NVIDIA/TransformerEngine/pull/1951 changed behavior to initialize the recipe state when an op is constructed with quantized params (see https://github.com/NVIDIA/TransformerEngine/pull/1985 for a related bug). If `fp8_model_init` and `fp8_autocast` use recipes with different amax history lengths (e.g. Megatron-LM uses default in `fp8_model_init`), then we reallocate the amax …

[PyTorch] Update amax pointers when reallocating amax history in fusible ops

---

transformer_engine/pytorch/ops/basic/basic_linear.py

This fixes a bug when the linear functional API attempts to deduce the dtype from the weight tensor (see https://github.com/NVIDIA/TransformerEngine/issues/2011).
Closes https://github.com/NVIDIA/TransformerEngine/issues/2011.
- Fix bug when deducing dtype in linear functional API

[PyTorch] Fix bug when deducing dtype in linear functional API

---

qa/L2_jax_distributed_unittest/test.sh
tests/jax/test_distributed_layernorm.py

Create a script for `qa/L2_jax_distributed_unittest` so we can move distributed tests from L1 to L2 with a lower cadence and speed up L1.
- Create L2 distributed test script
- Update L1 distributed test script to set test level environment variable `NVTE_JAX_UNITTEST_LEVEL="L1"` which was missing

[JAX] Add L2_jax_distributed_unittest

---

transformer_engine/common/transpose/quantize_transpose_square_blockwise.cu
transformer_engine/common/transpose/quantize_transpose_vector_blockwise.cu

Enable PDL for blockwise quantization kernels following #2001.
This gives about 10% speedup for 8 consecutive quantization kernels.
TOT：
With PDL:
- Change A
- Change B

[Common] PDL for Blockwise Quantization

---

tests/pytorch/test_cuda_graphs.py
transformer_engine/common/common.cu
transformer_engine/common/transpose/quantize_transpose_square_blockwise.cu
transformer_engine/common/util/cast_gated_kernels.cuh
transformer_engine/common/util/cast_kernels.cuh
transformer_engine/common/util/cuda_driver.cpp
transformer_engine/common/util/dequantize_kernels.cuh

Previously we call `cuda_driver::ensure_context_exists()` in `create_2D_tensor_map`, which adds a lot CUDA driver calls if creating multiple TMA descriptors. We now move it to the beginning of kernels that would create TMA descriptors.
- Change A
- Change B

[Common] Reduce CUDA driver calls

---

transformer_engine/pytorch/ops/fuser.py

We keep track of the first TE module within an `fp8_autocast` context so that we can perform an FP8 scale update during its backward pass. However, the op fuser does not consider the possibility that it might not perform a backward pass. This was causing divergence problems in some finetuning workflows where the first layer does not require any grads.
- Avoid registering FP8 scale update in ops without backward pass

[PyTorch] Avoid registering FP8 scale update in ops without backward pass

---

transformer_engine/common/swizzle/swizzle.cu
transformer_engine/pytorch/tensor/mxfp8_tensor.py

#2019 added the feature to fuse padding of scaling inverses and swizzling. Without launch bounds, this kernel now fails with `CUDA Error: too many resources requested for launch` under specific conditions (such as debug builds) due to increased register usage.
Also converting some `zeros` &rarr; `empty` calls missed in #2019.
- Add launch bounds to swizzle kernels.
- Initialize MXFP8 scale inverses with empty since swizzle kernels will pad OOB region.

[Core] Add launch bounds to swizzle kernels

---

qa/L2_jax_unittest/test.sh
tests/jax/distributed_test_base.py
tests/jax/test_distributed_fused_attn.py

Reduce the number of L1 distributed fused attn tests so as to reduce CI nightly time outs (which runs L0 and L1 tests)
**_Preliminary tests suggest reduction of ~12 mins (720 seconds)_** 
**L1 test timings (before changes in this PR)**:
```
================================================================================
TEST RUNTIME SUMMARY (grouped by function)
================================================================================
test                                                         |  36x |    5.23s | avg:   0.15s
test_context_parallel_allgather_attn                         | 480x | 1446.77s | avg:   3.01s
test_context_parallel_allgather_attn_shardy                  |  60x |  204.83s | avg:   3.41s
test_context_parallel_ring_attn                              | 1920x | …
```

[JAX] Trim dist fused attn tests in L1 

---

transformer_engine/pytorch/attention/multi_head_attention.py

During multi head attention, when we apply the rotary position embedding, we may be using a context parallel setting, in which we have padded the input sequences to be divisible by cp_size*2.
In that case, we need to pass the cu_seqlens_padded to the rotary embedding in order to have the right shape, since we padded the input sequence.
- Added a change to the mha script to enable passing `cu_seq_lens_padded`  if `pad_between_seqs` is true.
- Change B

fix: fixes multi head attention for context parallel: rotary embedding to use padded cu_seq_lens

---

tests/cpp/operator/test_normalization.cu
tests/cpp/operator/test_normalization.h
tests/cpp/test_common.cu
tests/pytorch/test_fusible_ops.py
transformer_engine/common/include/transformer_engine/normalization.h
transformer_engine/common/normalization/common.cpp
transformer_engine/common/normalization/common.h
transformer_engine/common/normalization/layernorm/ln_api.cpp
transformer_engine/common/normalization/rmsnorm/rmsnorm_api.cpp
transformer_engine/common/normalization/rmsnorm/rmsnorm_bwd_kernels.cuh
transformer_engine/common/normalization/rmsnorm/rmsnorm_bwd_semi_cuda_kernel.cu
transformer_engine/pytorch/csrc/extensions.h
transformer_engine/pytorch/csrc/extensions/normalization.cpp
transformer_engine/pytorch/csrc/extensions/pybind.cpp
transformer_engine/pytorch/ops/fused/__init__.py
transformer_engine/pytorch/ops/fused/backward_add_rmsnorm.py
transformer_engine/pytorch/ops/fuser.py

Fuse `MakeExtraOutput` with `RMSNorm` in the backward pass. Works through adding `nvte_rmsnorm_bwd_add`.
- (7ef7b578ebc4ce4e0edae218fdaa3a67dabb268a) Add `nvte_rmsnorm_bwd_add` as well as PyTorch binding, test, and update kernel to support the fusion
- (507471894d028cd7e253f1af309438d5ecd1c69b) Add `BackwardAddRMSNorm` fused operation, including test

Add backward RMSNorm+Add fusion

---

transformer_engine/pytorch/graph.py

This PR avoids a situation where automatic garbage collection destroys a graph while another graph is being captured, which results in a CUDA error.
The bug was introduced with https://github.com/pytorch/pytorch/pull/158193 and https://github.com/pytorch/pytorch/pull/158649. See https://github.com/pytorch/pytorch/pull/161037 for a bugfix and more details.
- Avoid garbage collection when capturing a CUDA Graph

[PyTorch] Avoid garbage collection when capturing a CUDA Graph

---

transformer_engine/jax/flax/transformer.py

The `cp_strategy` arg is not exposed to the `DotProductAttention` api which is used in MaxText to provide Fused Attn support. This PR exposes this argument to DPA.
- added `cp_strategy` arg to DPA api
- wrote helper code to match different strings to existing CP strategies
- [] I have added tests that prove my fix is effective or that my feature works

[ TE-JAX ] Expose cp_strategy argument to DPA api

---

transformer_engine/jax/layernorm_mlp.py
transformer_engine/jax/sharding.py

1. Using `RulesFallback.AXIS_IS_UNSHARDED` instead of the `RulesFallback.NO_CONSTRAINT` in the `flax.linen.with_logical_constraint` so that if an axis is undefined in the mesh, it will still apply the sharding constraint for the given tensor in other axes instead of skipping ([More info](https://github.com/google/flax/blob/485e101df79376851e2da407f36d266ebebc6574/flax/linen/spmd.py#L216-L223)).
2. Add a `dot_1_output` sharding constraint if `dot_2_input_axes` is provided. This is a WAR for the known Shardy shading propagation issue.

[JAX] `dot_1_output` sharding constraint + use AXIS_IS_UNSHARDED

---

transformer_engine/pytorch/attention/dot_product_attention/utils.py

Relax constraints to cuDNN 9.13 for disabling fused attn for kv caching

Further relax constraints to cuDNN 9.13 for disabling fused attn for kv caching

---

transformer_engine/pytorch/csrc/extensions/cast.cpp

It's possible that using from_blob for empty token for an expert cause issue because from_blob will check whether the data pointer is valid. 
Unclear why the sanity test with exact same edge case cannot reproduce the issue. Might close this PR once we figure it out or merge this PR if it solves the problem. 
- Change A
- Change B

[PyTorch][MOE] Tentative Fix For Replacing from_blob with empty for experts receiving zero tokens

---

docs/api/pytorch.rst
examples/pytorch/comm_gemm_overlap/te_layer_with_overlap.py
tests/pytorch/distributed/run_layer_with_overlap.py
tests/pytorch/distributed/test_fusible_ops_with_userbuffers.py
transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers-host.cpp
transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers.h
transformer_engine/pytorch/__init__.py
transformer_engine/pytorch/module/__init__.py
transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/module/layernorm_linear.py
transformer_engine/pytorch/module/layernorm_mlp.py
transformer_engine/pytorch/module/linear.py
transformer_engine/pytorch/ops/fused/userbuffers_backward_linear.py
transformer_engine/pytorch/ops/fused/userbuffers_forward_linear.py

Adds support for using FP8 and non-FP8 quantization modes with UB overlap in the same model by allocating separate communicators and dynamically switching between them based on the layer's configured FP8 state

feat: Add support for multiple quantization modes in the UB communicators

---

tests/pytorch/test_fusible_ops.py
transformer_engine/common/CMakeLists.txt
transformer_engine/common/__init__.py
transformer_engine/common/dropout/dropout.cu
transformer_engine/common/include/transformer_engine/dropout.h
transformer_engine/pytorch/csrc/extensions.h
transformer_engine/pytorch/csrc/extensions/dropout.cpp
transformer_engine/pytorch/csrc/extensions/pybind.cpp
transformer_engine/pytorch/ops/basic/dropout.py

Dropout with 8-bit RNG

---

tests/jax/test_custom_call_compute.py
tests/jax/test_distributed_layernorm_mlp.py
transformer_engine/jax/activation.py
transformer_engine/jax/cpp_extensions/activation.py
transformer_engine/jax/cpp_extensions/gemm.py
transformer_engine/jax/cpp_extensions/normalization.py
transformer_engine/jax/cpp_extensions/quantization.py
transformer_engine/jax/dense.py
transformer_engine/jax/layernorm.py
transformer_engine/jax/layernorm_dense.py
transformer_engine/jax/layernorm_mlp.py
transformer_engine/jax/quantize/quantizer.py
transformer_engine/jax/quantize/scaling_modes.py
transformer_engine/jax/quantize/tensor.py

To unify our API between quantized and non-quantized codepaths, as well as supporting high-precision ops to output an amax in use for current scaling, this PR creates a NoScaleTensor wrapper around jnp.ndarray which can also optionally store an amax. This change also restructures the class hierarchy in tensor.py so this new class and the existing ScaledTensor classes all inherit from a new AbstractBaseTensor class with a shared interface.
- Introduce new AbstractBaseTensor class that is a base class and interface for the existing ScaledTensor classes as well as the new NoScaleTensor class
- Create NoScaleTensor class which can store non-quantized data along with an optional amax
- Update scaling_modes.py to implement a NoScalingModeMetadataImpl for high-precision which doesn't have scales …

[JAX] NoScaleTensor wrapper for non-quantized data

---

transformer_engine/common/fused_router/fused_moe_aux_loss.cu
transformer_engine/common/fused_router/utils.h

Add the new datatype(1. bf16, 2. fp32) support on the token-per-expert on the moe-aux-loss-computation kernel. 
- Change A
- Change B

Add bf16/fp32 token-per-expert to the MoE aux loss kernel

---

transformer_engine/jax/cpp_extensions/base.py
transformer_engine/jax/cpp_extensions/gemm.py
transformer_engine/jax/csrc/extensions/gemm.cpp

XLA often inserts transpose ops before and after the `custom_partitioning` in the custom call to transform and partition the data and scale_inv.
This PR fuses the swizzle with the transpose after the `custom_partitioning`, resulting in up to 1.4% speedup in the E2E training of LLama3.1 8B on GB200x4.  
Profiling with TPSP2 + FSDP2, focusing on the First GEMM in the MLP.
- Before fusing swizzling:
- After fusing swizzling:
The time between AG and launching the GEMM kernel reduces from 70us to 53us.

[JAX] Scale swizzling via JAX transpose op

---

tests/jax/test_custom_call_compute.py
transformer_engine/jax/cpp_extensions/activation.py
transformer_engine/jax/cpp_extensions/normalization.py

Applying lower precision as the original inputs to accelerate FP8 current-scaling. In our reduced-layer llama-3.1-8b experiments, this change could bring ~3% performance and ~5% with PGLE, which narrow the performance gap to ~3% compared to delayed-scaling.
- Reset the Norm outputs' precision as the input to trigger lower-precision ARs for amax compuation.
- Remove FP32 up-casting for gated activation.

Lower precision gated-act to accelerate FP8 current-scaling.

---

tests/pytorch/test_cpu_offloading.py
transformer_engine/pytorch/ops/_common.py
transformer_engine/pytorch/ops/basic/activation.py
transformer_engine/pytorch/ops/basic/basic_linear.py
transformer_engine/pytorch/ops/basic/dropout.py
transformer_engine/pytorch/ops/basic/l2normalization.py
transformer_engine/pytorch/ops/basic/layer_norm.py
transformer_engine/pytorch/ops/basic/rmsnorm.py
transformer_engine/pytorch/ops/fused/forward_linear_bias_activation.py
transformer_engine/pytorch/ops/fused/forward_linear_bias_add.py
transformer_engine/pytorch/ops/fused/forward_linear_scale_add.py
transformer_engine/pytorch/ops/fused/userbuffers_forward_linear.py

This PR modifies the fusible ops to support CPU offloading for activations (see https://github.com/NVIDIA/TransformerEngine/pull/571). It also simplifies the test and makes it more precise.
- Support activation CPU offloading in fusible ops
- Debug and refactor CPU offloading test

[PyTorch] Support activation CPU offloading in fusible ops

---

docs/examples/attention/attention.ipynb
tests/pytorch/attention/test_attention_with_cp.py
transformer_engine/pytorch/attention/dot_product_attention/context_parallel.py
transformer_engine/pytorch/attention/dot_product_attention/utils.py

Because [flash-attention](https://github.com/Dao-AILab/flash-attention) [#1604](https://github.com/Dao-AILab/flash-attention/pull/1604)  has already support hdimQK != hdimV backward, so we can support FA3(Flash Attention 3) backend for MLA (Multi-latent attention). [#1604](https://github.com/Dao-AILab/flash-attention/pull/1604)  allows us to skip explicit padding & unpadding hdimV to use FA3 as attention backend, and it can bring performance benefits.
Test Results:
1. I add some unit tests for FA3 MLA CP, test_fused_attn.py and test_fused_attn_with_cp.py passed.
2. I use the Megatron-LM framework to run the 16B DeepSeek model, where TP=CP=2, hdimQK=192, hdimV=128, FA3's MFU is basically the same as cuDNN attention, and the overall loss curves of the two are exactly the same.
1. Update FA3 …

[PyTorch] Support FA3 MLA CP feature

---

transformer_engine/common/fused_attn/fused_attn.cpp
transformer_engine/pytorch/attention/dot_product_attention/utils.py

Rather than updating these checks every time that we have a new cuDNN version (without the bugfix), this PR aims to apply a blanket condition until a resolution is achieved.
The conditional will be revisited once the cuDNN bug is fixed

Fix cuDNN version checks when getting backend and for sm89 kv cache

---

transformer_engine/jax/cpp_extensions/activation.py
transformer_engine/jax/cpp_extensions/attention.py
transformer_engine/jax/cpp_extensions/base.py
transformer_engine/jax/cpp_extensions/normalization.py
transformer_engine/jax/cpp_extensions/quantization.py
transformer_engine/jax/cpp_extensions/softmax.py

In the latest CI with JAX 0.7.2, `import jax.extend.ffi` fails in the lint test.
Since it's not essential to support JAX version < 0.5.0 now, we can remove this import.

[JAX] Remove import jax.extend.ffi

---

transformer_engine/common/util/nvfp4_transpose.cuh

This pull request fixes the logic for calculating the strides in the columnwise scale inverse. Previously the shape vector of that tensor is accessed without checking if the transpose is needed (and therefore if that shape is even populated), leading to the OOB memory access and a possible segfault.

Fix the segfault in the nvfp4 quantization

---

transformer_engine/common/CMakeLists.txt

#2045 added the cutlass backend for GEMM that results in a build hang during compile time.
**Note**: #2177 introduces features that result in a significantly slower compilation time for debug build, but it does not hang with this fix and hence not addressed in this PR.
- Remove debug options for cutlass GEMM source.

Fix hang during debug build

---

transformer_engine/common/recipe/__init__.py

Convert NVFP4 recipe to a data class such that the fields can be passed as arguments during initialization. This is also resulting in the failure of some tests in TE fused ops that rely on the `make_recipe` method in `tests/pytorch/utils.py`.
- Convert `NVFP4BlockScaling` to a data class.

Convert `NVFP4BlockScaling` to dataclass

---

transformer_engine/jax/quantize/helper.py

Before
After
- Indent fp8_autocast docstring so it's detected as a codeblock

[JAX] Fix code block in fp8_autocast docstring

---

transformer_engine/pytorch/triton/permutation.py

If the input size is large, some int32 indices will overflow. Modified them to int64.
- Change A
- Change B

[PyTorch] fix int32 overflow in permute kernels

---

build_tools/pytorch.py

HF `transformers` has `torchao` as a dependency, which only added [safetensors](https://github.com/pytorch/ao/pull/2881) support recently. `transformers` uses this feature without robust version checks for availability of this functionality. This is resulting in CI failures from our end. This is a workaround for a green CI until this is fixed properly in `transformers`.
- Include `torchao` minimum version for pytorch test requirements.

[PyTorch] Fix tests for 🤗 integration

---

transformer_engine/pytorch/module/base.py
transformer_engine/pytorch/module/layernorm_mlp.py

Use fused kernel for bias gradient and nvfp4 quantization in the backward pass.
- Use fused kernel for bias gradient and nvfp4 quantization in the backward pass.

[PyTorch] Unblock fused bgrad quantization path for nvfp4
