- setup.py
> Remove pytest-runner from setup requirements

- transformer_engine/common/recipe.py
> Fix docs for default FP8 format in recipe

- docs/conf.py
Add an ability to switch to the documentation snapshot of the older releases.
> Add link to the documentation archives in the docs

- transformer_engine/common/transpose/cast_transpose_fusion.cu
Fixed the out of bounds access to the partial dbias workspace.
> Fix the out-of-bounds access in the C+T+dbias kernel

- transformer_engine/pytorch/fp8.py
> Full activation recompute checkpointing bug fix

- qa/L0_lint/pylintrc
Cleanup pylint config file after removal of PyTorch softmax extensions
> cleanup pylintrc

- transformer_engine/pytorch/module.py
> Fix LayerNorm API param names

- transformer_engine/pytorch/transformer.py
> Fix in MHA cross attention path

- transformer_engine/pytorch/transformer.py
> Enforce boolean attention mask type

- qa/L0_lint/pylintrc
- transformer_engine/common/CMakeLists.txt
- transformer_engine/common/activation/gelu.cu
- transformer_engine/common/common.h
- transformer_engine/common/fused_softmax/scaled_masked_softmax.cu
- transformer_engine/common/gemm/cublaslt_gemm.cu
- transformer_engine/common/layer_norm/ln_api.cpp
- transformer_engine/common/nvtx.h
- transformer_engine/common/rmsnorm/rmsnorm_api.cpp
- transformer_engine/common/transpose/cast_transpose.cu
- transformer_engine/common/transpose/cast_transpose_fusion.cu
- transformer_engine/common/transpose/multi_cast_transpose.cu
- transformer_engine/common/transpose/transpose.cu
- transformer_engine/common/util/cast.cu
- transformer_engine/pytorch/module.py
Changes:
- Changed pre_forward/post_forward and pre_backward/post_backward into context managers
- Added NVTX ranges
> Add NVTX to TE modules

- transformer_engine/pytorch/cpp_extensions.py
- transformer_engine/pytorch/csrc/extensions.cu
- transformer_engine/pytorch/csrc/extensions.h
- transformer_engine/pytorch/module.py
> Add margin for LayerNorm kernel SM usage

- transformer_engine/pytorch/module.py
This pull request addresses the following 2 issues from PR #40 
- ~~Whether or not to compute dgrad is not determined solely by `input.requires_grad`. For a lot of the LLM cases this attribute is `False` but we still need to propagate the gradient.~~ The check for `inputmat.requires_grad` always returns `False` in the scenario of checking whether or not to compute dgrad because `inputmat` is the output of an operation and a new tensor of the same name. To do the check, we need to grab the `requires_grad` from `inp` instead. Since this needs to be done for all 3 APIs and is an orthogonal issue, it is out of the scope of this PR. 
- We update the forward scales/amaxes for the previous iteration in the beginning of the current iteration. Thus, `needs_stats` cannot be set only for training …
> Numerics fix from #40

- transformer_engine/pytorch/fp8.py
> Add docs for FP8 calibration

- transformer_engine/common/fused_softmax/scaled_masked_softmax.cu
- transformer_engine/common/fused_softmax/scaled_upper_triang_masked_softmax.cu
- transformer_engine/pytorch/csrc/extensions.cu
Based on the same fix in APEX made by @cyanguwa (https://github.com/NVIDIA/apex/pull/1568)
> Fix the integer overflow in fused softmax

- transformer_engine/pytorch/fp8.py
- transformer_engine/pytorch/module.py
> Address steady memory increase and bloated checkpoints

- transformer_engine/pytorch/csrc/ts_fp8_op.cpp
> remove d2d copies

- qa/L0_unittest/test.sh
- tests/test_fp8.py
- transformer_engine/pytorch/fp8.py
- transformer_engine/pytorch/module.py
> Bug fixes from PR 22

- tests/pytorch/test_sanity.py
- transformer_engine/pytorch/module.py
> Conditional dgrad computation for Linear API

- .github/workflows/deploy_nightly_docs.yml
> Fix nightly docs build

- transformer_engine/tensorflow/module.py
- transformer_engine/tensorflow/transformer.py
We are not recommended to use the `autocast_variable` from keras, which is an internal API. So, this PR gets rid of it.
cc. @trevor-m @pjannaty
> Remove the autocast_variable from TF-TE

- README.rst
- docs/installation.rst
We were telling to install the dev version in the README.
> Clean up the installation instruction.

- transformer_engine/pytorch/transformer.py
> Remove userbuf docs

- transformer_engine/pytorch/transformer.py
`untyped_storage()` support was added in PyTorch 2.0.
> Re-add support for PyTorch version 1.x

- transformer_engine/common/include/transformer_engine/logging.h
See [the cuDNN documentation](https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#unique_1072898310).
Pinging @nouiz.
> Add instructions in cuDNN error message for cuDNN error logging

- transformer_engine/pytorch/transformer.py
> Check input dimensions for Sequence Parallel

- tests/pytorch/test_numerics.py
Add numeric tests for the remaining PyTorch API modules (`LayerNormMLP` and `DotProductAttention`).
> PyTorch API numeric tests

- transformer_engine/pytorch/attention.py
- transformer_engine/pytorch/transformer.py
Implement `RoPE` as described in [this](https://arxiv.org/abs/2104.09864) paper.
> [PyTorch] Rotary Position Embedding

- setup.py
- transformer_engine/pytorch/attention.py
Resolves #277 
Expand the range to include latest release; Tested for numerical equivalence, compilation speed, and perf.
> Update FA version

- README.rst
DeepSpeed, Amazon SageMaker Model Parallel Library, Colossal-AI, and PeriFlow
> Added more integrations to README.md

- transformer_engine/pytorch/module/layernorm_linear.py
- transformer_engine/pytorch/module/layernorm_mlp.py
- transformer_engine/pytorch/transformer.py
#287 highlights this inconsistency in docs
> Consistent docs for fuse_wgrad_accumulation

- README.rst
Added NVIDIA NeMo to Integrations section
> Update README.rst - Integrations section

- tests/pytorch/test_onnx_export.py
* Detach output tensor from graph before serializing
* Add missing bf16 gemm tests
> Test ONNX export - missing BF16 GEMM tests + output.json fix

- transformer_engine/pytorch/attention.py
- transformer_engine/pytorch/module/layernorm.py
- transformer_engine/pytorch/module/layernorm_linear.py
- transformer_engine/pytorch/module/layernorm_mlp.py
- transformer_engine/pytorch/module/linear.py
- transformer_engine/pytorch/transformer.py
> Get default dtype from pytorch

- tests/pytorch/test_onnx_export.py
- transformer_engine/pytorch/module/layernorm.py
When running inference use a fwd method that is registered with torchscript.
This bug was reported here: https://github.com/NVIDIA/TransformerEngine/issues/310
Change the export tests to cover this export flow.
Fixes #310
> Fix FP32 LayerNorm ONNX export

- transformer_engine/pytorch/attention.py
Fixes #294, `UnfusedDotProductAttention` for `fp16`, and KV inference cache.
> layer number bug fixes

- tests/paddle/test_operators.py
- transformer_engine/paddle/cpp_extensions.py
- transformer_engine/paddle/csrc/custom_ops.cu
- Refactor `fused_attn_bwd_qkvpacked` and `fused_attn_bwd_kvpacked` to support flash attention.
- Add UTs for flash attention.
> [Paddle] Support flash attention

- transformer_engine/paddle/fp8.py
- transformer_engine/paddle/layer/base.py
Wrap fp8 global state and accessing methods into class `FP8State`.
> [Paddle] Refactor FP8 state

- transformer_engine/jax/dot.py
- transformer_engine/jax/flax/transformer.py
- transformer_engine/jax/fused_attn.py
- transformer_engine/jax/layernorm.py
- transformer_engine/jax/mlp.py
- transformer_engine/jax/praxis/module.py
- transformer_engine/jax/sharding.py
- transformer_engine/jax/softmax.py
This PR is to support
- FSDP on both Flax and Praxis.
- FP8 training on Praxis, based on [Praxis/PR24](https://github.com/google/praxis/pull/24).
> [JAX] FSDP General Support and FP8 Support to Praxis.

- transformer_engine/pytorch/module/layernorm_linear.py
- transformer_engine/pytorch/module/layernorm_mlp.py
- transformer_engine/pytorch/module/linear.py
If `weight` is frozen, then `inputmat` will be `None`, causing an error in `gather_along_..._dim()` when `sequence_parallel` is enabled. I added a check to skip this op if `weight.requires_grad=False`
> fix linear sequence parallel when weight is frozen

- tests/pytorch/test_onnx_export.py
* Use ORT CUDA backend by default.
* Add dynamically shaped input mask in test_export_softmax
* Fix test_softmax_mask_fn - use env. var `NVTE_ONNX_KVCACHE_MAX_SEQ_LEN` to control whether the test uses the default mask generation function or dynamic TRILU mask slicing.
> Improve softmax ONNX export tests

- transformer_engine/pytorch/csrc/extensions/softmax.cu
- transformer_engine/pytorch/softmax.py
> [PyTorch] Catch misaligned address errors in softmax

- transformer_engine/jax/cpp_extensions.py
This fix a crash with JAX nightly.
> [JAX] Use the new API when it is available.

- .github/workflows/docs.yml
Fixes the GH docs generation CI test.
> Pin astroid to 2.15.7

- .github/workflows/build.yml
- .github/workflows/lint.yml
- README.rst
- setup.py
This is a followup to https://github.com/NVIDIA/TransformerEngine/pull/467. I am also using this to check TF-related changes in the internal CI infrastructure.
> Remove remaining references to TensorFlow

- tests/pytorch/test_fused_attn.py
- tests/pytorch/test_numerics.py
- transformer_engine/pytorch/attention.py
- transformer_engine/pytorch/fp8.py
- transformer_engine/pytorch/module/base.py
> [PyTorch] Fixes and tests for FP8 + activation recompute

- transformer_engine/paddle/cpp_extensions.py
- transformer_engine/paddle/csrc/custom_ops.cu
1. Fix the shape of softmax_aux - [b, h, s, s] for max512, [b, h, s, 1] for arbitrary seqlen.
2. Register rng_state as inplace tensor.
> [Paddle] Fix issues

- docs/api/common.rst
Update `amax_compute_algo` and `amax_history_len` in doc to match with latest code.
> Update doc to match with latest code.

- tests/pytorch/test_onnx_export.py
- transformer_engine/pytorch/__init__.py
This PR fixes the dynamo error when running ONNX tests: `RuntimeError: Detected that you are using FX to torch.jit.trace a dynamo-optimized function.`
> [PyTorch] Fix ONNX/dynamo error

- transformer_engine/pytorch/__init__.py
Fix bare-except PyLint error in #562 .
> [PyTorch] Disable pylint bare except

- docs/examples/advanced_optimizations.ipynb
- docs/examples/quickstart.ipynb
> chore: Fix multiple typos

- tests/pytorch/test_numerics.py
- transformer_engine/pytorch/attention.py
Patched tests which made the CI fail for #557
> Fix failing CI due to PR #557 merge

- transformer_engine/pytorch/jit.py
> Fix compatibility with pyTorch 2.0

- tests/paddle/test_layers.py
- tests/paddle/test_operators.py
- transformer_engine/paddle/cpp_extensions.py
- transformer_engine/paddle/csrc/custom_ops.cu
- transformer_engine/paddle/layer/attention.py
- transformer_engine/paddle/layer/transformer.py
Please merge [PR561](https://github.com/NVIDIA/TransformerEngine/pull/561) and [PR580](https://github.com/NVIDIA/TransformerEngine/pull/580) before this one.
Changes in this PR:
- Use separate QKV. Change default QKV layout from `bs3hd/bshd_bs2hd` to `bshd_bshd_bshd`
- Support GQA/MQA (num_gqa_groups).
> [Paddle] Support GQA

- transformer_engine/pytorch/module/base.py
We are seeing unexpected memory usage in models with native FP8 parameters, resulting in no memory savings compared to BF16 params. It turns out we are still allocating workspace buffers for the FP8 and FP8 transpose weights, which are never used.
> [PyTorch] Do not allocate FP8 workspace buffers when params are FP8

- transformer_engine/common/fused_rope/fused_rope.cu
Also fixes the following compilation error for cuda12.1 and below:
```
error: ambiguous "?" operation: second operand of type "float" can be converted to third operand type "const transformer_engine::bf16", and vice versa
```
> Fused rope compute in fp32

- transformer_engine/pytorch/module/layernorm_linear.py
- transformer_engine/pytorch/module/layernorm_mlp.py
> [PyTorch] Fix pipeline parallel execution by using cloned scale inverse tensors

- transformer_engine/pytorch/utils.py
Closes https://github.com/NVIDIA/TransformerEngine/issues/688.
> Slightly more explicit error message for invalid FP8 GEMM dims

- transformer_engine/pytorch/distributed.py
#581 Adds support for non-tensor inputs and outputs to `checkpoint`
> [PyTorch] Update doc for checkpoint API

- README.rst
Added an entry to Latest News section
> Update README - Latest News

- docs/examples/te_llama/te_llama.py
- docs/examples/te_llama/tutorial_accelerate_hf_llama_with_te.ipynb
- docs/examples/te_llama/utils.py
Fixes for the TELlama tutorial so that the benchmark results are more representative
> Llama accelerate tutorial

- transformer_engine/pytorch/module/base.py
Fix the default initialization configs of TP comm overlap with userbuffer.
> Fix the default userbuffer communicator init settings

- transformer_engine/pytorch/attention.py
LRU cache usage is leading to IMAs in certain LLM workloads
@vasunvidia
> [PyTorch] Avoid using LRU cache for cu_seqlens

- transformer_engine/jax/cpp_extensions.py
> [JAX] [B] Fixed Batcher in DBiasCastTranspose Primitive

- transformer_engine/jax/cpp_extensions.py
Remove `act_enum` from the del list in `ActLuPrimitive*.partition`.
1. Remove `act_enum` from the del list in `ActLuPrimitive*.partition`.
> [JAX] Fix the Failures on Partition of ActPrimitives

- transformer_engine/pytorch/csrc/userbuffers/userbuffers.cu
Making sure that the UB timeouts have consistent error messaging
- Fixing error messaging to provide consistent output to simplify the work of log parsers
> [UB] Fixing consistency of error messages.

- .github/workflows/trigger-ci.yml
Add @nvcforster to list of authorized TE CI users.
- Add TE CI user
> Add user to TE CI

- build_tools/build_ext.py
Build fix for installing TE's paddle framework extension using `pip install -e .`.
Fix local search path for `lib_transformerengine.so` for editable (in-place) TE paddle build.
> [PaddlePaddle] Fix editable build for paddle

- .github/workflows/blossom-ci.yml
- .github/workflows/trigger-ci.yml
Fix minor security vulnerability when triggering CI
- Fix minor security vulnerability when triggering CI
> Fix minor security vulnerability when triggering CI

- transformer_engine/jax/flax/module.py
This PR changes the order of the gated activation call in `LayerNormMLP` so that it is consistent in all conditional branches. 
This order is important for checkpointing as a miss-order may cause drops in training accuracy for LLama.
> [JAX] Made order of gated act consistent in all branches

- transformer_engine/pytorch/distributed.py
This PR fixes misplaced asserts on a module attribute that only exists for TE modules, but is incorrectly applied to non-TE modules.
Supersedes #913.
- Assert on Fp8 primary weights are now applied only for TE modules with `primary_weights_in_fp8` attribute.
> [PyTorch] Fixed assert on primary Fp8 weights in `prepare_te_modules_for_fsdp()`

- tests/pytorch/test_onnx_export.py
Deduplicated class FP8GemmModule in a unit test.
- Code refactor
> remove code duplication in a test

- .github/PULL_REQUEST_TEMPLATE.md
> Add more type of change to the PR template

- qa/format.sh
Add a small-script to run pre-commit hooks locally.
Add a small-script to run pre-commit hooks locally.
> Script to run pre-commit hooks locally

- transformer_engine/common/transpose/cast_transpose.cu
- transformer_engine/common/transpose/cast_transpose_fusion.cu
- transformer_engine/common/transpose/transpose.cu
https://github.com/NVIDIA/TransformerEngine/pull/258 added a basic performance model for transpose to choose optimal configs for NVRTC kernels. However, it queries the number of available SMs for each config, resulting in many calls to the CUDA driver (mainly to query the current device). In my profiling, about 1/3 of the CPU runtime for [`tex.fused_cast_transpose_noop`](https://github.com/NVIDIA/TransformerEngine/blob/a3df1d73ad68b75d3e8fbbf21a2870c531e058c8/transformer_engine/pytorch/csrc/extensions/transpose.cu#L29) is spent in calls to the CUDA driver. This PR cuts down on this overhead by querying the number of available SMs once.
- Query number of SMs once in transpose performance models
> Reduce CUDA driver calls when choosing transpose kernels

- .github/workflows/blossom-ci.yml
- .github/workflows/trigger-ci.yml
- Simplify logic for launching CI
> Simplify logic for launching CI

- transformer_engine/paddle/csrc/custom_ops.cu
- transformer_engine/paddle/layer/base.py
Fix device memory leak caused by pp forward hook.
- Avoid register PP fwd begin hook when CUDA graph is not enabled or PP is not enabled.
> [Paddle] Fix device memory leak

- transformer_engine/pytorch/csrc/comm_gemm_overlap.h
- transformer_engine/pytorch/csrc/userbuffers/userbuffers-host.cpp
This fixes some Cpplint warnings introduced by https://github.com/NVIDIA/TransformerEngine/pull/986.
- Fix linter warnings
> [PyTorch] Fix linter warnings

- .github/workflows/build.yml
Fix Paddle build failure in Github check.
- Update Paddle image
> [Paddle] Update Paddle image

- transformer_engine/pytorch/cpu_offload.py
Implemented a new load balanced offloading algorithm to utilize the CPU/GPU interconnect bandwidth to the maximum extent.
> Load balanced offloading algorithm

- transformer_engine/pytorch/attention.py
- transformer_engine/pytorch/transformer.py
Hello,
we noticed a few issues for encoder decoder models with cross attention.
I would like to suggest the following changes to fix them.
- `transformer.py`: arguments not propagated correctly, should be self-explanatory
- `attention.py`: I think it is necessary to check for self attention here. Only foror cross-attention `attention_mask` is supposed to be a tuple.
> [PyTorch] Fix issues with cross attention

- build_tools/utils.py
- build_tools/wheel_utils/Dockerfile.aarch
- build_tools/wheel_utils/Dockerfile.x86
- build_tools/wheel_utils/build_wheels.sh
- qa/L0_jax_wheel/test.sh
- qa/L0_paddle_wheel/test.sh
- qa/L0_pytorch_wheel/test.sh
- qa/L1_pytorch_distributed_unittest/test.sh
- setup.py
- transformer_engine/common/__init__.py
- transformer_engine/jax/__init__.py
- transformer_engine/paddle/__init__.py
- transformer_engine/pytorch/__init__.py
Make build time improvements and bug fixes for publishing wheels.
- Add build for metapackage.
- Catch incorrect installations during import and provide logging messages.
- Improve scripts for wheel build.
- Bug fix for wheels introduced in #946 that needs xla include directory during jax extensions build.
> Improvements for building wheels

- docs/_templates/layout.html
Added Adobe analytics to the User Guide.
- Added analytics script.
> Added Adobe analytics to the documentation

- .github/workflows/trigger-ci.yml
Add @huanghua1994 to list of authorized CI users.
- Update CI users
> Update CI users

- .github/workflows/trigger-ci.yml
Add @pggPL to list of CI users.
- Add @pggPL to list of CI users
> Update list of CI users

- tests/pytorch/fused_attn/test_fused_attn_with_cp.py
CP unit test fix.
- skip FP8 unit tests if hardware does not support FP8
- Change A
- Change B
> Fix CP unit test on A100 and L40s

- qa/L1_pytorch_distributed_unittest/test.sh
Adds fixes for PyTorch distributed tests.
- Install `prettytable` since it's needed for printing logs from distributed tests.
- Change megatron-LM to latest commit which [includes fixes](https://github.com/NVIDIA/Megatron-LM/commit/09766613d7cd7ee483513ec32baa0d84ce16720c) to correctly check package version.
- Remove `sed` hack since megatron-LM has removed the deprecated argument `apply_query_key_layer_scaling` to TE's `TransformerLayer`.
- Omit installing older version of setuptools needed to still import `packaging` from `pkg_resources`.
> [PyTorch] Fix distributed testing

- tests/pytorch/fused_attn/test_fused_attn.py
PR removes duplicate code found in `tests/pytorch/fused_attn/test_fused_attn.py`:
```
_DUMMY_CUDA_RNG_STATE_TRACKER = CudaRNGStatesTracker()
_DUMMY_CUDA_RNG_STATE_TRACKER.add("model-parallel-rng", seed)
def get_dummy_cuda_rng_tracker():
"""Get cuda rng tracker."""
return _DUMMY_CUDA_RNG_STATE_TRACKER
```
First Part located on line [1850](https://github.com/NVIDIA/TransformerEngine/blob/7b152a83475085355f4a14406dd690a3753267e4/tests/pytorch/fused_attn/test_fused_attn.py#L1850), second one located on line [1857](https://github.com/NVIDIA/TransformerEngine/blob/7b152a83475085355f4a14406dd690a3753267e4/tests/pytorch/fused_attn/test_fused_attn.py#L1857).
Please list the changes introduced in this …
> [PyTorch] remove duplicate code

- transformer_engine/pytorch/attention.py
- transformer_engine/pytorch/csrc/extensions.h
- transformer_engine/pytorch/csrc/extensions/attention.cu
Enable FA3 in all CP implementation. Work in BF16 and FP16 now.
> Add FlashAttention3 to CP implementations

- tests/pytorch/test_fused_rope.py
- transformer_engine/common/fused_rope/fused_rope.cu
- transformer_engine/common/include/transformer_engine/fused_rope.h
- transformer_engine/pytorch/attention.py
- transformer_engine/pytorch/csrc/extensions.h
- transformer_engine/pytorch/csrc/extensions/apply_rope.cu
Let the Fused RoPE kernels support CP with THD format.
> [PyTorch] Let Fused RoPE support CP with THD format

- transformer_engine/pytorch/attention.py
Fix a `seq_dim` bug in CP implementation.
- Change A
- Change B
> Fix seq_dim in CP implementation

- tests/jax/test_fused_attn.py
- transformer_engine/common/fused_attn/fused_attn.cpp
Support GQA/MHA with THD format
- Support GQA with THD format
- Add GQA + THD JAX unit tests
> Add THD + GQA supports

- tests/pytorch/fused_attn/test_fused_attn.py
Skip T3HD/TH3D tests for MQA/GQA and rerun pipeline with cuDNN 9.6.
- Skip T3HD/TH3D tests for MQA/GQA as they are not applicable
> [PyTorch] Skip t3hd/th3d for MQA/GQA tests

- transformer_engine/pytorch/attention.py
This PR adds a check for GPU availability so that CPU-only systems can import Transformer Engine properly.
- Add a GPU check
> Add check for GPU availability in attention

- .github/workflows/trigger-ci.yml
> Add user to CI

- transformer_engine/pytorch/csrc/common.h
Fixing the lack of virtual destructor in the Quantizer class.
> Add the virtual destructor to the Quantizer class

- transformer_engine/pytorch/tensor/float8_tensor.py
This PR fixes issues created by #1427 for context parallelism.
- Fix CP
> Fix d715c83

- transformer_engine/jax/flax/module.py
- transformer_engine/jax/flax/transformer.py
> [JAX] Lint Fix

- transformer_engine/pytorch/distributed.py
Fix a silly typo in FP8 all-gather function.
- Fix typo
> [PyTorch] Fix typo

- .github/workflows/build.yml
Transformer Engine 2.0 updated the minimum requirement to CUDA 12.1.
- Update C++ build test to use CUDA 12.1
- Update PyTorch build test to use CUDA 12.8
> Update build test CUDA version to 12.1

- transformer_engine/common/comm_gemm_overlap/comm_gemm_overlap.cpp
Bulk TP overlap takes 4x longer time when used with full iteration CUDA graph. This is because of launching GEMM kernel first on default stream.
This change fixes this issue by launching GEMM on _compute_stream[0] which has low stream priority.
Changed GEMM stream to _stream_compute[0] which launches comm. kernel before launching GEMM.
> Launch GEMM on compute_stream which has low priority.

- transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers-host.cpp
Setup of UB via MPI got broken in #1470.
- Change A
- Change B
> Fix UB with MPI init

- transformer_engine/pytorch/triton/permutation.py
Fix import error on CPU only devices
- Change A
- Change B
> Fix import error on CPU only devices

- setup.py
- tests/pytorch/distributed/run_layer_with_overlap.py
This PR extends current test for TP overlap layer to add more configurable parameters.
- [ x ] New feature (non-breaking change which adds functionality)
- Change A
- Change B
> Blackwell devel commoverlap mlperftests

- transformer_engine/pytorch/module/grouped_linear.py
[PR1474](https://github.com/NVIDIA/TransformerEngine/pull/1474) has fixed some issues in some modules. However, the logic in `grouped_linear.py` does not change. This PR is to add the fix to grouped GEMM, otherwise, then training MoE models with grouped GEMM, the following error will occur:
```
...
[rank0]: param.grad is not None 
[rank0]: AssertionError: param.grad being None is not safe when overlap_grad_reduce is True
```
The root cause is that the saved weight for backward usages does not have attribute `grad_added_to_main_grad`.
I also change the name from `w` to `weight` so that it can be consistent with the one in layernorm_linear.py.
- Save `origin_weight` in forward pass and use it in the corresponding part since it has params …
> [PyTorch] Fix issues for MCore DDP in grouped GEMM.

- tests/pytorch/test_cuda_graphs.py
- tests/pytorch/test_sanity.py
- transformer_engine/common/recipe/current_scaling.cu
- transformer_engine/pytorch/ops/op.py
> [PyTorch] Add tests for current scaling; misc related fixes

- transformer_engine/pytorch/attention.py
Put `softmax_lse` transpose in correct stream so that it's synced correctly.
> fix a sync race error of softmax_lse in CP+THD+P2P

- transformer_engine/jax/attention.py
Converting `SegmentID` to `Length` and `Offset` tensors is expensive due to quadric nature of computing an arbitrary attention mask. This PR adds a fast path for cuddn causal attention that reduces the work to linear time and memory. It relies on the constraints of the implicit ordering expected by cudnn causal attention mask.
New approach to compute length and offset.
> [JAX] Add fast path for causal masking with segment IDs.

- .github/workflows/trigger-ci.yml
Add @zhongbozhu, @kwyss-nvidia, @BestJuly as authorized CI users.
- Update list of authorized CI users
> Update list of authorized CI users

- transformer_engine/pytorch/attention.py
Added support for offloading with LoRa, had to add activation offloading support for FP8 attention.
> Added attention activation offloading support for TE v2.0

- examples/jax/encoder/run_test_multiprocessing_encoder.sh
- examples/jax/encoder/test_multiprocessing_encoder.py
- qa/L0_jax_distributed_unittest/test.sh
Improving the test_multiprocessing_encoder.py run script
- [] Documentation change (change only to the documentation, either a fix or a new content)
> [JAX] Improving the test_multiprocessing_encoder.py run script

- README.rst
- docs/installation.rst
Update installation section with comprehensive guidelines
- Add detailed system requirements
- Document environment variables for customizing build process
- Update FlashAttention support to cover both version 2 and 3
- Add troubleshooting section with solutions for common installation issues
> README.md - Installation section

- transformer_engine/pytorch/distributed.py
- transformer_engine/pytorch/module/layernorm_linear.py
- transformer_engine/pytorch/module/layernorm_mlp.py
- transformer_engine/pytorch/module/linear.py
This is a remake of the merge request for symmetric memory all reduce that was broken from merging with signatures. This should be a one to one same MR.
- Change A
- Change B
> Re Do symmetric memory merge request

- transformer_engine/common/util/cuda_runtime.cpp
Fixes #1692
- Change A
- Change B
> Check CUDA driver KMD version for multicast symbol support

- transformer_engine/common/comm_gemm_overlap/comm_gemm_overlap.cpp
https://github.com/NVIDIA/TransformerEngine/pull/1708 introduced a bug in a Userbuffers convenience macro that converts an `NVTEShape` to an `std::vector`. That PR changed `NVTEShape` to hold data internally, so each instance will have a different data pointer. If a function invocation is passed into the `AS_VECTOR` macro, the function will be called multiple times and each returned value will have different data pointers.
- Debug UB conversion function from NVTEShape to std::vector
> [PyTorch] Debug UB conversion function from NVTEShape to std::vector

- transformer_engine/pytorch/cpp_extensions/gemm.py
- transformer_engine/pytorch/tensor/_internal/float8_blockwise_tensor_base.py
- transformer_engine/pytorch/tensor/_internal/float8_tensor_base.py
- transformer_engine/pytorch/tensor/_internal/mxfp8_tensor_base.py
- transformer_engine/pytorch/tensor/utils.py
- transformer_engine/pytorch/utils.py
Cache torch.Tensor() to reduce CPU overhead in
- `clear_tensor_data()`
- `clear()`
- transformer_engine/pytorch/tensor/_internal/float8_blockwise_tensor_base.py
- transformer_engine/pytorch/tensor/_internal/float8_tensor_base.py
- transformer_engine/pytorch/tensor/_internal/mxfp8_tensor_base.py
- transformer_engine/pytorch/tensor/utils.py
- transformer_engine/pytorch/utils.py
> Cache torch.Tensor() to reduce CPU overhead

- build_tools/jax.py
A bug fix from #1781 
- Add correct extension for JAX builds.
> Fix JAX build

- setup.py
#1521 removed the tests for which these were required.
- Remove `prettytable` and `PyYAML` as test dependencies.
> Remove unused dependencies

- tests/pytorch/test_parallel_cross_entropy.py
- transformer_engine/pytorch/cross_entropy.py
- transformer_engine/pytorch/triton/cross_entropy.py
Added support for ignoring tokens while computing CE loss and gradients for loss.
> Added token ignoring for CE loss

- README.rst
A small change to fix the rendering of the readme on PyPI which we use as the description for the package. Without this change, the package upload fails.
- Add correct number of underlining chars for fixing README render on PyPI.
> Fix README render for uploading package to PyPI

- tests/jax/test_custom_call_compute.py
Fixes incorrectly skipped `test_quantize_dbias` tests in `test_custom_call_compute.py`. The check had a `flatten_axis <= 0` check that should instead have been `flatten_axis == 0`. Additionally, this skip check can be removed entirely by providing only valid flatten_axes in the test params.
Fixes #1785
- Remove incorrect test skipping logic and fix test cases in params for `test_quantize_dbias`
> [JAX] Fix incorrectly skipped test_quantize_dbias tests

- README.rst
> Updated README - Added conda installation

- tests/jax/test_distributed_fused_attn.py
- transformer_engine/jax/cpp_extensions/attention.py
- transformer_engine/jax/sharding.py
This PR supports sliding window attention (SWA) in context parallel ring attention using THD format and striped sharding.
> [JAX] Support SWA in CP Ring Attn THD striped sharding

- transformer_engine/jax/csrc/extensions/gemm.cpp
Fix all build from PR 1666.
- Fix all build from PR 1666.
> Fix all framework build from PR 1666

- tests/pytorch/fused_attn/run_fused_attn_with_cp.py
- tests/pytorch/fused_attn/test_fused_attn_with_cp.py
- transformer_engine/pytorch/attention/dot_product_attention/context_parallel.py
- transformer_engine/pytorch/attention/dot_product_attention/utils.py
fix: 
(1) UT ignores MLA; 
(2) bshd format runtime error. 
Ban fp8 mla attn + cp due to correctness problem
- Change A
- Change B
> Fix MLA CP Bugs

- qa/L3_pytorch_FA_versions_test/test.sh
- transformer_engine/pytorch/attention/dot_product_attention/utils.py
Bump up FA to 2.8.1
- Bump FA version to 2.8.1
> Bump up FA to 2.8.1

- transformer_engine/pytorch/attention/dot_product_attention/utils.py
Fix the condition error of the FP8 attention in `get_attention_backend`
- Change A
- Change B
> Fix the condition error when checking fp8 attn in `get_attention_backend`

- transformer_engine/common/comm_gemm_overlap/comm_gemm_overlap.cpp
The current destructor calls cudaStreamDestroy() and then proceeds to call cudaFree() on various internal buffers without first synchronising the stream to ensure all work is complete. This can cause invalid cuda access if the cudaFree happens before the work on the stream is complete. We add a `cudaStreamSynchronize()` before `cudaStreamDestroy()` to prevent this error, we also catch and warn about any exceptions thrown in the destructor to prevent the program aborting
- Add `cudaStreamSynchronize` to `CommOverlapCore::~CommOverlapCore`
- Catch exceptions thrown by `CommOverlapCore::~CommOverlapCore`
> fix: Add stream synchronization before destroying MPI communicator

- transformer_engine/pytorch/cpu_offload.py
Had to deal with assymetric layers when double buffering.
> Fixed double buffering issue for assymetric layers

- tests/pytorch/test_fused_router.py
- transformer_engine/common/fused_router/fused_moe_aux_loss.cu
- transformer_engine/common/fused_router/fused_score_for_moe_aux_loss.cu
- transformer_engine/common/fused_router/fused_topk_with_score_function.cu
- transformer_engine/common/fused_router/utils.h
Fix kernels bug on the case: all the logits < 0
- Change A
- Change B
> Fix corner case in router fuson

- transformer_engine/jax/csrc/extensions/activation.cpp
- transformer_engine/jax/csrc/extensions/normalization.cpp
Fixes #2093
- fix narrowing conversion from size_t to unsigned long
> fix narrowing conversions

- build_tools/utils.py
Fixes #2110 
- The varname `version` causes `UnboundLocalError: local variable 'version' referenced before assignment`.
> [Pytorch] Fix `UnboundLocalError` during build

- tests/pytorch/test_fusible_ops.py
- tests/pytorch/test_numerics.py
- tests/pytorch/test_sanity.py
- transformer_engine/pytorch/csrc/extensions.h
- transformer_engine/pytorch/csrc/extensions/activation.cpp
- transformer_engine/pytorch/csrc/extensions/pybind.cpp
- transformer_engine/pytorch/module/layernorm_mlp.py
- transformer_engine/pytorch/ops/basic/__init__.py
- transformer_engine/pytorch/ops/basic/activation.py
- transformer_engine/pytorch/transformer.py
Expose more activation functions to `LayerNormMLP` and `te.ops`.
- Change A
- Change B
> [PyTorch] Expose more activation functions

- examples/pytorch/comm_gemm_overlap/te_layer_with_overlap.py
- tests/pytorch/distributed/run_layer_with_overlap.py
- tests/pytorch/distributed/test_fusible_ops_with_userbuffers.py
- transformer_engine/pytorch/module/base.py
Fixes test failures on UB overlap changes
- Fix incorrect UserBufferQuantizationMode references
- Fix incorrect handling for custom `ub_cfgs`
> Fix CI failures for UB overlap changes

- tests/jax/test_custom_call_compute.py
Address L2 JAX unit test failures for dact with current scaling due to recent changes to removed our intermediate cast to fp32 because calling the primitive.
- Do lower precision comparison `dbias` comparison for particular activation type for current scaling dact, similar to existing `dbias` tolerance check for MXFP8
> [JAX] Address tolerance check for current scaling dact dbias

- transformer_engine/pytorch/attention/dot_product_attention/backends.py
- transformer_engine/pytorch/attention/dot_product_attention/context_parallel.py
> [PyTorch] Fix QuantizedTensorBase -> QuantizedTensorStorage

- transformer_engine/jax/sharding.py
We cannot use sharding constraints on `Manual` axes set by shard map. This PR fixes an issue where multiple mesh axes mapped to a single shape axis, such as assigning `get_all_mesh_axes()` to a single shape axis, would not correctly filter out the Manual axes. 
- If applicable, unpack multiple axes in a sharding constraint tuple assigned to a single shape axis and filter out `Manual` shard map axes
> [JAX] Fix shard map issue when `get_all_mesh_axes()` is used

- transformer_engine/jax/cpp_extensions/activation.py
- transformer_engine/jax/cpp_extensions/normalization.py
- transformer_engine/jax/cpp_extensions/quantization.py
- transformer_engine/jax/csrc/extensions/activation.cpp
- transformer_engine/jax/csrc/extensions/normalization.cpp
- transformer_engine/jax/csrc/extensions/quantization.cpp
- transformer_engine/jax/dense.py
- transformer_engine/jax/flax/module.py
- transformer_engine/jax/flax/transformer.py
- transformer_engine/jax/layernorm_dense.py
- transformer_engine/jax/layernorm_mlp.py
Activation/Normalization to output amax for later quantization in CurrentScaling
> [JAX] Activation/Normalization to output amax for later quantization in CurrentScaling

- tests/cpp_distributed/test_comm_gemm.cu
Skip tests with fp8 dtypes on unsupported devices.
- Skip tests with fp8 dtypes on unsupported devices.
> Skip fp8 tests on unsupported devices
